# 0. IMPORTAR LIBRERIAS

In [1]:
#básicos
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import numpy as np
import numpy.linalg as la
import math # to use isnan
from time import perf_counter as clock

#grafos
import networkx as nx


# de detección de anomalías
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.ensemble import IsolationForest
from sklearn.covariance import EllipticEnvelope
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from pyod.models.kde import KDE
from  pyod.models.sampling import Sampling
from pyod.models.gmm import GMM
# from pyod.models.lunar import LUNAR
from pyod.models.ecod import ECOD


# de minería de asociación
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,fpgrowth,association_rules,fpmax
from scipy.spatial import ConvexHull
from sklearn.preprocessing import KBinsDiscretizer

%matplotlib inline

In [2]:
sns.set_theme()
pd.set_option("display.max_rows", None, "display.max_columns", None)

# 1. CARGAR DATASET

In [3]:
dfs=pd.read_csv('dfs_fase3COMPLETO.csv')
dfs['indice']=dfs.index

In [4]:
dfs = dfs.rename(columns={
    'SE1_pred': 'SE1',
    'SE2_pred': 'SE2',
    'SE3_pred': 'SE3',
    "cluster_ganador": "clase"
})

dfs.head()

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice
0,Transporte,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,Si,4,182,2882,11756400,-0.230632,-0.122036,-0.001522,-0.002303,0.134220,0.176406,-0.056739,-0.030522,-0.149470,0.164997,-0.101998,-0.269728,0.280453,0.097403,0.188180,-0.512083,0.142109,0.154056,-0.289179,0.131029,0.087097,0.158542,0.065064,0.098843,0.241269,-0.301444,-0.155364,-0.045086,0.110323,-0.290308,-0.021428,-0.183431,-0.165765,0.050169,0.516933,-0.699410,-0.640868,-1.197668,0,0
1,agricultura,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,0,242,2812,48000000,-0.502233,-0.314990,0.007575,0.003116,0.000818,0.132630,0.047187,-0.261014,-0.207582,0.041610,0.177906,0.090063,0.021362,0.113700,-0.266953,0.032131,0.100277,0.052154,0.042238,-0.037100,0.025141,-0.161671,-0.109760,0.206130,0.286944,-0.508839,-0.089393,0.386624,0.709633,0.170777,0.529664,-0.574655,-0.339869,0.541785,0.226969,1.292304,1.291991,-0.388060,2,1
2,Salud y Protección Social,Ejecutivo,Centralizada,Prestación de servicios,Contratación régimen especial,No,No,No,No,No,No,No Válido,No,Si,0,132,2856,8074779,1.089181,-0.408082,0.010449,0.011622,0.011589,0.238742,-0.031481,-0.343014,-0.053873,-0.060902,-0.056533,-0.014609,0.334820,0.020835,0.121477,-0.550172,0.169496,-0.077804,-0.090625,0.054882,0.036406,0.091204,0.087001,-0.132702,0.073605,0.015176,-0.013934,0.034000,0.075565,0.016952,0.002795,0.079164,-0.010538,0.088693,-0.077400,1.541353,1.246222,-0.408194,2,2
3,Educación Nacional,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,3,15,3035,14885150,-0.338042,-0.278063,0.010924,0.013671,-0.009648,-0.363740,-0.090634,0.265894,0.020466,-0.003160,-0.173324,0.609988,-0.310310,-0.457564,-0.354598,-0.334695,-0.015035,0.882740,0.052598,-0.168797,-0.091880,0.185196,-0.353456,-0.112787,0.114576,-0.231244,0.083896,0.326041,-0.051403,0.082964,-0.121959,-0.043341,-0.058637,0.063921,0.094111,-0.332191,-0.062011,-0.105104,0,3
4,Inclusión Social y Reconciliación,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,21,305,2888,28820000,-0.487375,-0.318814,0.011714,0.008560,0.014443,0.285101,-0.016738,-0.257863,-0.212083,0.107955,0.124422,-0.003640,-0.141943,0.141153,-0.214277,0.193188,0.021567,-0.002867,-0.011424,-0.052882,0.066520,-0.447140,0.143064,0.269374,0.558160,-0.470381,0.162990,-0.043987,-0.366043,1.742416,-0.265758,-0.090741,0.681484,0.093808,-0.622647,-0.693104,0.502032,0.551954,0,4

# 2. DETECCIÓN DE ANOMALÍAS

## 2.1 LOCAL OUTLIER FACTOR

In [114]:
nolineales=['SE1','SE2','SE3']
dfss=dfs.sample(8000,random_state=42).reset_index(drop=True)
datos=dfss.loc[:,nolineales]
estimator=LocalOutlierFactor(n_neighbors=10,novelty=True,contamination=0.01)
X=datos.values
estimator.fit(X)
dfss['outlier']=estimator.predict(X)

fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='outlier',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
fig.show()

In [115]:
candidatos=[2116, 44596, 36359 ,4265, 423]

In [116]:
dfss.loc[dfss.indice.isin(candidatos),['indice','outlier']]

      indice  outlier
2347    2116        1
4689   44596        1
5114   36359        1
6224    4265        1
6683     423        1

## 2.2 ENVOLVENTE CONVEXA

In [117]:
def profundidad_convexa(datos,kmin):
    k=1
    copia=datos.values
    n,m=copia.shape
    depths=np.zeros(n)
    indices=np.array(range(len(depths)))
    while len(copia)>m: #En función ConvexHull, no se puede calcular envolvente sin al menos m+1 puntos (m es la dimensión)
        hull=ConvexHull(copia)
        depths[indices[hull.vertices]]=k
        if k==kmin:
            frontera=indices[hull.vertices]
        copia=np.delete(copia,hull.vertices,axis=0)
        indices=np.delete(indices,hull.vertices)
        k+=1
    depths[indices]=k #Si quedan puntos por asignar, estos tienen la máxima profundidad
    return depths,frontera

In [118]:
depths,frontera=profundidad_convexa(datos,5)
dfss["profundidad"]=depths

In [119]:
fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='profundidad',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
fig.show()

In [120]:
dfss.loc[:,'outlier']=1
dfss.loc[dfss.profundidad==1,'outlier']=-1
fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='outlier',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
fig.show()

In [121]:
dfss.loc[dfss.indice.isin(candidatos),['indice','outlier']]

      indice  outlier
2347    2116       -1
4689   44596       -1
5114   36359       -1
6224    4265       -1
6683     423       -1

## 2.3 KERNEL DENSITY ESTIMATION

In [122]:
estimator=KDE(contamination=0.05)
X=datos.values
estimator.fit(X)
dfss['outlier']=estimator.predict(X)
dfss['outlier']=1-2*dfss['outlier'].values #Para que el número -1 sea los outliers
fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='outlier',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
fig.show()

In [123]:
dfss.loc[dfss.indice.isin(candidatos),['indice','outlier']]

      indice  outlier
2347    2116       -1
4689   44596       -1
5114   36359       -1
6224    4265       -1
6683     423       -1

## 2.4 ALGORITMO ECOD

In [124]:
estimator=ECOD(contamination=0.02)
X=datos.values
estimator.fit(X)
dfss['outlier']=estimator.predict(X)
dfss['outlier']=1-2*dfss['outlier'].values #Para que el número -1 sea los outliers
fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='outlier',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
fig.show()

In [125]:
dfss.loc[dfss.indice.isin(candidatos),['indice','outlier']]

      indice  outlier
2347    2116       -1
4689   44596       -1
5114   36359       -1
6224    4265       -1
6683     423       -1

## 2.5 SVM DE UNA CLASE

In [126]:
estimator=OneClassSVM(gamma='scale',nu=0.01)
X=datos.values
estimator.fit(X)
dfss['outlier']=estimator.predict(X)
fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='outlier',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
fig.show()

In [127]:
dfss.loc[dfss.indice.isin(candidatos),['indice','outlier']]

      indice  outlier
2347    2116       -1
4689   44596       -1
5114   36359       -1
6224    4265       -1
6683     423       -1

# 3. DISCUCIÓN DATOS ANOMALOS

In [161]:
candidatos=[2116, 44596 ,4265,38461]

In [163]:
letras=['A','B','C','D']

def add_mark(fig,dfc,indx,color,hlabel):
    xx,yy,zz=dfc.loc[dfc.indice==indx,['SE1','SE2','SE3']].values[0,:]
    fig.add_trace(go.Scatter3d(x=[xx], y=[yy],z=[zz],marker=dict(size=4,color=color),hovertext=hlabel,showlegend=False))
    fig.add_trace(go.Scatter3d(x=[xx], y=[yy],z=[zz],mode="text",text=hlabel,showlegend=False))
fig = px.scatter_3d(dfss, x='SE1', y='SE2', z='SE3',color='clase',opacity=0.7,hover_data=['clase','indice'])
scene=dict(aspectratio=dict(x=1, y=1,z=1))
fig.update_traces(marker_size = 2)
fig.update_scenes(aspectmode='data')
for k in range(4):
    add_mark(fig,dfss,candidatos[k],"green","Punto "+letras[k])
fig.show()

## 3.1 PRIMER ANOMALO

In [147]:
dfss.loc[dfss.indice==candidatos[0],:]

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q,outlier,profundidad
2347,defensa,Ejecutivo,Centralizada,Prestación de servicios,Mínima cuantía,No,Si,No,Si,No,No,No Válido,No,Si,2,3,1,2,0.201081,1.381923,-0.101329,-0.019134,-0.448056,-0.017657,-0.1349,-0.041319,0.022469,-0.068705,-0.191619,0.350309,0.331975,-0.204866,0.078309,-0.486484,0.126389,-0.522498,-0.035933,0.22323,0.076906,0.525059,-0.201145,-0.202871,-0.339173,0.256922,-0.043857,-0.012546,0.083169,0.503831,-0.235153,0.131832,-0.343534,0.203429,-0.279923,1.551939,2.318834,-0.785418,2,2116,2,3,1,2,-1,1.0

El contrato fue identificado como un caso atípico porque presenta características poco comunes frente a la mayoría de contratos del dataset. Aunque pertenece a la modalidad de mínima cuantía, tiene una duración muy larga de 358 días y además fue prorrogado, algo que normalmente no ocurre en este tipo de contratos. También incluye pago adelantado y obligaciones ambientales, lo que hace que su comportamiento sea diferente al de los demás registros analizados. Por esta razón, el modelo lo detectó como un contrato alejado del patrón general de los datos.

## 3.2 SEGUNDO ANOMALO

In [148]:
dfss.loc[dfss.indice==candidatos[1],:]

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q,outlier,profundidad
4689,Salud y Protección Social,Ejecutivo,Centralizada,Decreto 092 de 2017,Contratación régimen especial,No,No,No,No,No,No,No Válido,No,No,0,1,2,1,2.207266,-0.594508,0.014677,0.016784,0.08915,0.355825,0.003395,-0.791883,-0.092761,0.121742,0.125767,-0.206243,-0.368539,0.087649,0.00959,0.550968,0.087245,0.071338,0.00545,-0.072339,0.011376,-0.038077,-0.210856,-0.085247,-0.04059,-0.044634,0.122244,0.042276,-0.120796,0.070921,-0.106539,-0.011747,-0.168933,0.154766,0.097665,-0.857302,0.447303,3.005442,1,44596,0,1,2,1,-1,1.0

Este contrato fue identificado como un caso atípico porque presenta características diferentes a las que normalmente aparecen en el conjunto de datos. Aunque tiene un valor relativamente moderado y una duración corta de 87 días, pertenece al tipo “Decreto 092 de 2017” bajo contratación de régimen especial, una modalidad menos frecuente dentro de los registros analizados. Además, algunas de sus variables transformadas muestran valores bastante alejados del promedio, especialmente en las componentes MCA y en SE3, lo que indica que el contrato se comporta de manera distinta frente a los demás. Por esta razón, el modelo lo detectó como un registro fuera del patrón general de contratación.

## 3.3 TERCER ANOMALO

In [149]:
dfss.loc[dfss.indice==candidatos[2],:]

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q,outlier,profundidad
5114,Servicio Público,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,2,3,3,2,-0.442577,-0.190577,0.004161,0.002818,0.02669,0.185955,-0.043467,-0.162269,-0.052908,0.073032,0.046968,0.133886,-0.0402,-0.095047,0.021912,0.121379,0.022787,-0.088817,0.051312,0.06866,0.055401,-0.151738,0.00432,-0.078546,0.073219,0.072032,0.195943,-0.081875,-0.01478,-0.219008,-0.012906,0.208623,-0.122016,0.21252,0.030249,-0.857972,0.464175,3.023987,1,36359,2,3,3,2,-1,1.0

Este contrato fue identificado como un caso atípico porque, aunque en apariencia tiene características normales dentro del conjunto de datos, presenta un comportamiento diferente en las variables transformadas utilizadas por el modelo. El contrato pertenece al sector de servicio público y fue realizado por contratación directa bajo prestación de servicios, con una duración relativamente alta de 294 días. Además, algunas de sus componentes MCA y especialmente la variable SE3 muestran valores alejados del comportamiento promedio, lo que indica que el registro se ubica en una zona poco común dentro de los datos analizados. Por esta razón, el modelo lo clasificó como un contrato fuera del patrón general.

## 3.4 CUARTO ANOMALO

In [150]:
dfss.loc[dfss.indice==candidatos[3],:]

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q,outlier,profundidad
6224,Servicio Público,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,No,2,2,1,2,-0.397731,-0.197147,0.005842,0.006077,0.016604,0.148651,-0.036331,-0.145595,-0.000919,0.052624,0.076648,0.179538,-0.013848,-0.142886,0.058698,0.08893,0.028534,-0.112758,0.075234,0.082162,0.080118,-0.156285,0.005067,-0.117989,0.065349,0.109027,0.241389,-0.095134,-0.028666,-0.236057,-0.037698,0.281472,-0.170756,0.289937,0.022665,1.780232,-2.057557,0.805376,3,4265,2,2,1,2,-1,1.0

Este contrato fue identificado como un caso atípico porque presenta un comportamiento diferente al de la mayoría de contratos del dataset. Aunque corresponde a una contratación directa por prestación de servicios, tiene características que lo hacen poco común, como un tiempo de espera de 24 días antes del inicio y un estado BPIN “No válido”. Además, las variables transformadas del modelo, especialmente en las componentes SE1 y SE2, muestran valores bastante alejados del promedio, indicando que el contrato se encuentra en una zona poco frecuente dentro de los datos analizados. Por esta razón, el modelo lo detectó como un registro fuera del patrón general.

## 3.5 QUINTO ANOMALO

In [151]:
dfss.loc[dfss.indice==candidatos[4],:]

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q,outlier,profundidad
7520,Planeación,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,No,2,0,3,0,-0.236356,-0.232543,0.521578,0.011766,0.01768,-0.14601,-0.040653,0.116006,0.033959,0.089594,0.164528,0.536736,-0.06405,-0.068518,-0.105303,0.237339,0.021603,-0.133762,-0.081177,0.367218,0.334643,-0.309987,0.356876,0.098482,0.516013,0.136842,-3.309283,-0.183172,-1.2584,-0.260693,0.931835,0.583255,-0.748228,0.403769,-0.53831,-0.619335,-0.780406,-1.317176,0,38461,2,0,3,0,-1,1.0

Este contrato fue identificado como un caso atípico porque presenta algunas características que no son tan comunes dentro del conjunto de datos. Aunque pertenece a una contratación directa por prestación de servicios y tiene un valor relativamente bajo, el contrato fue prorrogado y cuenta con una duración de 228 días, lo que puede diferenciarlo de otros contratos similares. Además, las variables transformadas del modelo muestran valores alejados del comportamiento promedio, especialmente en las componentes SE2 y SE3, indicando que el registro se encuentra en una zona menos frecuente dentro de los datos. Por esta razón, el modelo lo clasificó como un contrato fuera del patrón general.

## 3.6 SEXTO ANOMALO

In [ ]:
dfss.loc[dfss.indice==candidatos[5],:]

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,outlier,profundidad
6683,Servicio Público,Ejecutivo,Descentralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,Si,1,90,2875,10919700,-0.346254,-0.168691,0.000497,-0.00034,0.017922,0.252364,-0.089119,-0.164326,-0.068432,0.048707,-0.014563,0.089199,0.109629,-0.08568,0.106642,-0.12025,0.073898,-0.124085,0.021832,0.147175,0.127425,-0.04532,-0.033046,-0.18353,0.042758,0.141752,0.17929,-0.0254,0.023365,-0.257105,-0.057093,0.249656,-0.108987,0.182913,-0.026352,1.547129,2.318334,-0.788547,2,423,-1,1.0

Este contrato fue identificado como un caso atípico porque presenta un comportamiento diferente frente a la mayoría de registros analizados. Aunque corresponde a una contratación directa por prestación de servicios, pertenece a una entidad descentralizada y además fue prorrogado, aun teniendo una duración relativamente corta de 90 días y un valor bajo del contrato. También se observa que las variables transformadas del modelo, especialmente en las componentes SE1 y SE2, toman valores alejados del promedio, indicando que el contrato se ubica en una zona poco común dentro de los datos. Por esta razón, el modelo lo detectó como un registro fuera del patrón general.

# 4. MINERÍA DE REGLAS DE ASOCIACIÓN

In [26]:
# Variables binarias (sí/no, verdadero/falso)
binarias = ['centralizada','grupo','pime','pago_adelantado','liquidacion','obligacion_ambiente','obligacion_postconsumo','estado_bpin','prorrogado','postconflicto']

# Variables categóricas (sin un orden específico)
cuals = ['sector','rama','tipo_contrato','modalidad_contratacion']

# Variables cuantitativas (numéricas que representan cantidades medibles)
cuants = ['dias_espera_inicio','duracion_contrato','dias_desde_primer_contrato','valor_contratoo']

In [27]:

transformer = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='quantile',subsample=None)
dfs.loc[:,cuants]=transformer.fit_transform(dfs.loc[:,cuants]) #Las cuantitativas las transformamos a cuartiles
for cuant in cuants:
     dfs.loc[:,cuant+'_q']=dfs.loc[:,cuant].apply(int).astype('str') #Para evitar un warning de pandas se crean nuevas columnas con cuantiles y dtype object

c:\Users\alcas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning:

The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.

c:\Users\alcas\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_discretization.py:396: UserWarning:

Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.

## 4.1 MINERÍA DE LA CLASE 0

### 4.1.0 SUBCONJUNTO Y PREPRACIÓN

In [177]:
df0=dfs.copy()[dfs.clase==0]
df0.head()

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q
0,Transporte,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,Si,2,2,1,1,-0.230632,-0.122036,-0.001522,-0.002303,0.134220,0.176406,-0.056739,-0.030522,-0.149470,0.164997,-0.101998,-0.269728,0.280453,0.097403,0.188180,-0.512083,0.142109,0.154056,-0.289179,0.131029,0.087097,0.158542,0.065064,0.098843,0.241269,-0.301444,-0.155364,-0.045086,0.110323,-0.290308,-0.021428,-0.183431,-0.165765,0.050169,0.516933,-0.699410,-0.640868,-1.197668,0,0,2,2,1,1
3,Educación Nacional,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,1,0,2,1,-0.338042,-0.278063,0.010924,0.013671,-0.009648,-0.363740,-0.090634,0.265894,0.020466,-0.003160,-0.173324,0.609988,-0.310310,-0.457564,-0.354598,-0.334695,-0.015035,0.882740,0.052598,-0.168797,-0.091880,0.185196,-0.353456,-0.112787,0.114576,-0.231244,0.083896,0.326041,-0.051403,0.082964,-0.121959,-0.043341,-0.058637,0.063921,0.094111,-0.332191,-0.062011,-0.105104,0,3,1,0,2,1
4,Inclusión Social y Reconciliación,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,2,3,1,2,-0.487375,-0.318814,0.011714,0.008560,0.014443,0.285101,-0.016738,-0.257863,-0.212083,0.107955,0.124422,-0.003640,-0.141943,0.141153,-0.214277,0.193188,0.021567,-0.002867,-0.011424,-0.052882,0.066520,-0.447140,0.143064,0.269374,0.558160,-0.470381,0.162990,-0.043987,-0.366043,1.742416,-0.265758,-0.090741,0.681484,0.093808,-0.622647,-0.693104,0.502032,0.551954,0,4,2,3,1,2
5,Salud y Protección Social,Corporación Autónoma,Centralizada,Prestación de servicios,Contratación régimen especial,No,No,No,No,No,No,No Válido,No,Si,0,0,0,0,1.382267,-0.516775,0.015610,0.014045,0.045300,-0.208494,-0.046099,0.097162,-0.005489,-0.062138,-0.039359,0.025348,0.298700,-0.021544,0.093522,-0.499560,0.159782,-0.089353,-0.091828,0.073691,0.004596,0.092507,0.100983,-0.101308,0.070730,0.035983,-0.050008,-0.024554,0.125461,-0.024174,0.014963,0.043829,0.054716,-0.002287,-0.070030,-0.541255,0.524765,0.174724,0,5,0,0,0,0
6,deportes,Ejecutivo,Descentralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,No,0,3,1,2,-0.504574,-0.397166,0.010994,0.009706,0.000229,-0.068255,-0.089499,-0.212740,-0.239479,0.153282,0.305977,0.096343,-0.213860,0.181756,-0.390827,0.653696,0.209369,-0.019500,-0.699967,-0.678877,-1.690219,1.256887,0.835796,-0.485599,-0.379894,0.836112,-0.060325,-0.125866,-0.101270,0.063530,-0.101731,0.148275,0.291683,-0.147344,-0.028407,-0.634507,-0.742000,-1.152330,0,6,0,3,1,2

In [178]:
df_onehot=pd.concat([pd.get_dummies(df0.loc[:,cuals+[cuant+'_q' for cuant in cuants]],drop_first=False),pd.get_dummies(df0.loc[:,binarias],drop_first=True)],axis=1)
df_onehot.head()

,sector_Ambiente y Desarrollo Sostenible,sector_Ciencia Tecnología,sector_Cultura,sector_Educación Nacional,sector_Hacienda y Crédito Público,sector_Inclusión Social y Reconciliación,sector_Industria,sector_Información Estadística,sector_Inteligencia Estratégica y Contrainteligencia,sector_Ley de Justicia,sector_Minas y Energía,sector_No aplica/No pertenece,sector_Planeación,sector_Presidencia de la República,sector_Relaciones Exteriores,sector_Salud y Protección Social,sector_Servicio Público,sector_Tecnologías de la Información y las Comunicaciones,sector_Trabajo,sector_Transporte,"sector_Vivienda, Ciudad y Territorio",sector_agricultura,sector_defensa,sector_deportes,sector_interior,rama_Corporación Autónoma,rama_Ejecutivo,rama_Judicial,rama_Legislativo,tipo_contrato_Acuerdo Marco de Precios,tipo_contrato_Arrendamiento de inmuebles,tipo_contrato_Arrendamiento de muebles,tipo_contrato_Comisión,tipo_contrato_Comodato,tipo_contrato_Compraventa,tipo_contrato_Concesión,tipo_contrato_Consultoría,tipo_contrato_Decreto 092 de 2017,tipo_contrato_Interventoría,tipo_contrato_Negocio fiduciario,tipo_contrato_No Especificado,tipo_contrato_Obra,tipo_contrato_Operaciones de Crédito Público,tipo_contrato_Otro,tipo_contrato_Prestación de servicios,tipo_contrato_Seguros,tipo_contrato_Servicios financieros,tipo_contrato_Suministros,tipo_contrato_Venta muebles,modalidad_contratacion_Concurso de méritos abierto,modalidad_contratacion_Contratación Directa (con ofertas),modalidad_contratacion_Contratación directa,modalidad_contratacion_Contratación régimen especial,modalidad_contratacion_Contratación régimen especial (con ofertas),modalidad_contratacion_Enajenación de bienes con subasta,modalidad_contratacion_Licitación Pública Acuerdo Marco de Precios,modalidad_contratacion_Licitación pública,modalidad_contratacion_Licitación pública Obra Publica,modalidad_contratacion_Mínima cuantía,modalidad_contratacion_Seleccion Abreviada Menor Cuantia Sin Manifestacion Interes,modalidad_contratacion_Selección Abreviada de Menor Cuantía,modalidad_contratacion_Selección abreviada subasta inversa,dias_espera_inicio_q_0,dias_espera_inicio_q_1,dias_espera_inicio_q_2,duracion_contrato_q_0,duracion_contrato_q_1,duracion_contrato_q_2,duracion_contrato_q_3,dias_desde_primer_contrato_q_0,dias_desde_primer_contrato_q_1,dias_desde_primer_contrato_q_2,dias_desde_primer_contrato_q_3,valor_contratoo_q_0,valor_contratoo_q_1,valor_contratoo_q_2,valor_contratoo_q_3,centralizada_Descentralizada,grupo_Si,pime_Si,pago_adelantado_Si,liquidacion_Si,obligacion_ambiente_Si,obligacion_postconsumo_Si,estado_bpin_Válido,prorrogado_Si,postconflicto_Si
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False

In [179]:
df_onehot.sum(axis=0)/df_onehot.shape[0]

sector_Ambiente y Desarrollo Sostenible                                               0.040232
sector_Ciencia Tecnología                                                             0.002560
sector_Cultura                                                                        0.027237
sector_Educación Nacional                                                             0.053720
sector_Hacienda y Crédito Público                                                     0.009910
sector_Inclusión Social y Reconciliación                                              0.024678
sector_Industria                                                                      0.011486
sector_Información Estadística                                                        0.030059
sector_Inteligencia Estratégica y Contrainteligencia                                  0.000033
sector_Ley de Justicia                                                                0.015063
sector_Minas y Energía                                                                0.006235
sector_No aplica/No pertenece                                                         0.160536
sector_Planeación                                                                     0.011945
sector_Presidencia de la República                                                    0.004430
sector_Relaciones Exteriores                                                          0.000886
sector_Salud y Protección Social                                                      0.150658
sector_Servicio Público                                                               0.258196
sector_Tecnologías de la Información y las Comunicaciones                             0.006563
sector_Trabajo                                                                        0.044728
sector_Transporte                                                                     0.026647
sector_Vivienda, Ciudad y Territorio                                                  0.015423
sector_agricultura                                                                    0.026121
sector_defensa                                                                        0.028320
sector_deportes                                                                       0.039707
sector_interior                                                                       0.004627
rama_Corporación Autónoma                                                             0.170512
rama_Ejecutivo                                                                        0.814459
rama_Judicial                                                                         0.007088
rama_Legislativo                                                                      0.007941
tipo_contrato_Acuerdo Marco de Precios                                                0.000066
tipo_contrato_Arrendamiento de inmuebles                                              0.007909
tipo_contrato_Arrendamiento de muebles                                                0.000492
tipo_contrato_Comisión                                                                0.000066
tipo_contrato_Comodato                                                                0.001641
tipo_contrato_Compraventa                                                             0.016342
tipo_contrato_Concesión                                                               0.000033
tipo_contrato_Consultoría                                                             0.001903
tipo_contrato_Decreto 092 de 2017                                                     0.039412
tipo_contrato_Interventoría                                                           0.001542
tipo_contrato_Negocio fiduciario                                                      0.000033
tipo_contrato_No Especificado                                                         0.000066
tipo_contrato_Obra                                                                    0.006662
tipo_contrato_Operaciones de Crédito Público                                          0.000131
tipo_contrato_Otro                                                                    0.040692
tipo_contrato_Prestación de servicios                                                 0.854494
tipo_contrato_Seguros                                                                 0.002560
tipo_contrato_Servicios financieros                                                   0.000295
tipo_contrato_Suministros                                                             0.025596
tipo_contrato_Venta muebles                                                           0.000066
modalidad_contratacion_Concurso de méritos abierto                                    0.001706
modalidad_contratacion_Contratación Directa (con ofertas)                             0.010862
modalidad_contratacion_Contratación directa                                           0.755357
modalidad_contratacion_Contratación régimen especial                                  0.150527
modalidad_contratacion_Contratación régimen especial (con ofertas)                    0.008532
modalidad_contratacion_Enajenación de bienes con subasta                              0.000066
modalidad_contratacion_Licitación Pública Acuerdo Marco de Precios                    0.000066
modalidad_contratacion_Licitación pública                                             0.002494
modalidad_contratacion_Licitación pública Obra Publica                                0.000689
modalidad_contratacion_Mínima cuantía                                                 0.050274
modalidad_contratacion_Seleccion Abreviada Menor Cuantia Sin Manifestacion Interes    0.000164
modalidad_contratacion_Selección Abreviada de Menor Cuantía                           0.009385
modalidad_contratacion_Selección abreviada subasta inversa                            0.009878
dias_espera_inicio_q_0                                                                0.333935
dias_espera_inicio_q_1                                                                0.387392
dias_espera_inicio_q_2                                                                0.278673
duracion_contrato_q_0                                                                 0.246152
duracion_contrato_q_1                                                                 0.243494
duracion_contrato_q_2                                                                 0.260657
duracion_contrato_q_3                                                                 0.249696
dias_desde_primer_contrato_q_0                                                        0.243461
dias_desde_primer_contrato_q_1                                                        0.255931
dias_desde_primer_contrato_q_2                                                        0.245988
dias_desde_primer_contrato_q_3                                                        0.254619
valor_contratoo_q_0                                                                   0.250878
valor_contratoo_q_1                                                                   0.252978
valor_contratoo_q_2                                                                   0.248384
valor_contratoo_q_3                                                                   0.247760
centralizada_Descentralizada                                                          0.166607
grupo_Si                                                                              0.004988
pime_Si                                                                               0.138385
pago_adelantado_Si                                                                    0.000886
liquidacion_Si                                                                        0.128540
obligacion_ambiente_Si                                                                0.025859
obligacion_postconsumo_Si                                                             0.000131
estado_bpin_Válido                                                                    0.526400
prorrogado_Si                                                                         0.151019
postconflicto_Si                                                                      0.004397
dtype: float64

In [180]:
cumplen=(df_onehot.sum(axis=0)/df_onehot.shape[0]>0.1) & (df_onehot.sum(axis=0)/df_onehot.shape[0]<0.9)
df_onehot=df_onehot.loc[:,cumplen]
df_onehot.head()

,sector_No aplica/No pertenece,sector_Salud y Protección Social,sector_Servicio Público,rama_Corporación Autónoma,rama_Ejecutivo,tipo_contrato_Prestación de servicios,modalidad_contratacion_Contratación directa,modalidad_contratacion_Contratación régimen especial,dias_espera_inicio_q_0,dias_espera_inicio_q_1,dias_espera_inicio_q_2,duracion_contrato_q_0,duracion_contrato_q_1,duracion_contrato_q_2,duracion_contrato_q_3,dias_desde_primer_contrato_q_0,dias_desde_primer_contrato_q_1,dias_desde_primer_contrato_q_2,dias_desde_primer_contrato_q_3,valor_contratoo_q_0,valor_contratoo_q_1,valor_contratoo_q_2,valor_contratoo_q_3,centralizada_Descentralizada,pime_Si,liquidacion_Si,estado_bpin_Válido,prorrogado_Si
0,False,False,False,False,True,True,True,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,True,True
3,False,False,False,False,True,True,True,False,False,True,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False
4,False,False,False,False,True,True,True,False,False,False,True,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,False
5,False,True,False,True,False,True,False,True,True,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True
6,False,False,False,False,True,True,True,False,True,False,False,False,False,False,True,False,True,False,False,False,False,True,False,True,False,False,False,False

### 4.1.1 MINERÍA DE ITEMSETS FRECUENTES

In [181]:
freqitems = apriori(df_onehot, min_support=0.08, use_colnames=True)
freqitems.sort_values('support',ascending=True)

      support                                           itemsets
160  0.080432  frozenset({centralizada_Descentralizada, estad...
41   0.080465  frozenset({sector_Servicio Público, duracion_c...
361  0.080530  frozenset({dias_espera_inicio_q_1, tipo_contra...
166  0.080662  frozenset({modalidad_contratacion_Contratación...
87   0.080760  frozenset({tipo_contrato_Prestación de servici...
435  0.081023  frozenset({tipo_contrato_Prestación de servici...
118  0.081187  frozenset({dias_espera_inicio_q_1, duracion_co...
152  0.081252  frozenset({valor_contratoo_q_1, dias_desde_pri...
165  0.081285  frozenset({tipo_contrato_Prestación de servici...
126  0.081318  frozenset({dias_espera_inicio_q_1, valor_contr...
132  0.081318  frozenset({dias_espera_inicio_q_2, dias_desde_...
370  0.081646  frozenset({tipo_contrato_Prestación de servici...
389  0.081777  frozenset({rama_Ejecutivo, modalidad_contratac...
271  0.081810  frozenset({dias_espera_inicio_q_1, tipo_contra...
264  0.081909  frozenset({tipo_contrato_Prestación de servici...
362  0.082171  frozenset({dias_espera_inicio_q_1, tipo_contra...
356  0.082171  frozenset({tipo_contrato_Prestación de servici...
42   0.082204  frozenset({sector_Servicio Público, valor_cont...
114  0.082237  frozenset({dias_espera_inicio_q_0, dias_desde_...
110  0.082335  frozenset({duracion_contrato_q_1, dias_espera_...
35   0.082401  frozenset({dias_espera_inicio_q_0, sector_Salu...
329  0.082565  frozenset({valor_contratoo_q_3, duracion_contr...
111  0.082565  frozenset({dias_espera_inicio_q_0, duracion_co...
358  0.082762  frozenset({dias_espera_inicio_q_1, tipo_contra...
219  0.082827  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
391  0.082959  frozenset({rama_Ejecutivo, modalidad_contratac...
274  0.083057  frozenset({dias_espera_inicio_q_1, tipo_contra...
409  0.083156  frozenset({dias_espera_inicio_q_1, tipo_contra...
444  0.083320  frozenset({tipo_contrato_Prestación de servici...
442  0.083320  frozenset({tipo_contrato_Prestación de servici...
235  0.083713  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
393  0.083812  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
439  0.084042  frozenset({dias_espera_inicio_q_1, tipo_contra...
131  0.084042  frozenset({dias_desde_primer_contrato_q_1, dia...
368  0.084074  frozenset({tipo_contrato_Prestación de servici...
359  0.084140  frozenset({dias_espera_inicio_q_1, tipo_contra...
407  0.084337  frozenset({dias_espera_inicio_q_1, tipo_contra...
386  0.084567  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
436  0.084764  frozenset({dias_espera_inicio_q_1, tipo_contra...
300  0.084928  frozenset({dias_espera_inicio_q_1, duracion_co...
390  0.084928  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
270  0.084928  frozenset({dias_desde_primer_contrato_q_1, tip...
330  0.084960  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
379  0.084993  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
367  0.085190  frozenset({tipo_contrato_Prestación de servici...
213  0.085518  frozenset({rama_Ejecutivo, prorrogado_Si, moda...
113  0.085584  frozenset({dias_espera_inicio_q_0, dias_desde_...
417  0.085682  frozenset({tipo_contrato_Prestación de servici...
456  0.086142  frozenset({tipo_contrato_Prestación de servici...
227  0.086142  frozenset({duracion_contrato_q_1, rama_Ejecuti...
220  0.086142  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
302  0.086175  frozenset({dias_espera_inicio_q_1, modalidad_c...
39   0.086207  frozenset({sector_Servicio Público, dias_esper...
283  0.086634  frozenset({tipo_contrato_Prestación de servici...
335  0.086634  frozenset({dias_espera_inicio_q_1, sector_Serv...
412  0.086667  frozenset({dias_espera_inicio_q_1, tipo_contra...
163  0.086798  frozenset({rama_Ejecutivo, sector_No aplica/No...
371  0.087061  frozenset({valor_contratoo_q_2, tipo_contrato_...
305  0.087422  frozenset({dias_espera_inicio_q_1, modalidad_c...
214  0.087586  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
216  0.087914  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
429  0.087914  frozenset({tipo_contrato_Prestación de servici...
138  0.088078  frozenset({duracion_contrato_q_1, dias_desde_p...
112  0.088144  frozenset({dias_espera_inicio_q_0, dias_desde_...
333  0.088308  frozenset({dias_espera_inicio_q_1, sector_Serv...
289  0.088537  frozenset({tipo_contrato_Prestación de servici...
133  0.088866  frozenset({dias_espera_inicio_q_2, valor_contr...
328  0.089062  frozenset({valor_contratoo_q_0, duracion_contr...
142  0.089194  frozenset({valor_contratoo_q_1, duracion_contr...
221  0.089423  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
411  0.089522  frozenset({dias_espera_inicio_q_1, tipo_contra...
310  0.089653  frozenset({modalidad_contratacion_Contratación...
230  0.089719  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
420  0.089916  frozenset({tipo_contrato_Prestación de servici...
446  0.090014  frozenset({tipo_contrato_Prestación de servici...
304  0.090080  frozenset({dias_espera_inicio_q_1, valor_contr...
124  0.090145  frozenset({dias_espera_inicio_q_1, dias_desde_...
266  0.090244  frozenset({dias_espera_inicio_q_1, tipo_contra...
229  0.090375  frozenset({rama_Ejecutivo, dias_desde_primer_c...
337  0.090408  frozenset({dias_espera_inicio_q_1, sector_Serv...
408  0.090474  frozenset({dias_espera_inicio_q_1, tipo_contra...
116  0.090474  frozenset({valor_contratoo_q_1, dias_espera_in...
108  0.091031  frozenset({dias_espera_inicio_q_0, modalidad_c...
125  0.091064  frozenset({dias_espera_inicio_q_1, dias_desde_...
434  0.091130  frozenset({tipo_contrato_Prestación de servici...
48   0.091163  frozenset({rama_Ejecutivo, modalidad_contratac...
322  0.091163  frozenset({valor_contratoo_q_0, modalidad_cont...
301  0.091392  frozenset({dias_espera_inicio_q_1, modalidad_c...
395  0.091491  frozenset({rama_Ejecutivo, modalidad_contratac...
146  0.091721  frozenset({dias_desde_primer_contrato_q_1, dur...
217  0.091819  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
31   0.091950  frozenset({sector_No aplica/No pertenece, esta...
447  0.091950  frozenset({tipo_contrato_Prestación de servici...
313  0.091983  frozenset({modalidad_contratacion_Contratación...
415  0.092082  frozenset({tipo_contrato_Prestación de servici...
279  0.092147  frozenset({tipo_contrato_Prestación de servici...
174  0.092344  frozenset({dias_espera_inicio_q_1, sector_Serv...
452  0.093000  frozenset({tipo_contrato_Prestación de servici...
262  0.093033  frozenset({tipo_contrato_Prestación de servici...
239  0.093132  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
360  0.093460  frozenset({dias_espera_inicio_q_1, tipo_contra...
418  0.093591  frozenset({duracion_contrato_q_1, valor_contra...
384  0.093689  frozenset({tipo_contrato_Prestación de servici...
311  0.093821  frozenset({duracion_contrato_q_1, modalidad_co...
123  0.093919  frozenset({dias_desde_primer_contrato_q_1, dia...
410  0.094083  frozenset({dias_espera_inicio_q_1, tipo_contra...
172  0.094116  frozenset({dias_espera_inicio_q_1, sector_Serv...
405  0.094772  frozenset({rama_Ejecutivo, modalidad_contratac...
303  0.094805  frozenset({dias_espera_inicio_q_1, modalidad_c...
365  0.095166  frozenset({tipo_contrato_Prestación de servici...
119  0.095330  frozenset({dias_espera_inicio_q_1, duracion_co...
169  0.095429  frozenset({dias_espera_inicio_q_1, sector_Serv...
70   0.095790  frozenset({tipo_contrato_Prestación de servici...
149  0.095954  frozenset({valor_contratoo_q_3, dias_desde_pri...
272  0.095954  frozenset({dias_espera_inicio_q_1, tipo_contra...
263  0.096216  frozenset({tipo_contrato_Prestación de servici...
308  0.096216  frozenset({modalidad_contratacion_Contratación...
273  0.096216  frozenset({dias_espera_inicio_q_1, tipo_contra...
218  0.097070  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
107  0.097234  frozenset({prorrogado_Si, modalidad_contrataci...
268  0.097299  frozenset({dias_espera_inicio_q_1, tipo_contra...
396  0.097332  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
421  0.097496  frozenset({valor_contratoo_q_2, tipo_contrato_...
267  0.097660  frozenset({dias_espera_inicio_q_1, tipo_contra...
176  0.098120  frozenset({tipo_contrato_Prestación de servici...
314  0.098185  frozenset({valor_contratoo_q_2, modalidad_cont...
380  0.098481  frozenset({tipo_contrato_Prestación de servici...
401  0.098940  frozenset({modalidad_contratacion_Contratación...
423  0.098973  frozenset({tipo_contrato_Prestación de servici...
127  0.099268  frozenset({dias_espera_inicio_q_1, valor_contr...
453  0.099564  frozenset({tipo_contrato_Prestación de servici...
282  0.099629  frozenset({tipo_contrato_Prestación de servici...
402  0.100154  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
298  0.100220  frozenset({tipo_contrato_Prestación de servici...
327  0.100515  frozenset({modalidad_contratacion_Contratación...
416  0.100646  frozenset({tipo_contrato_Prestación de servici...
316  0.100811  frozenset({modalidad_contratacion_Contratación...
381  0.101007  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
354  0.101073  frozenset({tipo_contrato_Prestación de servici...
280  0.101204  frozenset({duracion_contrato_q_1, valor_contra...
128  0.101336  frozenset({dias_espera_inicio_q_1, valor_contr...
451  0.101368  frozenset({tipo_contrato_Prestación de servici...
430  0.101697  frozenset({tipo_contrato_Prestación de servici...
40   0.101762  frozenset({dias_espera_inicio_q_1, sector_Serv...
45   0.102058  frozenset({rama_Corporación Autónoma, modalida...
366  0.102320  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
309  0.102484  frozenset({valor_contratoo_q_0, duracion_contr...
373  0.102812  frozenset({tipo_contrato_Prestación de servici...
211  0.103436  frozenset({centralizada_Descentralizada, rama_...
284  0.103469  frozenset({valor_contratoo_q_2, tipo_contrato_...
241  0.103501  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
120  0.103830  frozenset({dias_espera_inicio_q_1, duracion_co...
293  0.103961  frozenset({tipo_contrato_Prestación de servici...
400  0.103994  frozenset({rama_Ejecutivo, modalidad_contratac...
32   0.104355  frozenset({rama_Ejecutivo, sector_Salud y Prot...
374  0.104519  frozenset({tipo_contrato_Prestación de servici...
139  0.104748  frozenset({duracion_contrato_q_1, valor_contra...
66   0.104814        frozenset({rama_Ejecutivo, liquidacion_Si})
378  0.104880  frozenset({tipo_contrato_Prestación de servici...
129  0.105470  frozenset({dias_espera_inicio_q_1, valor_contr...
438  0.105569  frozenset({tipo_contrato_Prestación de servici...
109  0.105700  frozenset({dias_espera_inicio_q_0, duracion_co...
226  0.106127  frozenset({rama_Ejecutivo, duracion_contrato_q...
424  0.106258  frozenset({tipo_contrato_Prestación de servici...
195  0.106586  frozenset({tipo_contrato_Prestación de servici...
121  0.107046  frozenset({dias_espera_inicio_q_1, duracion_co...
143  0.107177  frozenset({valor_contratoo_q_2, duracion_contr...
294  0.107603  frozenset({tipo_contrato_Prestación de servici...
269  0.107866  frozenset({dias_espera_inicio_q_1, tipo_contra...
357  0.108161  frozenset({tipo_contrato_Prestación de servici...
323  0.108227  frozenset({modalidad_contratacion_Contratación...
232  0.108325  frozenset({rama_Ejecutivo, duracion_contrato_q...
385  0.108325  frozenset({rama_Ejecutivo, modalidad_contratac...
33   0.109704  frozenset({tipo_contrato_Prestación de servici...
448  0.110458  frozenset({tipo_contrato_Prestación de servici...
34   0.110688  frozenset({modalidad_contratacion_Contratación...
431  0.110754  frozenset({tipo_contrato_Prestación de servici...
65   0.111377               frozenset({rama_Ejecutivo, pime_Si})
324  0.111377  frozenset({valor_contratoo_q_0, modalidad_cont...
141  0.111377  frozenset({dias_desde_primer_contrato_q_2, dur...
428  0.111935  frozenset({tipo_contrato_Prestación de servici...
443  0.112034  frozenset({tipo_contrato_Prestación de servici...
406  0.112230  frozenset({tipo_contrato_Prestación de servici...
122  0.112263  frozenset({dias_espera_inicio_q_1, dias_desde_...
295  0.112427  frozenset({tipo_contrato_Prestación de servici...
449  0.112690  frozenset({tipo_contrato_Prestación de servici...
331  0.112887  frozenset({tipo_contrato_Prestación de servici...
392  0.113346  frozenset({modalidad_contratacion_Contratación...
317  0.113379  frozenset({valor_contratoo_q_3, modalidad_cont...
398  0.113478  frozenset({rama_Ejecutivo, modalidad_contratac...
375  0.113510  frozenset({tipo_contrato_Prestación de servici...
369  0.113773  frozenset({tipo_contrato_Prestación de servici...
376  0.114035  frozenset({tipo_contrato_Prestación de servici...
455  0.114626  frozenset({tipo_contrato_Prestación de servici...
397  0.114725  frozenset({rama_Ejecutivo, modalidad_contratac...
321  0.114757  frozenset({modalidad_contratacion_Contratación...
225  0.114889  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
137  0.114921  frozenset({duracion_contrato_q_0, estado_bpin_...
450  0.115118  frozenset({tipo_contrato_Prestación de servici...
425  0.115118  frozenset({tipo_contrato_Prestación de servici...
156  0.115118  frozenset({valor_contratoo_q_0, estado_bpin_Vá...
265  0.115250  frozenset({tipo_contrato_Prestación de servici...
299  0.115282  frozenset({modalidad_contratacion_Contratación...
154  0.115676  frozenset({valor_contratoo_q_0, dias_desde_pri...
292  0.115906  frozenset({tipo_contrato_Prestación de servici...
404  0.116037  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
277  0.116300  frozenset({tipo_contrato_Prestación de servici...
260  0.116464  frozenset({tipo_contrato_Prestación de servici...
162  0.116693  frozenset({rama_Ejecutivo, sector_No aplica/No...
342  0.116825  frozenset({tipo_contrato_Prestación de servici...
238  0.116956  frozenset({rama_Ejecutivo, dias_desde_primer_c...
286  0.117153  frozenset({tipo_contrato_Prestación de servici...
399  0.117219  frozenset({dias_desde_primer_contrato_q_1, ram...
383  0.117415  frozenset({valor_contratoo_q_2, tipo_contrato_...
236  0.117809  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
377  0.118269  frozenset({dias_desde_primer_contrato_q_1, tip...
115  0.118400  frozenset({valor_contratoo_q_0, dias_espera_in...
161  0.118433  frozenset({tipo_contrato_Prestación de servici...
426  0.118466  frozenset({tipo_contrato_Prestación de servici...
288  0.119187  frozenset({tipo_contrato_Prestación de servici...
319  0.119253  frozenset({modalidad_contratacion_Contratación...
105  0.119352  frozenset({centralizada_Descentralizada, modal...
318  0.119778  frozenset({modalidad_contratacion_Contratación...
290  0.120270  frozenset({tipo_contrato_Prestación de servici...
228  0.120402  frozenset({rama_Ejecutivo, duracion_contrato_q...
445  0.120434  frozenset({tipo_contrato_Prestación de servici...
215  0.120927  frozenset({rama_Ejecutivo, dias_espera_inicio_...
224  0.121353  frozenset({rama_Ejecutivo, duracion_contrato_q...
433  0.121517  frozenset({valor_contratoo_q_2, tipo_contrato_...
353  0.121616  frozenset({tipo_contrato_Prestación de servici...
454  0.121846  frozenset({tipo_contrato_Prestación de servici...
68   0.122141         frozenset({rama_Ejecutivo, prorrogado_Si})
240  0.122239  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
199  0.122469  frozenset({rama_Ejecutivo, duracion_contrato_q...
394  0.122600  frozenset({modalidad_contratacion_Contratación...
403  0.122666  frozenset({modalidad_contratacion_Contratación...
427  0.122732  frozenset({dias_desde_primer_contrato_q_1, tip...
326  0.123027  frozenset({valor_contratoo_q_2, modalidad_cont...
372  0.123191  frozenset({tipo_contrato_Prestación de servici...
382  0.123552  frozenset({tipo_contrato_Prestación de servici...
233  0.123650  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
419  0.123913  frozenset({tipo_contrato_Prestación de servici...
287  0.124011  frozenset({tipo_contrato_Prestación de servici...
150  0.124077  frozenset({estado_bpin_Válido, dias_desde_prim...
145  0.124077  frozenset({duracion_contrato_q_3, dias_desde_p...
297  0.124569  frozenset({valor_contratoo_q_2, tipo_contrato_...
320  0.124930  frozenset({dias_desde_primer_contrato_q_1, mod...
312  0.125324  frozenset({modalidad_contratacion_Contratación...
243  0.125685  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
281  0.125980  frozenset({tipo_contrato_Prestación de servici...
234  0.126309  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
242  0.126538  frozenset({rama_Ejecutivo, valor_contratoo_q_1...
441  0.126571  frozenset({tipo_contrato_Prestación de servici...
291  0.126834  frozenset({dias_desde_primer_contrato_q_1, tip...
25   0.128540                        frozenset({liquidacion_Si})
117  0.128868  frozenset({dias_espera_inicio_q_0, estado_bpin...
193  0.128934  frozenset({tipo_contrato_Prestación de servici...
278  0.129131  frozenset({tipo_contrato_Prestación de servici...
153  0.129295  frozenset({dias_desde_primer_contrato_q_2, est...
237  0.130017  frozenset({dias_desde_primer_contrato_q_1, ram...
422  0.130115  frozenset({tipo_contrato_Prestación de servici...
164  0.130575  frozenset({tipo_contrato_Prestación de servici...
244  0.131297  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
89   0.131329  frozenset({tipo_contrato_Prestación de servici...
432  0.131428  frozenset({tipo_contrato_Prestación de servici...
325  0.132248  frozenset({modalidad_contratacion_Contratación...
315  0.132412  frozenset({modalidad_contratacion_Contratación...
364  0.132478  frozenset({tipo_contrato_Prestación de servici...
388  0.132773  frozenset({modalidad_contratacion_Contratación...
210  0.132872  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
148  0.133036  frozenset({estado_bpin_Válido, duracion_contra...
140  0.133266  frozenset({duracion_contrato_q_1, estado_bpin_...
285  0.133298  frozenset({tipo_contrato_Prestación de servici...
158  0.133331  frozenset({valor_contratoo_q_2, estado_bpin_Vá...
296  0.133397  frozenset({tipo_contrato_Prestación de servici...
155  0.133823  frozenset({estado_bpin_Válido, dias_desde_prim...
231  0.134184  frozenset({rama_Ejecutivo, duracion_contrato_q...
28   0.134578  frozenset({rama_Ejecutivo, sector_No aplica/No...
437  0.135267  frozenset({tipo_contrato_Prestación de servici...
30   0.135924  frozenset({sector_No aplica/No pertenece, moda...
414  0.136252  frozenset({tipo_contrato_Prestación de servici...
157  0.136777  frozenset({valor_contratoo_q_1, estado_bpin_Vá...
349  0.137466  frozenset({tipo_contrato_Prestación de servici...
24   0.138385                               frozenset({pime_Si})
151  0.139205  frozenset({dias_desde_primer_contrato_q_1, est...
44   0.139238  frozenset({tipo_contrato_Prestación de servici...
29   0.139862  frozenset({tipo_contrato_Prestación de servici...
336  0.139894  frozenset({sector_Servicio Público, rama_Ejecu...
334  0.140977  frozenset({sector_Servicio Público, rama_Ejecu...
159  0.141174  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
338  0.141273  frozenset({sector_Servicio Público, modalidad_...
248  0.141338  frozenset({tipo_contrato_Prestación de servici...
259  0.141437  frozenset({tipo_contrato_Prestación de servici...
307  0.142815  frozenset({modalidad_contratacion_Contratación...
276  0.143274  frozenset({tipo_contrato_Prestación de servici...
64   0.144128  frozenset({rama_Ejecutivo, centralizada_Descen...
144  0.145178  frozenset({duracion_contrato_q_2, estado_bpin_...
192  0.145736  frozenset({tipo_contrato_Prestación de servici...
175  0.146031  frozenset({sector_Servicio Público, modalidad_...
350  0.146687  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
206  0.147114  frozenset({rama_Ejecutivo, modalidad_contratac...
173  0.147147  frozenset({sector_Servicio Público, tipo_contr...
93   0.147639  frozenset({duracion_contrato_q_0, modalidad_co...
181  0.147705  frozenset({tipo_contrato_Prestación de servici...
147  0.147901  frozenset({valor_contratoo_q_3, duracion_contr...
86   0.147967  frozenset({tipo_contrato_Prestación de servici...

In [182]:
freqitems =fpgrowth(df_onehot, min_support=0.08, use_colnames=True)
freqitems.sort_values('support',ascending=True).head(300)

      support                                           itemsets
340  0.080432  frozenset({centralizada_Descentralizada, estad...
435  0.080465  frozenset({sector_Servicio Público, duracion_c...
118  0.080530  frozenset({dias_espera_inicio_q_1, tipo_contra...
355  0.080662  frozenset({modalidad_contratacion_Contratación...
456  0.080760  frozenset({tipo_contrato_Prestación de servici...
171  0.081023  frozenset({tipo_contrato_Prestación de servici...
146  0.081187  frozenset({dias_espera_inicio_q_1, duracion_co...
180  0.081252  frozenset({valor_contratoo_q_1, dias_desde_pri...
354  0.081285  frozenset({tipo_contrato_Prestación de servici...
271  0.081318  frozenset({dias_espera_inicio_q_1, valor_contr...
391  0.081318  frozenset({dias_espera_inicio_q_2, dias_desde_...
199  0.081646  frozenset({tipo_contrato_Prestación de servici...
160  0.081777  frozenset({rama_Ejecutivo, modalidad_contratac...
194  0.081810  frozenset({dias_espera_inicio_q_1, tipo_contra...
119  0.081909  frozenset({tipo_contrato_Prestación de servici...
126  0.082171  frozenset({tipo_contrato_Prestación de servici...
243  0.082171  frozenset({dias_espera_inicio_q_1, tipo_contra...
101  0.082204  frozenset({sector_Servicio Público, valor_cont...
390  0.082237  frozenset({dias_espera_inicio_q_0, dias_desde_...
408  0.082335  frozenset({duracion_contrato_q_1, dias_espera_...
331  0.082401  frozenset({dias_espera_inicio_q_0, sector_Salu...
58   0.082565  frozenset({dias_espera_inicio_q_0, duracion_co...
319  0.082565  frozenset({valor_contratoo_q_3, duracion_contr...
75   0.082762  frozenset({dias_espera_inicio_q_1, tipo_contra...
116  0.082827  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
166  0.082959  frozenset({rama_Ejecutivo, modalidad_contratac...
384  0.083057  frozenset({dias_espera_inicio_q_1, tipo_contra...
221  0.083156  frozenset({dias_espera_inicio_q_1, tipo_contra...
158  0.083320  frozenset({tipo_contrato_Prestación de servici...
250  0.083320  frozenset({tipo_contrato_Prestación de servici...
318  0.083713  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
249  0.083812  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
326  0.084042  frozenset({dias_espera_inicio_q_1, tipo_contra...
80   0.084042  frozenset({dias_desde_primer_contrato_q_1, dia...
429  0.084074  frozenset({tipo_contrato_Prestación de servici...
220  0.084140  frozenset({dias_espera_inicio_q_1, tipo_contra...
424  0.084337  frozenset({dias_espera_inicio_q_1, tipo_contra...
325  0.084567  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
454  0.084764  frozenset({dias_espera_inicio_q_1, tipo_contra...
157  0.084928  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
93   0.084928  frozenset({dias_desde_primer_contrato_q_1, tip...
423  0.084928  frozenset({dias_espera_inicio_q_1, duracion_co...
378  0.084960  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
289  0.084993  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
164  0.085190  frozenset({tipo_contrato_Prestación de servici...
125  0.085518  frozenset({rama_Ejecutivo, prorrogado_Si, moda...
181  0.085584  frozenset({dias_espera_inicio_q_0, dias_desde_...
165  0.085682  frozenset({tipo_contrato_Prestación de servici...
382  0.086142  frozenset({tipo_contrato_Prestación de servici...
427  0.086142  frozenset({rama_Ejecutivo, duracion_contrato_q...
241  0.086142  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
219  0.086175  frozenset({dias_espera_inicio_q_1, modalidad_c...
433  0.086207  frozenset({sector_Servicio Público, dias_esper...
453  0.086634  frozenset({dias_espera_inicio_q_1, sector_Serv...
113  0.086634  frozenset({tipo_contrato_Prestación de servici...
242  0.086667  frozenset({dias_espera_inicio_q_1, tipo_contra...
353  0.086798  frozenset({rama_Ejecutivo, sector_No aplica/No...
248  0.087061  frozenset({valor_contratoo_q_2, tipo_contrato_...
240  0.087422  frozenset({dias_espera_inicio_q_1, modalidad_c...
274  0.087586  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
73   0.087914  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
290  0.087914  frozenset({tipo_contrato_Prestación de servici...
410  0.088078  frozenset({duracion_contrato_q_1, dias_desde_p...
292  0.088144  frozenset({dias_espera_inicio_q_0, dias_desde_...
451  0.088308  frozenset({dias_espera_inicio_q_1, sector_Serv...
317  0.088537  frozenset({tipo_contrato_Prestación de servici...
362  0.088866  frozenset({dias_espera_inicio_q_2, valor_contr...
169  0.089062  frozenset({valor_contratoo_q_0, duracion_contr...
98   0.089194  frozenset({valor_contratoo_q_1, duracion_contr...
383  0.089423  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
117  0.089522  frozenset({dias_espera_inicio_q_1, tipo_contra...
163  0.089653  frozenset({modalidad_contratacion_Contratación...
246  0.089719  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
198  0.089916  frozenset({tipo_contrato_Prestación de servici...
309  0.090014  frozenset({tipo_contrato_Prestación de servici...
115  0.090080  frozenset({dias_espera_inicio_q_1, valor_contr...
179  0.090145  frozenset({dias_espera_inicio_q_1, dias_desde_...
422  0.090244  frozenset({dias_espera_inicio_q_1, tipo_contra...
197  0.090375  frozenset({rama_Ejecutivo, dias_desde_primer_c...
452  0.090408  frozenset({dias_espera_inicio_q_1, sector_Serv...
74   0.090474  frozenset({dias_espera_inicio_q_1, tipo_contra...
100  0.090474  frozenset({valor_contratoo_q_1, dias_espera_in...
335  0.091031  frozenset({dias_espera_inicio_q_0, modalidad_c...
389  0.091064  frozenset({dias_espera_inicio_q_1, dias_desde_...
381  0.091130  frozenset({tipo_contrato_Prestación de servici...
336  0.091163  frozenset({rama_Ejecutivo, modalidad_contratac...
288  0.091163  frozenset({valor_contratoo_q_0, modalidad_cont...
72   0.091392  frozenset({dias_espera_inicio_q_1, modalidad_c...
308  0.091491  frozenset({rama_Ejecutivo, modalidad_contratac...
204  0.091721  frozenset({dias_desde_primer_contrato_q_1, dur...
218  0.091819  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
348  0.091950  frozenset({sector_No aplica/No pertenece, esta...
374  0.091950  frozenset({tipo_contrato_Prestación de servici...
196  0.091983  frozenset({modalidad_contratacion_Contratación...
159  0.092082  frozenset({tipo_contrato_Prestación de servici...
162  0.092147  frozenset({tipo_contrato_Prestación de servici...
449  0.092344  frozenset({dias_espera_inicio_q_1, sector_Serv...
402  0.093000  frozenset({tipo_contrato_Prestación de servici...
124  0.093033  frozenset({tipo_contrato_Prestación de servici...
287  0.093132  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
323  0.093460  frozenset({dias_espera_inicio_q_1, tipo_contra...
428  0.093591  frozenset({tipo_contrato_Prestación de servici...
380  0.093689  frozenset({tipo_contrato_Prestación de servici...
426  0.093821  frozenset({duracion_contrato_q_1, modalidad_co...
81   0.093919  frozenset({dias_desde_primer_contrato_q_1, dia...
324  0.094083  frozenset({dias_espera_inicio_q_1, tipo_contra...
448  0.094116  frozenset({dias_espera_inicio_q_1, sector_Serv...
379  0.094772  frozenset({rama_Ejecutivo, modalidad_contratac...
322  0.094805  frozenset({dias_espera_inicio_q_1, modalidad_c...
174  0.095166  frozenset({tipo_contrato_Prestación de servici...
407  0.095330  frozenset({dias_espera_inicio_q_1, duracion_co...
450  0.095429  frozenset({dias_espera_inicio_q_1, sector_Serv...
334  0.095790  frozenset({tipo_contrato_Prestación de servici...
114  0.095954  frozenset({dias_espera_inicio_q_1, tipo_contra...
297  0.095954  frozenset({valor_contratoo_q_3, dias_desde_pri...
239  0.096216  frozenset({dias_espera_inicio_q_1, tipo_contra...
154  0.096216  frozenset({modalidad_contratacion_Contratación...
273  0.096216  frozenset({tipo_contrato_Prestación de servici...
321  0.097070  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
122  0.097234  frozenset({prorrogado_Si, modalidad_contrataci...
217  0.097299  frozenset({dias_espera_inicio_q_1, tipo_contra...
373  0.097332  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
247  0.097496  frozenset({valor_contratoo_q_2, tipo_contrato_...
71   0.097660  frozenset({dias_espera_inicio_q_1, tipo_contra...
329  0.098120  frozenset({tipo_contrato_Prestación de servici...
245  0.098185  frozenset({valor_contratoo_q_2, modalidad_cont...
401  0.098481  frozenset({tipo_contrato_Prestación de servici...
399  0.098940  frozenset({modalidad_contratacion_Contratación...
307  0.098973  frozenset({tipo_contrato_Prestación de servici...
99   0.099268  frozenset({dias_espera_inicio_q_1, valor_contr...
285  0.099564  frozenset({tipo_contrato_Prestación de servici...
195  0.099629  frozenset({tipo_contrato_Prestación de servici...
284  0.100154  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
377  0.100220  frozenset({tipo_contrato_Prestación de servici...
376  0.100515  frozenset({modalidad_contratacion_Contratación...
156  0.100646  frozenset({tipo_contrato_Prestación de servici...
305  0.100811  frozenset({modalidad_contratacion_Contratación...
283  0.101007  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
344  0.101073  frozenset({tipo_contrato_Prestación de servici...
425  0.101204  frozenset({tipo_contrato_Prestación de servici...
226  0.101336  frozenset({dias_espera_inicio_q_1, valor_contr...
193  0.101368  frozenset({tipo_contrato_Prestación de servici...
400  0.101697  frozenset({tipo_contrato_Prestación de servici...
436  0.101762  frozenset({dias_espera_inicio_q_1, sector_Serv...
328  0.102058  frozenset({rama_Corporación Autónoma, modalida...
170  0.102320  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
153  0.102484  frozenset({valor_contratoo_q_0, duracion_contr...
306  0.102812  frozenset({tipo_contrato_Prestación de servici...
343  0.103436  frozenset({centralizada_Descentralizada, rama_...
244  0.103469  frozenset({valor_contratoo_q_2, tipo_contrato_...
281  0.103501  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
59   0.103830  frozenset({dias_espera_inicio_q_1, duracion_co...
286  0.103961  frozenset({tipo_contrato_Prestación de servici...
192  0.103994  frozenset({rama_Ejecutivo, modalidad_contratac...
332  0.104355  frozenset({rama_Ejecutivo, sector_Salud y Prot...
371  0.104519  frozenset({tipo_contrato_Prestación de servici...
409  0.104748  frozenset({duracion_contrato_q_1, valor_contra...
356  0.104814        frozenset({rama_Ejecutivo, liquidacion_Si})
190  0.104880  frozenset({tipo_contrato_Prestación de servici...
363  0.105470  frozenset({dias_espera_inicio_q_1, valor_contr...
265  0.105569  frozenset({tipo_contrato_Prestación de servici...
148  0.105700  frozenset({dias_espera_inicio_q_0, duracion_co...
161  0.106127  frozenset({rama_Ejecutivo, duracion_contrato_q...
372  0.106258  frozenset({tipo_contrato_Prestación de servici...
123  0.106586  frozenset({tipo_contrato_Prestación de servici...
205  0.107046  frozenset({dias_espera_inicio_q_1, duracion_co...
227  0.107177  frozenset({valor_contratoo_q_2, duracion_contr...
398  0.107603  frozenset({tipo_contrato_Prestación de servici...
320  0.107866  frozenset({dias_espera_inicio_q_1, tipo_contra...
264  0.108161  frozenset({tipo_contrato_Prestación de servici...
397  0.108227  frozenset({modalidad_contratacion_Contratación...
304  0.108325  frozenset({rama_Ejecutivo, duracion_contrato_q...
262  0.108325  frozenset({rama_Ejecutivo, modalidad_contratac...
330  0.109704  frozenset({tipo_contrato_Prestación de servici...
216  0.110458  frozenset({tipo_contrato_Prestación de servici...
333  0.110688  frozenset({modalidad_contratacion_Contratación...
282  0.110754  frozenset({tipo_contrato_Prestación de servici...
182  0.111377  frozenset({dias_desde_primer_contrato_q_2, dur...
455  0.111377               frozenset({rama_Ejecutivo, pime_Si})
280  0.111377  frozenset({valor_contratoo_q_0, modalidad_cont...
191  0.111935  frozenset({tipo_contrato_Prestación de servici...
421  0.112034  frozenset({tipo_contrato_Prestación de servici...
263  0.112230  frozenset({tipo_contrato_Prestación de servici...
298  0.112263  frozenset({dias_espera_inicio_q_1, dias_desde_...
279  0.112427  frozenset({tipo_contrato_Prestación de servici...
316  0.112690  frozenset({tipo_contrato_Prestación de servici...
351  0.112887  frozenset({tipo_contrato_Prestación de servici...
420  0.113346  frozenset({modalidad_contratacion_Contratación...
370  0.113379  frozenset({valor_contratoo_q_3, modalidad_cont...
315  0.113478  frozenset({rama_Ejecutivo, modalidad_contratac...
215  0.113510  frozenset({tipo_contrato_Prestación de servici...
419  0.113773  frozenset({tipo_contrato_Prestación de servici...
314  0.114035  frozenset({tipo_contrato_Prestación de servici...
238  0.114626  frozenset({tipo_contrato_Prestación de servici...
213  0.114725  frozenset({rama_Ejecutivo, modalidad_contratac...
189  0.114757  frozenset({modalidad_contratacion_Contratación...
168  0.114889  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
145  0.114921  frozenset({duracion_contrato_q_0, estado_bpin_...
214  0.115118  frozenset({tipo_contrato_Prestación de servici...
92   0.115118  frozenset({tipo_contrato_Prestación de servici...
270  0.115118  frozenset({valor_contratoo_q_0, estado_bpin_Vá...
261  0.115250  frozenset({tipo_contrato_Prestación de servici...
260  0.115282  frozenset({modalidad_contratacion_Contratación...
272  0.115676  frozenset({valor_contratoo_q_0, dias_desde_pri...
188  0.115906  frozenset({tipo_contrato_Prestación de servici...
237  0.116037  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
173  0.116300  frozenset({tipo_contrato_Prestación de servici...
342  0.116464  frozenset({tipo_contrato_Prestación de servici...
350  0.116693  frozenset({rama_Ejecutivo, sector_No aplica/No...
155  0.116825  frozenset({tipo_contrato_Prestación de servici...
187  0.116956  frozenset({rama_Ejecutivo, dias_desde_primer_c...
303  0.117153  frozenset({tipo_contrato_Prestación de servici...
91   0.117219  frozenset({dias_desde_primer_contrato_q_1, ram...
235  0.117415  frozenset({valor_contratoo_q_2, tipo_contrato_...
312  0.117809  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
89   0.118269  frozenset({dias_desde_primer_contrato_q_1, tip...
267  0.118400  frozenset({valor_contratoo_q_0, dias_espera_in...
349  0.118433  frozenset({tipo_contrato_Prestación de servici...
313  0.118466  frozenset({tipo_contrato_Prestación de servici...
212  0.119187  frozenset({tipo_contrato_Prestación de servici...
311  0.119253  frozenset({modalidad_contratacion_Contratación...
339  0.119352  frozenset({centralizada_Descentralizada, modal...
211  0.119778  frozenset({modalidad_contratacion_Contratación...
310  0.120270  frozenset({tipo_contrato_Prestación de servici...
417  0.120402  frozenset({rama_Ejecutivo, duracion_contrato_q...
70   0.120434  frozenset({tipo_contrato_Prestación de servici...
259  0.120927  frozenset({rama_Ejecutivo, dias_espera_inicio_...
172  0.121353  frozenset({rama_Ejecutivo, duracion_contrato_q...
236  0.121517  frozenset({valor_contratoo_q_2, tipo_contrato_...
367  0.121616  frozenset({tipo_contrato_Prestación de servici...
112  0.121846  frozenset({tipo_contrato_Prestación de servici...
121  0.122141         frozenset({rama_Ejecutivo, prorrogado_Si})
396  0.122239  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
152  0.122469  frozenset({rama_Ejecutivo, duracion_contrato_q...
69   0.122600  frozenset({modalidad_contratacion_Contratación...
111  0.122666  frozenset({modalidad_contratacion_Contratación...
90   0.122732  frozenset({dias_desde_primer_contrato_q_1, tip...
234  0.123027  frozenset({valor_contratoo_q_2, modalidad_cont...
67   0.123191  frozenset({tipo_contrato_Prestación de servici...
110  0.123552  frozenset({tipo_contrato_Prestación de servici...
369  0.123650  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
418  0.123913  frozenset({tipo_contrato_Prestación de servici...
368  0.124011  frozenset({tipo_contrato_Prestación de servici...
295  0.124077  frozenset({duracion_contrato_q_3, dias_desde_p...
296  0.124077  frozenset({estado_bpin_Válido, dias_desde_prim...
233  0.124569  frozenset({valor_contratoo_q_2, tipo_contrato_...
88   0.124930  frozenset({dias_desde_primer_contrato_q_1, mod...
416  0.125324  frozenset({modalidad_contratacion_Contratación...
232  0.125685  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
415  0.125980  frozenset({tipo_contrato_Prestación de servici...
210  0.126309  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
108  0.126538  frozenset({rama_Ejecutivo, valor_contratoo_q_1...
53   0.126571  frozenset({tipo_contrato_Prestación de servici...
87   0.126834  frozenset({dias_desde_primer_contrato_q_1, tip...
22   0.128540                        frozenset({liquidacion_Si})
254  0.128868  frozenset({dias_espera_inicio_q_0, estado_bpin...
341  0.128934  frozenset({tipo_contrato_Prestación de servici...
167  0.129131  frozenset({tipo_contrato_Prestación de servici...
178  0.129295  frozenset({dias_desde_primer_contrato_q_2, est...
86   0.130017  frozenset({dias_desde_primer_contrato_q_1, ram...
68   0.130115  frozenset({tipo_contrato_Prestación de servici...
352  0.130575  frozenset({tipo_contrato_Prestación de servici...
375  0.131297  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
120  0.131329  frozenset({tipo_contrato_Prestación de servici...
109  0.131428  frozenset({tipo_contrato_Prestación de servici...
107  0.132248  frozenset({modalidad_contratacion_Contratación...
66   0.132412  frozenset({modalidad_contratacion_Contratación...
50   0.132478  frozenset({tipo_contrato_Prestación de servici...
52   0.132773  frozenset({modalidad_contratacion_Contratación...
366  0.132872  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
203  0.133036  frozenset({estado_bpin_Válido, duracion_contra...
406  0.133266  frozenset({duracion_contrato_q_1, estado_bpin_...
65   0.133298  frozenset({tipo_contrato_Prestación de servici...
225  0.133331  frozenset({valor_contratoo_q_2, estado_bpin_Vá...
106  0.133397  frozenset({tipo_contrato_Prestación de servici...
388  0.133823  frozenset({estado_bpin_Válido, dias_desde_prim...
64   0.134184  frozenset({rama_Ejecutivo, duracion_contrato_q...
345  0.134578  frozenset({rama_Ejecutivo, sector_No aplica/No...
447  0.135267  frozenset({tipo_contrato_Prestación de servici...
347  0.135924  frozenset({sector_No aplica/No pertenece, moda...
51   0.136252  frozenset({tipo_contrato_Prestación de servici...
97   0.136777  frozenset({valor_contratoo_q_1, estado_bpin_Vá...
395  0.137466  frozenset({tipo_contrato_Prestación de servici...
27   0.138385                               frozenset({pime_Si})
79   0.139205  frozenset({dias_desde_primer_contrato_q_1, est...
327  0.139238  frozenset({tipo_contrato_Prestación de servici...
346  0.139862  frozenset({tipo_contrato_Prestación de servici...
446  0.139894  frozenset({sector_Servicio Público, rama_Ejecu...
444  0.140977  frozenset({sector_Servicio Público, rama_Ejecu...
361  0.141174  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
445  0.141273  frozenset({sector_Servicio Público, modalidad_...
151  0.141338  frozenset({tipo_contrato_Prestación de servici...
365  0.141437  frozenset({tipo_contrato_Prestación de servici...
49   0.142815  frozenset({modalidad_contratacion_Contratación...
48   0.143274  frozenset({tipo_contrato_Prestación de servici...
338  0.144128  frozenset({rama_Ejecutivo, centralizada_Descen...
57   0.145178  frozenset({duracion_contrato_q_2, estado_bpin_...
364  0.145736  frozenset({tipo_contrato_Prestación de servici...
443  0.146031  frozenset({sector_Servicio Público, modalidad_...
278  0.146687  frozenset({rama_Ejecutivo, tipo_contrato_Prest...

In [183]:
freqitems.shape

(457, 2)

### 4.1.2 MINERÍA DE REGLAS DE ASOCIACIÓN

In [184]:
rules = association_rules(freqitems, metric="lift", min_threshold=1.5)

rules.loc[:, "pearson"] = rules["leverage"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"] *
    (1 - rules["antecedent support"]) * (1 - rules["consequent support"])
)

rules.loc[:, "cosine"] = rules["support"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"]
)

rules.loc[:, "jaccard"] = rules["support"] / (
    rules["antecedent support"] + rules["consequent support"] - rules["support"]
)

rules.loc[:, "kuczynski"] = (rules["support"] / 2) * (
    1 / rules["antecedent support"] + 1 / rules["consequent support"]
)

rules.loc[:, "certainty"] = (
    rules["confidence"] - rules["consequent support"]
) / (1 - rules["consequent support"])

rules.head(100)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
0,frozenset({valor_contratoo_q_0}),frozenset({duracion_contrato_q_0}),0.250878,0.246152,0.148525,0.592021,2.405100,1.0,0.086771,1.847761,0.779869,0.426177,0.458804,0.597704,0.464646,0.597677,0.597704
1,frozenset({duracion_contrato_q_0}),frozenset({valor_contratoo_q_0}),0.246152,0.250878,0.148525,0.603386,2.405100,1.0,0.086771,1.888795,0.774980,0.426177,0.470562,0.597704,0.464646,0.597677,0.597704
2,frozenset({duracion_contrato_q_0}),frozenset({dias_desde_primer_contrato_q_3}),0.246152,0.254619,0.149181,0.606053,2.380234,1.0,0.086506,1.892083,0.769218,0.424305,0.471482,0.595976,0.460966,0.595891,0.595976
3,frozenset({dias_desde_primer_contrato_q_3}),frozenset({duracion_contrato_q_0}),0.254619,0.246152,0.149181,0.585900,2.380234,1.0,0.086506,1.820449,0.777955,0.424305,0.450685,0.595976,0.460966,0.595891,0.595976
4,"frozenset({valor_contratoo_q_0, modalidad_cont...",frozenset({duracion_contrato_q_0}),0.183704,0.246152,0.102484,0.557878,2.266393,1.0,0.057265,1.705066,0.684519,0.313051,0.413513,0.487111,0.343292,0.481943,0.487111
5,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({valor_contratoo_q_0}),0.147639,0.250878,0.102484,0.694154,2.766902,1.0,0.065445,2.449346,0.749195,0.346192,0.591728,0.551328,0.425555,0.532507,0.551328
6,frozenset({valor_contratoo_q_0}),"frozenset({duracion_contrato_q_0, modalidad_co...",0.250878,0.147639,0.102484,0.408502,2.766902,1.0,0.065445,1.441022,0.852444,0.346192,0.306048,0.551328,0.425555,0.532507,0.551328
7,frozenset({duracion_contrato_q_0}),"frozenset({valor_contratoo_q_0, modalidad_cont...",0.246152,0.183704,0.102484,0.416344,2.266393,1.0,0.057265,1.398593,0.741224,0.313051,0.284996,0.487111,0.343292,0.481943,0.487111
8,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({dias_desde_primer_contrato_q_3}),0.147639,0.254619,0.096216,0.651700,2.559514,1.0,0.058625,2.140057,0.714839,0.314390,0.532723,0.514792,0.379345,0.496253,0.514792
9,frozenset({modalidad_contratacion_Contratación...,frozenset({duracion_contrato_q_0}),0.175237,0.246152,0.096216,0.549064,2.230585,1.0,0.053081,1.671739,0.668904,0.295893,0.401820,0.469972,0.324131,0.463270,0.469972
10,frozenset({duracion_contrato_q_0}),frozenset({modalidad_contratacion_Contratación...,0.246152,0.175237,0.096216,0.390881,2.230585,1.0,0.053081,1.354026,0.731828,0.295893,0.261462,0.469972,0.324131,0.463270,0.469972
11,frozenset({dias_desde_primer_contrato_q_3}),"frozenset({duracion_contrato_q_0, modalidad_co...",0.254619,0.147639,0.096216,0.377884,2.559514,1.0,0.058625,1.370099,0.817435,0.314390,0.270126,0.514792,0.379345,0.496253,0.514792
12,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.176254,0.246152,0.100646,0.571030,2.319822,1.0,0.057261,1.757342,0.690665,0.312800,0.430959,0.489954,0.348858,0.483200,0.489954
13,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.141338,0.250878,0.100646,0.712097,2.838420,1.0,0.065188,2.601991,0.754303,0.345189,0.615679,0.556637,0.431637,0.534488,0.556637
14,frozenset({tipo_contrato_Prestación de servici...,"frozenset({duracion_contrato_q_0, modalidad_co...",0.217176,0.147639,0.100646,0.463433,3.138963,1.0,0.068583,1.588546,0.870468,0.380994,0.370493,0.572570,0.468884,0.562073,0.572570
15,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.186296,0.183704,0.100646,0.540250,2.940879,1.0,0.066423,1.775523,0.811064,0.373660,0.436786,0.544062,0.440557,0.544049,0.544062
16,"frozenset({valor_contratoo_q_0, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.183704,0.186296,0.100646,0.547874,2.940879,1.0,0.066423,1.799729,0.808488,0.373660,0.444361,0.544062,0.440557,0.544049,0.544062
17,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.147639,0.217176,0.100646,0.681707,3.138963,1.0,0.068583,2.459445,0.799454,0.380994,0.593404,0.572570,0.468884,0.562073,0.572570
18,frozenset({valor_contratoo_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.250878,0.141338,0.100646,0.401177,2.838420,1.0,0.065188,1.433916,0.864600,0.345189,0.302609,0.556637,0.431637,0.534488,0.556637
19,frozenset({duracion_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.246152,0.176254,0.100646,0.408879,2.319822,1.0,0.057261,1.393531,0.754705,0.312800,0.282398,0.489954,0.348858,0.483200,0.489954
20,"frozenset({rama_Ejecutivo, valor_contratoo_q_0...",frozenset({duracion_contrato_q_0}),0.152922,0.246152,0.084928,0.555365,2.256183,1.0,0.047285,1.695430,0.657288,0.270344,0.410179,0.450193,0.304991,0.437735,0.450193
21,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_0}),0.122469,0.250878,0.084928,0.693462,2.764142,1.0,0.054203,2.443815,0.727295,0.294459,0.590804,0.515992,0.381391,0.484512,0.515992
22,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})","frozenset({duracion_contrato_q_0, modalidad_co...",0.195189,0.147639,0.084928,0.435104,2.947084,1.0,0.056110,1.508882,0.820915,0.329304,0.337258,0.505172,0.399075,0.500289,0.505172
23,"frozenset({valor_contratoo_q_0, modalidad_cont...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.183704,0.193187,0.084928,0.462308,2.393054,1.0,0.049438,1.500511,0.713128,0.290885,0.333560,0.450960,0.323375,0.450818,0.450960
24,"frozenset({rama_Ejecutivo, duracion_contrato_q...","frozenset({valor_contratoo_q_0, modalidad_cont...",0.193187,0.183704,0.084928,0.439613,2.393054,1.0,0.049438,1.456665,0.721511,0.290885,0.313500,0.450960,0.323375,0.450818,0.450960
25,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.147639,0.195189,0.084928,0.575239,2.947084,1.0,0.056110,1.894738,0.775119,0.329304,0.472222,0.505172,0.399075,0.500289,0.505172
26,frozenset({valor_contratoo_q_0}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.250878,0.122469,0.084928,0.338522,2.764142,1.0,0.054203,1.326621,0.851963,0.294459,0.246205,0.515992,0.381391,0.484512,0.515992
27,frozenset({duracion_contrato_q_0}),"frozenset({rama_Ejecutivo, valor_contratoo_q_0...",0.246152,0.152922,0.084928,0.345021,2.256183,1.0,0.047285,1.293289,0.738576,0.270344,0.226778,0.450193,0.304991,0.437735,0.450193
28,"frozenset({rama_Ejecutivo, tipo_contrato_Prest...",frozenset({duracion_contrato_q_0}),0.146687,0.246152,0.083320,0.568009,2.307551,1.0,0.047212,1.745054,0.664047,0.269190,0.426952,0.453249,0.309785,0.438480,0.453249
29,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.116825,0.250878,0.083320,0.713202,2.842827,1.0,0.054011,2.612022,0.733985,0.292984,0.617155,0.522657,0.387867,0.486686,0.522657
30,"frozenset({rama_Ejecutivo, tipo_contrato_Prest...","frozenset({duracion_contrato_q_0, modalidad_co...",0.172415,0.147639,0.083320,0.483251,3.273195,1.0,0.057865,1.649468,0.839174,0.351955,0.393744,0.523799,0.431824,0.522227,0.523799
31,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.176254,0.193187,0.083320,0.472724,2.446970,1.0,0.049270,1.530152,0.717857,0.291203,0.346470,0.452007,0.327519,0.451532,0.452007
32,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.147705,0.183704,0.083320,0.564097,3.070690,1.0,0.056186,1.872655,0.791205,0.335847,0.465999,0.508826,0.408933,0.505815,0.508826
33,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.141338,0.195189,0.083320,0.589505,3.020175,1.0,0.055732,1.960588,0.778995,0.329057,0.489949,0.508186,0.403635,0.501637,0.508186
34,"frozenset({rama_Ejecutivo, valor_contratoo_q_0...",frozenset({tipo_contrato_Prestación de servici...,0.152922,0.186296,0.083320,0.544850,2.924645,1.0,0.054831,1.787770,0.776880,0.325596,0.440644,0.496047,0.391285,0.493640,0.496047
35,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.122469,0.217176,0.083320,0.680332,3.132633,1.0,0.056722,2.448868,0.775790,0.325054,0.591648,0.531991,0.419635,0.510891,0.531991
36,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.217176,0.122469,0.083320,0.383651,3.132633,1.0,0.056722,1.423756,0.869646,0.325054,0.297632,0.531991,0.419635,0.510891,0.531991
37,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0...",0.186296,0.152922,0.083320,0.447243,2.924645,1.0,0.054831,1.532460,0.808744,0.325596,0.347455,0.496047,0.391285,0.493640,0.496047
38,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({tipo_contrato_Prestación de servici...,0.195189,0.141338,0.083320,0.426866,3.020175,1.0,0.055732,1.498187,0.831119,0.329057,0.332527,0.508186,0.403635,0.501637,0.508186
39,"frozenset({valor_contratoo_q_0, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.183704,0.147705,0.083320,0.453555,3.070690,1.0,0.056186,1.559709,0.826097,0.335847,0.358855,0.508826,0.408933,0.505815,0.508826
40,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.193187,0.176254,0.083320,0.431289,2.446970,1.0,0.049270,1.448444,0.732923,0.291203,0.309604,0.452007,0.327519,0.451532,0.452007
41,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, tipo_contrato_Prest...",0.147639,0.172415,0.083320,0.564348,3.273195,1.0,0.057865,1.899646,0.814782,0.351955,0.473586,0.523799,0.431824,0.522227,0.523799
42,frozenset({valor_contratoo_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.250878,0.116825,0.083320,0.332112,2.842827,1.0,0.054011,1.322341,0.865329,0.292984,0.243766,0.522657,0.387867,0.486686,0.522657
43,frozenset({duracion_contrato_q_0}),"frozenset({rama_Ejecutivo, tipo_contrato_Prest...",0.246152,0.146687,0.083320,0.338488,2.307551,1.0,0.047212,1.289943,0.751664,0.269190,0.224772,0.453249,0.309785,0.438480,0.453249
44,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_3}),0.141338,0.254619,0.092082,0.651498,2.558717,1.0,0.056094,2.138812,0.709452,0.303024,0.532451,0.506571,0.369609,0.485397,0.506571
45,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.162603,0.246152,0.092082,0.566297,2.300594,1.0,0.052056,1.738164,0.675104,0.290777,0.424680,0.470190,0.327492,0.460263,0.470190
46,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.186296,0.175237,0.092082,0.494275,2.820608,1.0,0.059436,1.630853,0.793245,0.341737,0.386824,0.509872,0.401544,0.509633,0.509872
47,frozenset({tipo_contrato_Prestación de servici...,"frozenset({duracion_contrato_q_0, modalidad_co...",0.198143,0.147639,0.092082,0.464723,3.147703,1.0,0.062828,1.592375,0.850909,0.362954,0.372007,0.544209,0.444328,0.538373,0.544209
48,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.147639,0.198143,0.092082,0.623694,3.147703,1.0,0.062828,2.130866,0.800492,0.362954,0.530707,0.544209,0.444328,0.538373,0.544209
49,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.175237,0.186296,0.092082,0.525468,2.820608,1.0,0.059436,1.714751,0.782609,0.341737,0.416825,0.509872,0.401544,0.509633,0.509872
50,frozenset({duracion_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.246152,0.162603,0.092082,0.374083,2.300594,1.0,0.052056,1.337873,0.749926,0.290777,0.252545,0.470190,0.327492,0.460263,0.470190
51,frozenset({dias_desde_primer_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254619,0.141338,0.092082,0.361645,2.558717,1.0,0.056094,1.345115,0.817272,0.303024,0.256569,0.506571,0.369609,0.485397,0.506571
52,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({dias_desde_primer_contrato_q_3}),0.122469,0.254619,0.081777,0.667738,2.622502,1.0,0.050594,2.243357,0.705029,0.276920,0.554239,0.494457,0.354261,0.463100,0.494457
53,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({duracion_contrato_q_0}),0.147114,0.246152,0.081777,0.555878,2.258267,1.0,0.045565,1.697388,0.653291,0.262537,0.410859,0.444050,0.298617,0.429738,0.444050
54,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({modalidad_contratacion_Contratación...,0.193187,0.175237,0.081777,0.423306,2.415616,1.0,0.047924,1.430156,0.726348,0.285289,0.300776,0.444986,0.319299,0.444458,0.444986
55,"frozenset({rama_Ejecutivo, dias_desde_primer_c...","frozenset({duracion_contrato_q_0, modalidad_co...",0.206576,0.147639,0.081777,0.395870,2.681338,1.0,0.051279,1.410890,0.790311,0.300169,0.291227,0.474885,0.357052,0.468266,0.474885
56,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.147639,0.206576,0.081777,0.553901,2.681338,1.0,0.051279,1.778582,0.735665,0.300169,0.437754,0.474885,0.357052,0.468266,0.474885
57,frozenset({modalidad_contratacion_Contratación...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.175237,0.193187,0.081777,0.466667,2.415616,1.0,0.047924,1.512774,0.710540,0.285289,0.338963,0.444986,0.319299,0.444458,0.444986
58,frozenset({duracion_contrato_q_0}),"frozenset({rama_Ejecutivo, modalidad_contratac...",0.246152,0.147114,0.081777,0.332222,2.258267,1.0,0.045565,1.277201,0.739118,0.262537,0.217038,0.444050,0.298617,0.429738,0.444050
59,frozenset({dias_desde_primer_contrato_q_3}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.254619,0.122469,0.081777,0.321175,2.622502,1.0,0.050594,1.292721,0.830025,0.276920,0.226438,0.494457,0.354261,0.463100,0.494457
60,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.217176,0.246152,0.129131,0.594591,2.415539,1.0,0.075672,1.859472,0.748589,0.386390,0.462213,0.559594,0.426045,0.558498,0.559594
61,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.186296,0.250878,0.129131,0.693148,2.762890,1.0,0.082393,2.441313,0.784143,0.419197,0.590384,0.603932,0.488145,0.597306,0.603932
62,frozenset({valor_contratoo_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.250878,0.186296,0.129131,0.514716,2.762890,1.0,0.082393,1.676756,0.851744,0.419197,0.403610,0.603932,0.488145,0.597306,0.603932
63,frozenset({duracion_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.246152,0.217176,0.129131,0.524597,2.415539,1.0,0.075672,1.646653,0.777364,0.386390,0.392707,0.559594,0.426045,0.558498,0.559594
64,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({duracion_contrato_q_0}),0.195189,0.246152,0.114889,0.588601,2.391207,1.0,0.066842,1.832401,0.722904,0.351930,0.454268,0.527669,0.391501,0.524140,0.527669
65,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_0}),0.193187,0.250878,0.114889,0.594700,2.370477,1.0,0.066422,1.848316,0.716578,0.349018,0.458967,0.526323,0.388088,0.521863,0.526323
66,frozenset({valor_contratoo_q_0}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.250878,0.193187,0.114889,0.457946,2.370477,1.0,0.066422,1.488437,0.771762,0.349018,0.328154,0.526323,0.388088,0.521863,0.526323
67,frozenset({duracion_contrato_q_0}),"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.246152,0.195189,0.114889,0.466738,2.391207,1.0,0.066842,1.509221,0.771776,0.351930,0.337407,0.527669,0.391501,0.524140,0.527669
68,"frozenset({valor_contratoo_q_0, duracion_contr...",frozenset({dias_desde_primer_contrato_q_3}),0.148525,0.254619,0.089062,0.599646,2.355075,1.0,0.051245,1.861807,0.675751,0.283565,0.462888,0.474717,0.330775,0.457983,0.474717
69,"frozenset({valor_contratoo_q_0, dias_desde_pri...",frozenset({duracion_contrato_q_0}),0.115676,0.246152,0.089062,0.769929,3.127856,1.0,0.060588,3.276588,0.769280,0.326516,0.694804,0.565874,0.439763,0.527802,0.565874
70,"frozenset({duracion_contrato_q_0, dias_desde_p...",frozenset({valor_contratoo_q_0}),0.149181,0.250878,0.089062,0.597008,2.379678,1.0,0.051636,1.858903,0.681432,0.286378,0.462048,0.476006,0.334327,0.460369,0.476006
71,frozenset({valor_contratoo_q_0}),"frozenset({duracion_contrato_q_0, dias_desde_p...",0.250878,0.149181,0.089062,0.355003,2.379678,1.0,0.051636,1.319106,0.773939,0.286378,0.241911,0.476006,0.334327,0.460369,0.476006
72,frozenset({duracion_contrato_q_0}),"frozenset({valor_contratoo_q_0, dias_desde_pri...",0.246152,0.115676,0.089062,0.361818,3.127856,1.0,0.060588,1.385693,0.902427,0.326516,0.278339,0.565874,0.439763,0.527802,0.565874
73,frozenset({dias_desde_primer_contrato_q_3}),"frozenset({valor_contratoo_q_0, duracion_contr...",0.254619,0.148525,0.089062,0.349787,2.355075,1.0,0.051245,1.309533,0.771934,0.283565,0.236369,0.474717,0.330775,0.457983,0.474717
74,"frozenset({rama_Ejecutivo, tipo_contrato_Prest...",frozenset({duracion_contrato_q_0}),0.172415,0.246152,0.102320,0.593453,2.410916,1.0,0.059880,1.854268,0.707142,0.323545,0.460704,0.504565,0.367995,0.496674,0.504565
75,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.147705,0.250878,0.102320,0.692735,2.761244,1.0,0.065264,2.438032,0.748384,0.345370,0.589833,0.550292,0.424303,0.531536,0.550292
76,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.217176,0.193187,0.102320,0.471139,2.438768,1.0,0.060364,1.525567,0.753626,0.332161,0.344506,0.500390,0.370824,0.499535,0.500390
77,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({tipo_contrato_Prestación de servici...,0.195189,0.186296,0.102320,0.524210,2.813853,1.0,0.065957,1.710216,0.800953,0.366522,0.415279,0.536722,0.427417,0.536576,0.536722
78,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.186296,0.195189,0.102320,0.549234,2.813853,1.0,0.065957,1.785428,0.792199,0.366522,0.439910,0.536722,0.427417,0.536576,0.536722
79,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.193187,0.217176,0.102320,0.529642,2.438768,1.0,0.060364,1.664314,0.731219,0.332161,0.399152,0.500390,0.370824,0.499535,0.500390
80,frozenset({valor_contratoo_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.250878,0.147705,0.102320,0.407848,2.761244,1.0,0.065264,1.439319,0.851456,0.345370,0.305227,0.550292,0.424303,0.531536,0.550292
81,frozenset({duracion_contrato_q_0}),"frozenset({rama_Ejecutivo, tipo_contrato_Prest...",0.246152,0.172415,0.102320,0.415678,2.410916,1.0,0.059880,1.416317,0.776311,0.323545,0.293943,0.504565,0.367995,0.496674,0.504565
82,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_3}),0.129131,0.254619,0.081023,0.627446,2.464256,1.0,0.048143,2.000733,0.682304,0.267642,0.500183,0.472829,0.329542,0.446834,0.472829
83,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.103961,0.246152,0.081023,0.779356,3.166153,1.0,0.055432,3.416580,0.763537,0.301098,0.707310,0.554256,0.421620,0.506488,0.554256
84,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.116300,0.250878,0.081023,0.696670,2.776931,1.0,0.051846,2.469664,0.724103,0.283142,0.595087,0.509813,0.373046,0.474335,0.509813
85,frozenset({tipo_contrato_Prestación de servici...,"frozenset({duracion_contrato_q_0, dias_desde_p...",0.217176,0.149181,0.081023,0.373073,2.500807,1.0,0.048624,1.357127,0.766620,0.283956,0.263149,0.458094,0.331007,0.450135,0.458094
86,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, dias_desde_pri...",0.186296,0.115676,0.081023,0.434913,3.759744,1.0,0.059473,1.564933,0.902078,0.366701,0.360995,0.567669,0.477588,0.551928,0.567669

In [190]:
rules_sub=rules[(rules.confidence > 0.5)&(rules.zhangs_metric > 0.5)].sort_values(by='lift',ascending=False)
rules_sub.head(100)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
297,frozenset({sector_Salud y Protección Social}),frozenset({modalidad_contratacion_Contratación...,0.150658,0.150527,0.110688,0.734698,4.880851,1.0,0.088010,3.201915,0.936157,0.581051,0.687687,0.735019,0.688040,0.735019,0.735019
296,frozenset({modalidad_contratacion_Contratación...,frozenset({sector_Salud y Protección Social}),0.150527,0.150658,0.110688,0.735339,4.880851,1.0,0.088010,3.209170,0.936013,0.581051,0.688393,0.735019,0.688040,0.735019,0.735019
89,"frozenset({valor_contratoo_q_0, dias_desde_pri...",frozenset({tipo_contrato_Prestación de servici...,0.115676,0.186296,0.081023,0.700426,3.759744,1.0,0.059473,2.716199,0.830040,0.366701,0.631838,0.567669,0.477588,0.551928,0.567669
289,"frozenset({valor_contratoo_q_3, dias_desde_pri...",frozenset({duracion_contrato_q_3}),0.095954,0.249696,0.082565,0.860465,3.446045,1.0,0.058606,5.377175,0.785150,0.313833,0.814029,0.595563,0.459714,0.533406,0.595563
350,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.155285,0.179897,0.091950,0.592139,3.291543,1.0,0.064015,2.010740,0.824173,0.378036,0.502671,0.551633,0.460167,0.550144,0.551633
341,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.179897,0.155285,0.091950,0.511127,3.291543,1.0,0.064015,1.727883,0.848907,0.378036,0.421257,0.551633,0.460167,0.550144,0.551633
340,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.145736,0.192137,0.091950,0.630939,3.283792,1.0,0.063949,2.188968,0.814120,0.373899,0.543164,0.554752,0.460024,0.549496,0.554752
41,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, tipo_contrato_Prest...",0.147639,0.172415,0.083320,0.564348,3.273195,1.0,0.057865,1.899646,0.814782,0.351955,0.473586,0.523799,0.431824,0.522227,0.523799
344,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({tipo_contrato_Prestación de servici...,0.132872,0.211827,0.091950,0.692023,3.266926,1.0,0.063804,2.559192,0.800230,0.363802,0.609252,0.563052,0.460036,0.548083,0.563052
325,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.211827,0.155285,0.106258,0.501627,3.230361,1.0,0.073364,1.694944,0.875997,0.407347,0.410010,0.592952,0.495752,0.585877,0.592952
326,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.155285,0.211827,0.106258,0.684277,3.230361,1.0,0.073364,2.496409,0.817361,0.407347,0.599425,0.592952,0.495752,0.585877,0.592952
83,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.103961,0.246152,0.081023,0.779356,3.166153,1.0,0.055432,3.416580,0.763537,0.301098,0.707310,0.554256,0.421620,0.506488,0.554256
324,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.175336,0.192137,0.106258,0.606027,3.154133,1.0,0.072570,2.050551,0.828162,0.406784,0.512326,0.579529,0.484402,0.578923,0.579529
327,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.192137,0.175336,0.106258,0.553032,3.154133,1.0,0.072570,1.845017,0.845386,0.406784,0.458000,0.579529,0.484402,0.578923,0.579529
346,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, modalidad_contratac...",0.175336,0.166508,0.091950,0.524424,3.149544,1.0,0.062755,1.752596,0.827602,0.367958,0.429418,0.538326,0.443006,0.538146,0.538326
345,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({tipo_contrato_Prestación de servici...,0.166508,0.175336,0.091950,0.552227,3.149544,1.0,0.062755,1.841702,0.818837,0.367958,0.457024,0.538326,0.443006,0.538146,0.538326
48,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.147639,0.198143,0.092082,0.623694,3.147703,1.0,0.062828,2.130866,0.800492,0.362954,0.530707,0.544209,0.444328,0.538373,0.544209
17,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.147639,0.217176,0.100646,0.681707,3.138963,1.0,0.068583,2.459445,0.799454,0.380994,0.593404,0.572570,0.468884,0.562073,0.572570
35,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.122469,0.217176,0.083320,0.680332,3.132633,1.0,0.056722,2.448868,0.775790,0.325054,0.591648,0.531991,0.419635,0.510891,0.531991
69,"frozenset({valor_contratoo_q_0, dias_desde_pri...",frozenset({duracion_contrato_q_0}),0.115676,0.246152,0.089062,0.769929,3.127856,1.0,0.060588,3.276588,0.769280,0.326516,0.694804,0.565874,0.439763,0.527802,0.565874
342,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.141437,0.209234,0.091950,0.650116,3.107118,1.0,0.062357,2.260079,0.789876,0.355403,0.557538,0.544788,0.439923,0.534509,0.544788
32,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.147705,0.183704,0.083320,0.564097,3.070690,1.0,0.056186,1.872655,0.791205,0.335847,0.465999,0.508826,0.408933,0.505815,0.508826
338,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.121616,0.249696,0.091950,0.756071,3.027961,1.0,0.061583,3.075913,0.762474,0.329144,0.674893,0.562160,0.435312,0.527657,0.562160
33,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.141338,0.195189,0.083320,0.589505,3.020175,1.0,0.055732,1.960588,0.778995,0.329057,0.489949,0.508186,0.403635,0.501637,0.508186
322,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.141437,0.249696,0.106258,0.751276,3.008758,1.0,0.070942,3.016612,0.777621,0.372999,0.668502,0.588412,0.470338,0.565424,0.588412
334,"frozenset({valor_contratoo_q_3, modalidad_cont...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.155285,0.209234,0.097332,0.626796,2.995665,1.0,0.064841,2.118858,0.788650,0.364284,0.528048,0.545989,0.440139,0.539976,0.545989
25,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.147639,0.195189,0.084928,0.575239,2.947084,1.0,0.056110,1.894738,0.775119,0.329304,0.472222,0.505172,0.399075,0.500289,0.505172
16,"frozenset({valor_contratoo_q_0, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.183704,0.186296,0.100646,0.547874,2.940879,1.0,0.066423,1.799729,0.808488,0.373660,0.444361,0.544062,0.440557,0.544049,0.544062
15,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.186296,0.183704,0.100646,0.540250,2.940879,1.0,0.066423,1.775523,0.811064,0.373660,0.436786,0.544062,0.440557,0.544049,0.544062
330,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({duracion_contrato_q_3}),0.132872,0.249696,0.097332,0.732527,2.933668,1.0,0.064154,2.805151,0.760130,0.341233,0.643513,0.561164,0.436661,0.534359,0.561164
34,"frozenset({rama_Ejecutivo, valor_contratoo_q_0...",frozenset({tipo_contrato_Prestación de servici...,0.152922,0.186296,0.083320,0.544850,2.924645,1.0,0.054831,1.787770,0.776880,0.325596,0.440644,0.496047,0.391285,0.493640,0.496047
310,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({duracion_contrato_q_3}),0.155285,0.249696,0.113379,0.730135,2.924091,1.0,0.074605,2.780295,0.778977,0.388814,0.640326,0.592101,0.475908,0.575787,0.592101
314,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.145736,0.249696,0.104519,0.717181,2.872211,1.0,0.068129,2.652944,0.763038,0.359278,0.623060,0.567882,0.446097,0.547905,0.567882
316,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.175336,0.209234,0.104519,0.596107,2.848992,1.0,0.067833,1.957859,0.786985,0.373213,0.489238,0.547818,0.438555,0.545686,0.547818
29,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.116825,0.250878,0.083320,0.713202,2.842827,1.0,0.054011,2.612022,0.733985,0.292984,0.617155,0.522657,0.387867,0.486686,0.522657
13,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.141338,0.250878,0.100646,0.712097,2.838420,1.0,0.065188,2.601991,0.754303,0.345189,0.615679,0.556637,0.431637,0.534488,0.556637
302,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.175336,0.249696,0.124011,0.707281,2.832561,1.0,0.080231,2.563217,0.784516,0.411970,0.609865,0.601965,0.487464,0.592680,0.601965
49,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.175237,0.186296,0.092082,0.525468,2.820608,1.0,0.059436,1.714751,0.782609,0.341737,0.416825,0.509872,0.401544,0.509633,0.509872
77,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({tipo_contrato_Prestación de servici...,0.195189,0.186296,0.102320,0.524210,2.813853,1.0,0.065957,1.710216,0.800953,0.366522,0.415279,0.536722,0.427417,0.536576,0.536722
78,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.186296,0.195189,0.102320,0.549234,2.813853,1.0,0.065957,1.785428,0.792199,0.366522,0.439910,0.536722,0.427417,0.536576,0.536722
84,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.116300,0.250878,0.081023,0.696670,2.776931,1.0,0.051846,2.469664,0.724103,0.283142,0.595087,0.509813,0.373046,0.474335,0.509813
5,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({valor_contratoo_q_0}),0.147639,0.250878,0.102484,0.694154,2.766902,1.0,0.065445,2.449346,0.749195,0.346192,0.591728,0.551328,0.425555,0.532507,0.551328
21,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_0}),0.122469,0.250878,0.084928,0.693462,2.764142,1.0,0.054203,2.443815,0.727295,0.294459,0.590804,0.515992,0.381391,0.484512,0.515992
62,frozenset({valor_contratoo_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.250878,0.186296,0.129131,0.514716,2.762890,1.0,0.082393,1.676756,0.851744,0.419197,0.403610,0.603932,0.488145,0.597306,0.603932
61,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.186296,0.250878,0.129131,0.693148,2.762890,1.0,0.082393,2.441313,0.784143,0.419197,0.590384,0.603932,0.488145,0.597306,0.603932
75,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.147705,0.250878,0.102320,0.692735,2.761244,1.0,0.065264,2.438032,0.748384,0.345370,0.589833,0.550292,0.424303,0.531536,0.550292
88,"frozenset({valor_contratoo_q_0, duracion_contr...",frozenset({tipo_contrato_Prestación de servici...,0.148525,0.198143,0.081023,0.545515,2.753142,1.0,0.051593,1.764320,0.747854,0.305003,0.433209,0.477213,0.363975,0.472299,0.477213
290,"frozenset({duracion_contrato_q_3, dias_desde_p...",frozenset({valor_contratoo_q_3}),0.124077,0.247760,0.082565,0.665432,2.685791,1.0,0.051824,2.248394,0.716582,0.285423,0.555238,0.499339,0.364128,0.470906,0.499339
56,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.147639,0.206576,0.081777,0.553901,2.681338,1.0,0.051279,1.778582,0.735665,0.300169,0.437754,0.474885,0.357052,0.468266,0.474885
52,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({dias_desde_primer_contrato_q_3}),0.122469,0.254619,0.081777,0.667738,2.622502,1.0,0.050594,2.243357,0.705029,0.276920,0.554239,0.494457,0.354261,0.463100,0.494457
355,"frozenset({estado_bpin_Válido, duracion_contra...",frozenset({valor_contratoo_q_3}),0.133036,0.247760,0.084960,0.638629,2.577606,1.0,0.051999,2.081624,0.705961,0.287188,0.519606,0.490771,0.354666,0.467969,0.490771
266,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.179897,0.195320,0.090014,0.500365,2.561764,1.0,0.054877,1.610534,0.743375,0.315614,0.379088,0.480609,0.360376,0.480203,0.480609
8,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({dias_desde_primer_contrato_q_3}),0.147639,0.254619,0.096216,0.651700,2.559514,1.0,0.058625,2.140057,0.714839,0.314390,0.532723,0.514792,0.379345,0.496253,0.514792
44,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_3}),0.141338,0.254619,0.092082,0.651498,2.558717,1.0,0.056094,2.138812,0.709452,0.303024,0.532451,0.506571,0.369609,0.485397,0.506571
102,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_3}),0.147705,0.254619,0.095166,0.644301,2.530454,1.0,0.057558,2.095541,0.709629,0.309829,0.522796,0.509030,0.372373,0.490728,0.509030
343,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.178223,0.204673,0.091950,0.515927,2.520739,1.0,0.055473,1.642990,0.734130,0.316039,0.391354,0.482591,0.359267,0.481438,0.482591
90,"frozenset({duracion_contrato_q_0, dias_desde_p...",frozenset({tipo_contrato_Prestación de servici...,0.149181,0.217176,0.081023,0.543115,2.500807,1.0,0.048624,1.713394,0.705355,0.283956,0.416363,0.458094,0.331007,0.450135,0.458094
335,frozenset({modalidad_contratacion_Contratación...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.192137,0.204673,0.097332,0.506576,2.475049,1.0,0.058007,1.611852,0.737709,0.325005,0.379596,0.491062,0.364923,0.490817,0.491062
104,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.186296,0.206576,0.095166,0.510833,2.472855,1.0,0.056682,1.621990,0.731973,0.319665,0.383473,0.485758,0.359597,0.485111,0.485758
268,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.178223,0.204312,0.090014,0.505064,2.472021,1.0,0.053601,1.607657,0.724616,0.307718,0.377977,0.472818,0.347372,0.471717,0.472818
94,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({dias_desde_primer_contrato_q_3}),0.193187,0.254619,0.121353,0.628164,2.467075,1.0,0.072164,2.004595,0.737051,0.371733,0.501146,0.552386,0.419577,0.547163,0.552386
82,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_3}),0.129131,0.254619,0.081023,0.627446,2.464256,1.0,0.048143,2.000733,0.682304,0.267642,0.500183,0.472829,0.329542,0.446834,0.472829
271,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({tipo_contrato_Prestación de servici...,0.172677,0.211827,0.090014,0.521285,2.460900,1.0,0.053436,1.646434,0.717549,0.305661,0.392627,0.473113,0.346004,0.470655,0.473113
98,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_3}),0.186296,0.254619,0.116300,0.624273,2.451796,1.0,0.068865,1.983839,0.727704,0.358269,0.495927,0.540517,0.406004,0.533988,0.540517
79,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.193187,0.217176,0.102320,0.529642,2.438768,1.0,0.060364,1.664314,0.731219,0.332161,0.399152,0.500390,0.370824,0.499535,0.500390
306,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({duracion_contrato_q_3}),0.204673,0.249696,0.123650,0.604137,2.419484,1.0,0.072544,1.895360,0.737670,0.373884,0.472396,0.549670,0.415409,0.546965,0.549670
60,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.217176,0.246152,0.129131,0.594591,2.415539,1.0,0.075672,1.859472,0.748589,0.386390,0.462213,0.559594,0.426045,0.558498,0.559594
63,frozenset({duracion_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.246152,0.217176,0.129131,0.524597,2.415539,1.0,0.075672,1.646653,0.777364,0.386390,0.392707,0.559594,0.426045,0.558498,0.559594
74,"frozenset({rama_Ejecutivo, tipo_contrato_Prest...",frozenset({duracion_contrato_q_0}),0.172415,0.246152,0.102320,0.593453,2.410916,1.0,0.059880,1.854268,0.707142,0.323545,0.460704,0.504565,0.367995,0.496674,0.504565
318,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({tipo_contrato_Prestación de servici...,0.204673,0.211827,0.104519,0.510662,2.410753,1.0,0.061164,1.610693,0.735788,0.335016,0.379149,0.502039,0.371012,0.501965,0.502039
354,"frozenset({valor_contratoo_q_3, estado_bpin_Vá...",frozenset({duracion_contrato_q_3}),0.141174,0.249696,0.084960,0.601813,2.410179,1.0,0.049710,1.884300,0.681271,0.277730,0.469299,0.471034,0.329828,0.452515,0.471034
323,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.178223,0.247760,0.106258,0.596207,2.406386,1.0,0.062101,1.862934,0.711190,0.332341,0.463212,0.512541,0.375879,0.505666,0.512541
0,frozenset({valor_contratoo_q_0}),frozenset({duracion_contrato_q_0}),0.250878,0.246152,0.148525,0.592021,2.405100,1.0,0.086771,1.847761,0.779869,0.426177,0.458804,0.597704,0.464646,0.597677,0.597704
1,frozenset({duracion_contrato_q_0}),frozenset({valor_contratoo_q_0}),0.246152,0.250878,0.148525,0.603386,2.405100,1.0,0.086771,1.888795,0.774980,0.426177,0.470562,0.597704,0.464646,0.597677,0.597704
253,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.195320,0.211827,0.098973,0.506720,2.392144,1.0,0.057599,1.597822,0.723226,0.321159,0.374148,0.486978,0.355571,0.486577,0.486978
64,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({duracion_contrato_q_0}),0.195189,0.246152,0.114889,0.588601,2.391207,1.0,0.066842,1.832401,0.722904,0.351930,0.454268,0.527669,0.391501,0.524140,0.527669
301,frozenset({duracion_contrato_q_3}),frozenset({valor_contratoo_q_3}),0.249696,0.247760,0.147901,0.592325,2.390717,1.0,0.086037,1.845194,0.775307,0.423113,0.458052,0.594639,0.460431,0.594635,0.594639
300,frozenset({valor_contratoo_q_3}),frozenset({duracion_contrato_q_3}),0.247760,0.249696,0.147901,0.596954,2.390717,1.0,0.086037,1.861581,0.773311,0.423113,0.462822,0.594639,0.460431,0.594635,0.594639
95,"frozenset({rama_Ejecutivo, dias_desde_primer_c...",frozenset({duracion_contrato_q_0}),0.206576,0.246152,0.121353,0.587450,2.386532,1.0,0.070504,1.827290,0.732247,0.366211,0.452741,0.540226,0.404276,0.538158,0.540226
307,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_3}),0.209234,0.247760,0.123650,0.590966,2.385233,1.0,0.071810,1.839065,0.734420,0.370939,0.456245,0.545019,0.408934,0.543079,0.545019
99,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.198143,0.246152,0.116300,0.586949,2.384496,1.0,0.067526,1.825073,0.724099,0.354577,0.452077,0.529710,0.393271,0.526608,0.529710
103,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_0}),0.162144,0.246152,0.095166,0.586926,2.384400,1.0,0.055254,1.824969,0.692968,0.303920,0.452045,0.486770,0.348006,0.476355,0.486770
270,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({tipo_contrato_Prestación de servici...,0.166508,0.226857,0.090014,0.540599,2.383000,1.0,0.052241,1.682939,0.696300,0.296733,0.405801,0.468694,0.334838,0.463145,0.468694
311,frozenset({modalidad_contratacion_Contratación...,frozenset({valor_contratoo_q_3}),0.192137,0.247760,0.113379,0.590094,2.381713,1.0,0.065775,1.835151,0.718110,0.347236,0.455086,0.523855,0.386716,0.519650,0.523855
2,frozenset({duracion_contrato_q_0}),frozenset({dias_desde_primer_contrato_q_3}),0.246152,0.254619,0.149181,0.606053,2.380234,1.0,0.086506,1.892083,0.769218,0.424305,0.471482,0.595976,0.460966,0.595891,0.595976
3,frozenset({dias_desde_primer_contrato_q_3}),frozenset({duracion_contrato_q_0}),0.254619,0.246152,0.149181,0.585900,2.380234,1.0,0.086506,1.820449,0.777955,0.424305,0.450685,0.595976,0.460966,0.595891,0.595976
70,"frozenset({duracion_contrato_q_0, dias_desde_p...",frozenset({valor_contratoo_q_0}),0.149181,0.250878,0.089062,0.597008,2.379678,1.0,0.051636,1.858903,0.681432,0.286378,0.462048,0.476006,0.334327,0.460369,0.476006

In [186]:
vals=[len(list(rules_sub.iloc[k,:].consequents)) == 1 for k in range(rules_sub.shape[0])]

In [187]:
np.array(vals).sum()

np.int64(80)

In [188]:
rules_sub.loc[vals,:].consequents.drop_duplicates()

297    frozenset({modalidad_contratacion_Contratación...
296        frozenset({sector_Salud y Protección Social})
289                   frozenset({duracion_contrato_q_3})
83                    frozenset({duracion_contrato_q_0})
29                      frozenset({valor_contratoo_q_0})
290                     frozenset({valor_contratoo_q_3})
52           frozenset({dias_desde_primer_contrato_q_3})
264          frozenset({dias_desde_primer_contrato_q_0})
299                  frozenset({dias_espera_inicio_q_0})
Name: consequents, dtype: object

In [189]:
vals=[list(rules_sub.iloc[k,:].consequents) == ['duracion_contrato_q_0'] for k in range(rules_sub.shape[0])]
print(rules_sub.loc[vals,:].iloc[0,:].antecedents)
rules_sub.loc[vals,:].iloc[0,:]

frozenset({'tipo_contrato_Prestación de servicios', 'valor_contratoo_q_0', 'dias_desde_primer_contrato_q_3'})

antecedents           frozenset({tipo_contrato_Prestación de servici...
consequents                          frozenset({duracion_contrato_q_0})
antecedent support                                             0.103961
consequent support                                             0.246152
support                                                        0.081023
confidence                                                     0.779356
lift                                                           3.166153
representativity                                                    1.0
leverage                                                       0.055432
conviction                                                      3.41658
zhangs_metric                                                  0.763537
jaccard                                                        0.301098
certainty                                                       0.70731
kulczynski                                                     0.554256
pearson                                                         0.42162
cosine                                                         0.506488
kuczynski                                                      0.554256
Name: 83, dtype: object

In [191]:
cols = [
    'antecedents', 'consequents',
    'antecedent support', 'consequent support',
    'support', 'confidence', 'lift', 'zhangs_metric'
]

seleccion_clase0 = rules.loc[[0, 17, 83], cols].copy()

def limpiar_itemset(x):
    return ' + '.join(list(x))

seleccion_clase0['antecedents'] = seleccion_clase0['antecedents'].apply(limpiar_itemset)
seleccion_clase0['consequents'] = seleccion_clase0['consequents'].apply(limpiar_itemset)

seleccion_clase0

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,zhangs_metric
0,valor_contratoo_q_0,duracion_contrato_q_0,0.250878,0.246152,0.148525,0.592021,2.405100,0.779869
17,duracion_contrato_q_0 + modalidad_contratacion...,tipo_contrato_Prestación de servicios + valor_...,0.147639,0.217176,0.100646,0.681707,3.138963,0.799454
83,tipo_contrato_Prestación de servicios + valor_...,duracion_contrato_q_0,0.103961,0.246152,0.081023,0.779356,3.166153,0.763537

## 4.2 MINERÍA DE LA CLASE 1

In [192]:
df0=dfs.copy()[dfs.clase==1]
df_onehot=pd.concat([pd.get_dummies(df0.loc[:,cuals+[cuant+'_q' for cuant in cuants]],drop_first=False),pd.get_dummies(df0.loc[:,binarias],drop_first=True)],axis=1)
cumplen=(df_onehot.sum(axis=0)/df_onehot.shape[0]>0.1) & (df_onehot.sum(axis=0)/df_onehot.shape[0]<0.9)
df_onehot=df_onehot.loc[:,cumplen]

In [193]:
freqitems =fpgrowth(df_onehot, min_support=0.08, use_colnames=True)

In [194]:
rules = association_rules(freqitems, metric="lift", min_threshold=1.5)

rules.loc[:, "pearson"] = rules["leverage"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"] *
    (1 - rules["antecedent support"]) * (1 - rules["consequent support"])
)

rules.loc[:, "cosine"] = rules["support"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"]
)

rules.loc[:, "jaccard"] = rules["support"] / (
    rules["antecedent support"] + rules["consequent support"] - rules["support"]
)

rules.loc[:, "kuczynski"] = (rules["support"] / 2) * (
    1 / rules["antecedent support"] + 1 / rules["consequent support"]
)

rules.loc[:, "certainty"] = (
    rules["confidence"] - rules["consequent support"]
) / (1 - rules["consequent support"])

rules.head(100)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
0,frozenset({valor_contratoo_q_2}),frozenset({duracion_contrato_q_2}),0.247317,0.258567,0.104361,0.421973,1.631969,1.0,0.040413,1.282697,0.514484,0.259914,0.220393,0.412794,0.213928,0.412692,0.412794
1,frozenset({duracion_contrato_q_2}),frozenset({valor_contratoo_q_2}),0.258567,0.247317,0.104361,0.403614,1.631969,1.0,0.040413,1.262074,0.522291,0.259914,0.207653,0.412794,0.213928,0.412692,0.412794
2,"frozenset({valor_contratoo_q_2, tipo_contrato_...",frozenset({duracion_contrato_q_2}),0.224645,0.258567,0.100554,0.447612,1.731125,1.0,0.042468,1.342232,0.544707,0.262777,0.254972,0.418250,0.232402,0.417218,0.418250
3,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_2}),0.233299,0.247317,0.100554,0.431009,1.742736,1.0,0.042855,1.322837,0.555874,0.264572,0.244049,0.418793,0.234854,0.418615,0.418793
4,frozenset({valor_contratoo_q_2}),frozenset({tipo_contrato_Prestación de servici...,0.247317,0.233299,0.100554,0.406578,1.742736,1.0,0.042855,1.292000,0.566227,0.264572,0.226006,0.418793,0.234854,0.418615,0.418793
5,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, tipo_contrato_...",0.258567,0.224645,0.100554,0.388889,1.731125,1.0,0.042468,1.268762,0.569628,0.262777,0.211830,0.418250,0.232402,0.417218,0.418250
6,"frozenset({valor_contratoo_q_2, modalidad_cont...",frozenset({duracion_contrato_q_2}),0.200242,0.258567,0.094669,0.472774,1.828441,1.0,0.042893,1.406292,0.566529,0.259981,0.288910,0.419453,0.244800,0.416050,0.419453
7,frozenset({modalidad_contratacion_Contratación...,frozenset({valor_contratoo_q_2}),0.213742,0.247317,0.094669,0.442915,1.790877,1.0,0.041807,1.351109,0.561666,0.258385,0.259867,0.412850,0.236370,0.411754,0.412850
8,frozenset({valor_contratoo_q_2}),frozenset({modalidad_contratacion_Contratación...,0.247317,0.213742,0.094669,0.382785,1.790877,1.0,0.041807,1.273881,0.586720,0.258385,0.214997,0.412850,0.236370,0.411754,0.412850
9,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, modalidad_cont...",0.258567,0.200242,0.094669,0.366131,1.828441,1.0,0.042893,1.261709,0.611095,0.259981,0.207424,0.419453,0.244800,0.416050,0.419453
10,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",frozenset({duracion_contrato_q_2}),0.210453,0.258567,0.089997,0.427632,1.653852,1.0,0.035580,1.295377,0.500732,0.237443,0.228024,0.387845,0.199351,0.385799,0.387845
11,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_2}),0.218242,0.247317,0.089997,0.412371,1.667376,1.0,0.036022,1.280881,0.511994,0.239631,0.219287,0.388131,0.202127,0.387373,0.388131
12,frozenset({valor_contratoo_q_2}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.247317,0.218242,0.089997,0.363891,1.667376,1.0,0.036022,1.228969,0.531772,0.239631,0.186310,0.388131,0.202127,0.387373,0.388131
13,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",0.258567,0.210453,0.089997,0.348059,1.653852,1.0,0.035580,1.211070,0.533226,0.237443,0.174284,0.387845,0.199351,0.385799,0.387845
14,"frozenset({valor_contratoo_q_2, tipo_contrato_...",frozenset({duracion_contrato_q_2}),0.196608,0.258567,0.093977,0.477993,1.848623,1.0,0.043141,1.420351,0.571398,0.260182,0.295948,0.420723,0.247915,0.416807,0.420723
15,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_2}),0.209588,0.247317,0.093977,0.448390,1.813013,1.0,0.042142,1.364519,0.567340,0.258941,0.267141,0.414188,0.239980,0.412773,0.414188
16,"frozenset({valor_contratoo_q_2, tipo_contrato_...",frozenset({modalidad_contratacion_Contratación...,0.224645,0.213742,0.093977,0.418336,1.957202,1.0,0.045961,1.351739,0.630765,0.272864,0.260212,0.429006,0.268636,0.428873,0.429006
17,"frozenset({valor_contratoo_q_2, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.200242,0.233299,0.093977,0.469317,2.011658,1.0,0.047261,1.444745,0.628812,0.276758,0.307836,0.436068,0.279239,0.434799,0.436068
18,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_2, modalidad_cont...",0.233299,0.200242,0.093977,0.402819,2.011658,1.0,0.047261,1.339222,0.655924,0.276758,0.253298,0.436068,0.279239,0.434799,0.436068
19,frozenset({modalidad_contratacion_Contratación...,"frozenset({valor_contratoo_q_2, tipo_contrato_...",0.213742,0.224645,0.093977,0.439676,1.957202,1.0,0.045961,1.383762,0.622018,0.272864,0.277332,0.429006,0.268636,0.428873,0.429006
20,frozenset({valor_contratoo_q_2}),frozenset({tipo_contrato_Prestación de servici...,0.247317,0.209588,0.093977,0.379986,1.813013,1.0,0.042142,1.274829,0.595778,0.258941,0.215581,0.414188,0.239980,0.412773,0.414188
21,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, tipo_contrato_...",0.258567,0.196608,0.093977,0.363454,1.848623,1.0,0.043141,1.262111,0.619148,0.260182,0.207677,0.420723,0.247915,0.416807,0.420723
22,"frozenset({valor_contratoo_q_2, tipo_contrato_...",frozenset({duracion_contrato_q_2}),0.193319,0.258567,0.087400,0.452104,1.748498,1.0,0.037414,1.353236,0.530669,0.239791,0.261031,0.395061,0.216386,0.390921,0.395061
23,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_2}),0.198339,0.247317,0.087400,0.440663,1.781772,1.0,0.038348,1.345670,0.547314,0.243961,0.256876,0.397029,0.222900,0.394624,0.397029
24,"frozenset({valor_contratoo_q_2, tipo_contrato_...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.224645,0.218242,0.087400,0.389060,1.782704,1.0,0.038374,1.279599,0.566262,0.245862,0.218505,0.394768,0.222602,0.394727,0.394768
25,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",frozenset({tipo_contrato_Prestación de servici...,0.210453,0.233299,0.087400,0.415296,1.780104,1.0,0.038302,1.311264,0.555047,0.245265,0.237377,0.394963,0.222170,0.394439,0.394963
26,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",0.233299,0.210453,0.087400,0.374629,1.780104,1.0,0.038302,1.262525,0.571585,0.245265,0.207937,0.394963,0.222170,0.394439,0.394963
27,"frozenset({rama_Ejecutivo, duracion_contrato_q...","frozenset({valor_contratoo_q_2, tipo_contrato_...",0.218242,0.224645,0.087400,0.400476,1.782704,1.0,0.038374,1.293284,0.561624,0.245862,0.226774,0.394768,0.222602,0.394727,0.394768
28,frozenset({valor_contratoo_q_2}),frozenset({tipo_contrato_Prestación de servici...,0.247317,0.198339,0.087400,0.353394,1.781772,1.0,0.038348,1.239799,0.582930,0.243961,0.193418,0.397029,0.222900,0.394624,0.397029
29,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, tipo_contrato_...",0.258567,0.193319,0.087400,0.338019,1.748498,1.0,0.037414,1.218585,0.577369,0.239791,0.179376,0.395061,0.216386,0.390921,0.395061
30,"frozenset({valor_contratoo_q_2, rama_Ejecutivo...",frozenset({duracion_contrato_q_2}),0.176186,0.258567,0.083247,0.472495,1.827361,1.0,0.037691,1.405547,0.549593,0.236829,0.288533,0.397225,0.225952,0.390028,0.397225
31,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({valor_contratoo_q_2}),0.187262,0.247317,0.083247,0.444547,1.797476,1.0,0.036934,1.355079,0.545889,0.236946,0.262036,0.390573,0.219426,0.386826,0.390573
32,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",frozenset({modalidad_contratacion_Contratación...,0.210453,0.213742,0.083247,0.395559,1.850641,1.0,0.038264,1.300803,0.582165,0.244162,0.231244,0.392516,0.228980,0.392505,0.392516
33,"frozenset({valor_contratoo_q_2, modalidad_cont...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.200242,0.218242,0.083247,0.415730,1.904909,1.0,0.039546,1.338010,0.593980,0.248322,0.252621,0.398587,0.239241,0.398218,0.398587
34,"frozenset({rama_Ejecutivo, duracion_contrato_q...","frozenset({valor_contratoo_q_2, modalidad_cont...",0.218242,0.200242,0.083247,0.381443,1.904909,1.0,0.039546,1.292942,0.607656,0.248322,0.226570,0.398587,0.239241,0.398218,0.398587
35,frozenset({modalidad_contratacion_Contratación...,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",0.213742,0.210453,0.083247,0.389474,1.850641,1.0,0.038264,1.293223,0.584600,0.244162,0.226738,0.392516,0.228980,0.392505,0.392516
36,frozenset({valor_contratoo_q_2}),"frozenset({rama_Ejecutivo, modalidad_contratac...",0.247317,0.187262,0.083247,0.336599,1.797476,1.0,0.036934,1.225108,0.589444,0.236946,0.183746,0.390573,0.219426,0.386826,0.390573
37,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, rama_Ejecutivo...",0.258567,0.176186,0.083247,0.321954,1.827361,1.0,0.037691,1.214984,0.610659,0.236829,0.176944,0.397225,0.225952,0.390028,0.397225
38,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_2}),0.183628,0.247317,0.082728,0.450518,1.821620,1.0,0.037313,1.369805,0.552491,0.237575,0.269969,0.392509,0.223366,0.388199,0.392509
39,"frozenset({valor_contratoo_q_2, tipo_contrato_...",frozenset({duracion_contrato_q_2}),0.173416,0.258567,0.082728,0.477046,1.844961,1.0,0.037888,1.417778,0.554067,0.236868,0.294671,0.398496,0.228554,0.390678,0.398496
40,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_2, modalidad_cont...",0.198339,0.200242,0.082728,0.417103,2.082991,1.0,0.043012,1.372039,0.648555,0.261918,0.271158,0.415120,0.269545,0.415115,0.415120
41,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",0.209588,0.210453,0.082728,0.394715,1.875546,1.0,0.038619,1.304421,0.590606,0.245254,0.233377,0.393904,0.232769,0.393903,0.393904
42,"frozenset({valor_contratoo_q_2, tipo_contrato_...",frozenset({modalidad_contratacion_Contratación...,0.193319,0.213742,0.082728,0.427932,2.002098,1.0,0.041407,1.374414,0.620474,0.255069,0.272417,0.407488,0.255776,0.406975,0.407488
43,"frozenset({valor_contratoo_q_2, tipo_contrato_...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.196608,0.218242,0.082728,0.420775,1.928022,1.0,0.039820,1.349662,0.599127,0.249088,0.259074,0.399919,0.242565,0.399375,0.399919
44,"frozenset({rama_Ejecutivo, modalidad_contratac...","frozenset({valor_contratoo_q_2, tipo_contrato_...",0.187262,0.224645,0.082728,0.441774,1.966543,1.0,0.040660,1.388963,0.604738,0.251314,0.280039,0.405017,0.249729,0.403345,0.405017
45,"frozenset({valor_contratoo_q_2, rama_Ejecutivo...",frozenset({tipo_contrato_Prestación de servici...,0.176186,0.233299,0.082728,0.469548,2.012648,1.0,0.041624,1.445374,0.610747,0.253178,0.308137,0.412074,0.258328,0.408046,0.412074
46,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_2, rama_Ejecutivo...",0.233299,0.176186,0.082728,0.354599,2.012648,1.0,0.041624,1.276439,0.656243,0.253178,0.216570,0.412074,0.258328,0.408046,0.412074
47,"frozenset({valor_contratoo_q_2, tipo_contrato_...","frozenset({rama_Ejecutivo, modalidad_contratac...",0.224645,0.187262,0.082728,0.368259,1.966543,1.0,0.040660,1.286505,0.633895,0.251314,0.222700,0.405017,0.249729,0.403345,0.405017
48,"frozenset({rama_Ejecutivo, duracion_contrato_q...","frozenset({valor_contratoo_q_2, tipo_contrato_...",0.218242,0.196608,0.082728,0.379064,1.928022,1.0,0.039820,1.293841,0.615707,0.249088,0.227108,0.399919,0.242565,0.399375,0.399919
49,frozenset({modalidad_contratacion_Contratación...,"frozenset({valor_contratoo_q_2, tipo_contrato_...",0.213742,0.193319,0.082728,0.387045,2.002098,1.0,0.041407,1.316051,0.636590,0.255069,0.240151,0.407488,0.255776,0.406975,0.407488
50,"frozenset({valor_contratoo_q_2, rama_Ejecutivo})",frozenset({tipo_contrato_Prestación de servici...,0.210453,0.209588,0.082728,0.393092,1.875546,1.0,0.038619,1.302359,0.591253,0.245254,0.232163,0.393904,0.232769,0.393903,0.393904
51,"frozenset({valor_contratoo_q_2, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.200242,0.198339,0.082728,0.413137,2.082991,1.0,0.043012,1.366012,0.650098,0.261918,0.267942,0.415120,0.269545,0.415115,0.415120
52,frozenset({duracion_contrato_q_2}),"frozenset({valor_contratoo_q_2, tipo_contrato_...",0.258567,0.173416,0.082728,0.319946,1.844961,1.0,0.037888,1.215468,0.617700,0.236868,0.177272,0.398496,0.228554,0.390678,0.398496
53,frozenset({valor_contratoo_q_2}),frozenset({tipo_contrato_Prestación de servici...,0.247317,0.183628,0.082728,0.334500,1.821620,1.0,0.037313,1.226705,0.599241,0.237575,0.184808,0.392509,0.223366,0.388199,0.392509
54,frozenset({valor_contratoo_q_3}),frozenset({duracion_contrato_q_3}),0.254067,0.254933,0.150398,0.591962,2.322034,1.0,0.085628,1.825975,0.763263,0.419402,0.452347,0.590957,0.451317,0.590956,0.590957
55,frozenset({duracion_contrato_q_3}),frozenset({valor_contratoo_q_3}),0.254933,0.254067,0.150398,0.589952,2.322034,1.0,0.085628,1.819138,0.764150,0.419402,0.450289,0.590957,0.451317,0.590956,0.590957
56,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({duracion_contrato_q_3}),0.212530,0.254933,0.125649,0.591205,2.319066,1.0,0.071468,1.822595,0.722303,0.367595,0.451332,0.542038,0.400843,0.539804,0.542038
57,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_3}),0.213742,0.254067,0.125649,0.587854,2.313775,1.0,0.071344,1.809876,0.722162,0.367223,0.447476,0.541202,0.399768,0.539188,0.541202
58,frozenset({valor_contratoo_q_3}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.254067,0.213742,0.125649,0.494550,2.313775,1.0,0.071344,1.555562,0.761202,0.367223,0.357146,0.541202,0.399768,0.539188,0.541202
59,frozenset({duracion_contrato_q_3}),"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.254933,0.212530,0.125649,0.492872,2.319066,1.0,0.071468,1.552802,0.763410,0.367595,0.356003,0.542038,0.400843,0.539804,0.542038
60,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.179647,0.254933,0.124611,0.693642,2.720883,1.0,0.078813,2.432013,0.770976,0.402010,0.588818,0.591220,0.471059,0.582281,0.591220
61,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.214088,0.254067,0.124611,0.582053,2.290943,1.0,0.070218,1.784756,0.716999,0.362720,0.439699,0.536258,0.393224,0.534299,0.536258
62,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254067,0.214088,0.124611,0.490463,2.290943,1.0,0.070218,1.542405,0.755428,0.362720,0.351662,0.536258,0.393224,0.534299,0.536258
63,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254933,0.179647,0.124611,0.488798,2.720883,1.0,0.078813,1.604754,0.848879,0.402010,0.376852,0.591220,0.471059,0.582281,0.591220
64,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({duracion_contrato_q_3}),0.160609,0.254933,0.114573,0.713362,2.798239,1.0,0.073628,2.599333,0.765594,0.380679,0.615286,0.581393,0.460114,0.566217,0.581393
65,frozenset({modalidad_contratacion_Contratación...,frozenset({valor_contratoo_q_3}),0.195050,0.254067,0.114573,0.587400,2.311988,1.0,0.065017,1.807885,0.704978,0.342473,0.446867,0.519177,0.376915,0.514675,0.519177
66,frozenset({valor_contratoo_q_3}),frozenset({modalidad_contratacion_Contratación...,0.254067,0.195050,0.114573,0.450954,2.311988,1.0,0.065017,1.466087,0.760755,0.342473,0.317912,0.519177,0.376915,0.514675,0.519177
67,frozenset({duracion_contrato_q_3}),"frozenset({valor_contratoo_q_3, modalidad_cont...",0.254933,0.160609,0.114573,0.449423,2.798239,1.0,0.073628,1.524566,0.862516,0.380679,0.344075,0.581393,0.460114,0.566217,0.581393
68,"frozenset({valor_contratoo_q_3, estado_bpin_Vá...",frozenset({duracion_contrato_q_3}),0.150571,0.254933,0.087747,0.582759,2.285933,1.0,0.049361,1.785699,0.662259,0.276144,0.439995,0.463477,0.316694,0.447865,0.463477
69,"frozenset({estado_bpin_Válido, duracion_contra...",frozenset({valor_contratoo_q_3}),0.138283,0.254067,0.087747,0.634543,2.497541,1.0,0.052613,2.041097,0.695827,0.288068,0.510067,0.489956,0.350111,0.468135,0.489956
70,frozenset({valor_contratoo_q_3}),"frozenset({estado_bpin_Válido, duracion_contra...",0.254067,0.138283,0.087747,0.345368,2.497541,1.0,0.052613,1.316338,0.803834,0.288068,0.240316,0.489956,0.350111,0.468135,0.489956
71,frozenset({duracion_contrato_q_3}),"frozenset({valor_contratoo_q_3, estado_bpin_Vá...",0.254933,0.150571,0.087747,0.344196,2.285933,1.0,0.049361,1.295247,0.755021,0.276144,0.227947,0.463477,0.316694,0.447865,0.463477
72,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.150917,0.254933,0.105573,0.699541,2.744025,1.0,0.067099,2.479767,0.748539,0.351585,0.596736,0.556831,0.430093,0.538233,0.556831
73,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.183628,0.254067,0.105573,0.574929,2.262903,1.0,0.058919,1.754844,0.683622,0.317874,0.430149,0.495230,0.349558,0.488775,0.495230
74,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.179647,0.213742,0.105573,0.587669,2.749432,1.0,0.067175,1.906860,0.775628,0.366807,0.475578,0.540798,0.426844,0.538763,0.540798
75,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.214088,0.212530,0.105573,0.493129,2.320274,1.0,0.060073,1.553589,0.724020,0.328841,0.356329,0.494936,0.357987,0.494932,0.494936
76,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({tipo_contrato_Prestación de servici...,0.212530,0.214088,0.105573,0.496743,2.320274,1.0,0.060073,1.561651,0.722588,0.328841,0.359652,0.494936,0.357987,0.494932,0.494936
77,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.213742,0.179647,0.105573,0.493927,2.749432,1.0,0.067175,1.621018,0.809262,0.366807,0.383104,0.540798,0.426844,0.538763,0.540798
78,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254067,0.183628,0.105573,0.415531,2.262903,1.0,0.058919,1.396777,0.748177,0.317874,0.284066,0.495230,0.349558,0.488775,0.495230
79,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254933,0.150917,0.105573,0.414121,2.744025,1.0,0.067099,1.449245,0.853039,0.351585,0.309986,0.556831,0.430093,0.538233,0.556831
80,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.144687,0.254933,0.106438,0.735646,2.885650,1.0,0.069553,2.818445,0.763998,0.363046,0.645194,0.576581,0.453657,0.554205,0.576581
81,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.178262,0.254067,0.106438,0.597087,2.350116,1.0,0.061148,1.851351,0.699115,0.326606,0.459854,0.508012,0.366994,0.500142,0.508012
82,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.179647,0.195050,0.106438,0.592486,3.037606,1.0,0.071398,1.975267,0.817689,0.396774,0.493739,0.569091,0.469373,0.568610,0.569091
83,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.214088,0.160609,0.106438,0.497171,3.095530,1.0,0.072054,1.669335,0.861360,0.396774,0.400959,0.579943,0.478416,0.574006,0.579943
84,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.160609,0.214088,0.106438,0.662716,3.095530,1.0,0.072054,2.330116,0.806482,0.396774,0.570837,0.579943,0.478416,0.574006,0.579943
85,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.195050,0.179647,0.106438,0.545697,3.037606,1.0,0.071398,1.805738,0.833336,0.396774,0.446210,0.569091,0.469373,0.568610,0.569091
86,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254067,0.178262,0.106438,0.418937,2.350116,1.0,0.061148,1.414198,0.770162,0.326606,0.292885,0.508012,0.366994,0.500142,0.508012
87,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.254933,0.144687,0.106438,0.417515,2.885650,1.0,0.069553,1.468387,0.877045,0.363046,0.318981,0.576581,0.453657,0.554205,0.576581

In [195]:
rules_sub=rules[(rules.confidence > 0.5)&(rules.zhangs_metric > 0.5)].sort_values(by='lift',ascending=False)
vals=[len(list(rules_sub.iloc[k,:].consequents)) == 1 for k in range(rules_sub.shape[0])]
rules_sub.loc[vals,:].consequents.drop_duplicates()

424        frozenset({sector_Salud y Protección Social})
425    frozenset({modalidad_contratacion_Contratación...
205                   frozenset({duracion_contrato_q_3})
299                   frozenset({duracion_contrato_q_0})
335                     frozenset({valor_contratoo_q_0})
366          frozenset({dias_desde_primer_contrato_q_3})
204          frozenset({dias_desde_primer_contrato_q_0})
206                     frozenset({valor_contratoo_q_3})
427                  frozenset({dias_espera_inicio_q_0})
Name: consequents, dtype: object

In [196]:
vals=[list(rules_sub.iloc[k,:].consequents) == ['sector_Salud y Protección Social'] for k in range(rules_sub.shape[0])]
l=0
print(rules_sub.loc[vals,:].iloc[l,:].antecedents)
rules_sub.loc[vals,:].iloc[l,:]

frozenset({'modalidad_contratacion_Contratación régimen especial'})

antecedents           frozenset({modalidad_contratacion_Contratación...
consequents               frozenset({sector_Salud y Protección Social})
antecedent support                                             0.145898
consequent support                                             0.146244
support                                                        0.106957
confidence                                                     0.733096
lift                                                           5.012816
representativity                                                    1.0
leverage                                                       0.085621
conviction                                                     3.198738
zhangs_metric                                                  0.937255
jaccard                                                         0.57757
certainty                                                      0.687377
kulczynski                                                     0.732229
pearson                                                        0.686424
cosine                                                         0.732228
kuczynski                                                      0.732229
Name: 424, dtype: object

In [197]:
vals=[list(rules_sub.iloc[k,:].consequents) == ['duracion_contrato_q_0'] for k in range(rules_sub.shape[0])]
l=0
print(rules_sub.loc[vals,:].iloc[l,:].antecedents)
rules_sub.loc[vals,:].iloc[l,:]

frozenset({'tipo_contrato_Prestación de servicios', 'valor_contratoo_q_0', 'dias_desde_primer_contrato_q_3'})

antecedents           frozenset({tipo_contrato_Prestación de servici...
consequents                          frozenset({duracion_contrato_q_0})
antecedent support                                             0.100035
consequent support                                             0.242298
support                                                        0.080132
confidence                                                     0.801038
lift                                                           3.305999
representativity                                                    1.0
leverage                                                       0.055893
conviction                                                     3.808274
zhangs_metric                                                  0.775052
jaccard                                                        0.305611
certainty                                                      0.737414
kulczynski                                                     0.565876
pearson                                                        0.434758
cosine                                                         0.514699
kuczynski                                                      0.565876
Name: 299, dtype: object

In [198]:
vals=[list(rules_sub.iloc[k,:].consequents) == ['valor_contratoo_q_0'] for k in range(rules_sub.shape[0])]
l=0
print(rules_sub.loc[vals,:].iloc[l,:].antecedents)
rules_sub.loc[vals,:].iloc[l,:]

frozenset({'tipo_contrato_Prestación de servicios', 'rama_Ejecutivo', 'duracion_contrato_q_0', 'modalidad_contratacion_Contratación directa'})

antecedents           frozenset({tipo_contrato_Prestación de servici...
consequents                            frozenset({valor_contratoo_q_0})
antecedent support                                              0.11215
consequent support                                             0.248875
support                                                        0.084112
confidence                                                         0.75
lift                                                           3.013561
representativity                                                    1.0
leverage                                                       0.056201
conviction                                                       3.0045
zhangs_metric                                                  0.752567
jaccard                                                         0.30375
certainty                                                      0.667166
kulczynski                                                     0.543985
pearson                                                        0.411934
cosine                                                         0.503465
kuczynski                                                      0.543985
Name: 335, dtype: object

## 4.3 MINERÍA DE LA CLASE 2

### 4.3.0 SUBCONJUNTO Y PREPRACIÓN

In [211]:
df0=dfs.copy()[dfs.clase==2]
df0.head()

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q
1,agricultura,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,0,3,0,3,-0.502233,-0.314990,0.007575,0.003116,0.000818,0.132630,0.047187,-0.261014,-0.207582,0.041610,0.177906,0.090063,0.021362,0.113700,-0.266953,0.032131,0.100277,0.052154,0.042238,-0.037100,0.025141,-0.161671,-0.109760,0.206130,0.286944,-0.508839,-0.089393,0.386624,0.709633,0.170777,0.529664,-0.574655,-0.339869,0.541785,0.226969,1.292304,1.291991,-0.388060,2,1,0,3,0,3
2,Salud y Protección Social,Ejecutivo,Centralizada,Prestación de servicios,Contratación régimen especial,No,No,No,No,No,No,No Válido,No,Si,0,2,1,0,1.089181,-0.408082,0.010449,0.011622,0.011589,0.238742,-0.031481,-0.343014,-0.053873,-0.060902,-0.056533,-0.014609,0.334820,0.020835,0.121477,-0.550172,0.169496,-0.077804,-0.090625,0.054882,0.036406,0.091204,0.087001,-0.132702,0.073605,0.015176,-0.013934,0.034000,0.075565,0.016952,0.002795,0.079164,-0.010538,0.088693,-0.077400,1.541353,1.246222,-0.408194,2,2,0,2,1,0
16,Servicio Público,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,0,0,3,1,-0.442577,-0.190577,0.004161,0.002818,0.026690,0.185955,-0.043467,-0.162269,-0.052908,0.073032,0.046968,0.133886,-0.040200,-0.095047,0.021912,0.121379,0.022787,-0.088817,0.051312,0.068660,0.055401,-0.151738,0.004320,-0.078546,0.073219,0.072032,0.195943,-0.081875,-0.014780,-0.219008,-0.012906,0.208623,-0.122016,0.212520,0.030249,1.058909,1.704955,-0.433727,2,16,0,0,3,1
32,Servicio Público,Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,No,0,1,2,0,-0.397731,-0.197147,0.005842,0.006077,0.016604,0.148651,-0.036331,-0.145595,-0.000919,0.052624,0.076648,0.179538,-0.013848,-0.142886,0.058698,0.088930,0.028534,-0.112758,0.075234,0.082162,0.080118,-0.156285,0.005067,-0.117989,0.065349,0.109027,0.241389,-0.095134,-0.028666,-0.236057,-0.037698,0.281472,-0.170756,0.289937,0.022665,1.537911,2.264077,-0.760939,2,32,0,1,2,0
41,Ambiente y Desarrollo Sostenible,Corporación Autónoma,Descentralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,1,1,2,1,-0.003794,-0.450302,0.011637,0.014974,0.160415,-1.318242,-0.187274,1.544792,-0.193684,0.173967,-0.088692,-0.440738,0.323590,-0.059955,0.138974,0.447464,-0.211076,-0.780021,-0.057436,0.029708,0.115563,-0.544655,0.306729,-0.285933,0.187102,0.155016,0.334765,-0.009011,-0.171667,0.082530,0.032346,0.086452,0.199511,0.209665,0.042262,1.141662,0.357170,-0.219113,2,41,1,1,2,1

In [212]:
df_onehot=pd.concat([pd.get_dummies(df0.loc[:,cuals+[cuant+'_q' for cuant in cuants]],drop_first=False),pd.get_dummies(df0.loc[:,binarias],drop_first=True)],axis=1)
df_onehot.head()

,sector_Ambiente y Desarrollo Sostenible,sector_Ciencia Tecnología,sector_Cultura,sector_Educación Nacional,sector_Hacienda y Crédito Público,sector_Inclusión Social y Reconciliación,sector_Industria,sector_Información Estadística,sector_Inteligencia Estratégica y Contrainteligencia,sector_Ley de Justicia,sector_Minas y Energía,sector_No aplica/No pertenece,sector_Planeación,sector_Presidencia de la República,sector_Relaciones Exteriores,sector_Salud y Protección Social,sector_Servicio Público,sector_Tecnologías de la Información y las Comunicaciones,sector_Trabajo,sector_Transporte,"sector_Vivienda, Ciudad y Territorio",sector_agricultura,sector_defensa,sector_deportes,sector_interior,rama_Corporación Autónoma,rama_Ejecutivo,rama_Judicial,rama_Legislativo,tipo_contrato_Acuerdo Marco de Precios,tipo_contrato_Arrendamiento de inmuebles,tipo_contrato_Arrendamiento de muebles,tipo_contrato_Comodato,tipo_contrato_Compraventa,tipo_contrato_Consultoría,tipo_contrato_Decreto 092 de 2017,tipo_contrato_Interventoría,tipo_contrato_Obra,tipo_contrato_Otro,tipo_contrato_Prestación de servicios,tipo_contrato_Seguros,tipo_contrato_Servicios financieros,tipo_contrato_Suministros,modalidad_contratacion_Concurso de méritos abierto,modalidad_contratacion_Contratación Directa (con ofertas),modalidad_contratacion_Contratación directa,modalidad_contratacion_Contratación régimen especial,modalidad_contratacion_Contratación régimen especial (con ofertas),modalidad_contratacion_Licitación Pública Acuerdo Marco de Precios,modalidad_contratacion_Licitación pública,modalidad_contratacion_Mínima cuantía,modalidad_contratacion_Seleccion Abreviada Menor Cuantia Sin Manifestacion Interes,modalidad_contratacion_Selección Abreviada de Menor Cuantía,modalidad_contratacion_Selección abreviada subasta inversa,dias_espera_inicio_q_0,dias_espera_inicio_q_1,dias_espera_inicio_q_2,duracion_contrato_q_0,duracion_contrato_q_1,duracion_contrato_q_2,duracion_contrato_q_3,dias_desde_primer_contrato_q_0,dias_desde_primer_contrato_q_1,dias_desde_primer_contrato_q_2,dias_desde_primer_contrato_q_3,valor_contratoo_q_0,valor_contratoo_q_1,valor_contratoo_q_2,valor_contratoo_q_3,centralizada_Descentralizada,grupo_Si,pime_Si,pago_adelantado_Si,liquidacion_Si,obligacion_ambiente_Si,obligacion_postconsumo_Si,estado_bpin_Válido,prorrogado_Si,postconflicto_Si
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
41,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False

In [213]:
df_onehot.sum(axis=0)/df_onehot.shape[0]

sector_Ambiente y Desarrollo Sostenible                                               0.041365
sector_Ciencia Tecnología                                                             0.002511
sector_Cultura                                                                        0.025558
sector_Educación Nacional                                                             0.056434
sector_Hacienda y Crédito Público                                                     0.012557
sector_Inclusión Social y Reconciliación                                              0.023785
sector_Industria                                                                      0.009307
sector_Información Estadística                                                        0.030728
sector_Inteligencia Estratégica y Contrainteligencia                                  0.000295
sector_Ley de Justicia                                                                0.015512
sector_Minas y Energía                                                                0.006648
sector_No aplica/No pertenece                                                         0.156596
sector_Planeación                                                                     0.011819
sector_Presidencia de la República                                                    0.004875
sector_Relaciones Exteriores                                                          0.000295
sector_Salud y Protección Social                                                      0.151573
sector_Servicio Público                                                               0.252770
sector_Tecnologías de la Información y las Comunicaciones                             0.006057
sector_Trabajo                                                                        0.050229
sector_Transporte                                                                     0.029251
sector_Vivienda, Ciudad y Territorio                                                  0.012705
sector_agricultura                                                                    0.026296
sector_defensa                                                                        0.026001
sector_deportes                                                                       0.041217
sector_interior                                                                       0.005614
rama_Corporación Autónoma                                                             0.172256
rama_Ejecutivo                                                                        0.813119
rama_Judicial                                                                         0.006796
rama_Legislativo                                                                      0.007830
tipo_contrato_Acuerdo Marco de Precios                                                0.000148
tipo_contrato_Arrendamiento de inmuebles                                              0.007534
tipo_contrato_Arrendamiento de muebles                                                0.000739
tipo_contrato_Comodato                                                                0.001477
tipo_contrato_Compraventa                                                             0.018023
tipo_contrato_Consultoría                                                             0.001034
tipo_contrato_Decreto 092 de 2017                                                     0.036933
tipo_contrato_Interventoría                                                           0.001625
tipo_contrato_Obra                                                                    0.006205
tipo_contrato_Otro                                                                    0.040922
tipo_contrato_Prestación de servicios                                                 0.855075
tipo_contrato_Seguros                                                                 0.002955
tipo_contrato_Servicios financieros                                                   0.000739
tipo_contrato_Suministros                                                             0.026592
modalidad_contratacion_Concurso de méritos abierto                                    0.001625
modalidad_contratacion_Contratación Directa (con ofertas)                             0.010194
modalidad_contratacion_Contratación directa                                           0.752253
modalidad_contratacion_Contratación régimen especial                                  0.152755
modalidad_contratacion_Contratación régimen especial (con ofertas)                    0.007830
modalidad_contratacion_Licitación Pública Acuerdo Marco de Precios                    0.000148
modalidad_contratacion_Licitación pública                                             0.001625
modalidad_contratacion_Mínima cuantía                                                 0.056286
modalidad_contratacion_Seleccion Abreviada Menor Cuantia Sin Manifestacion Interes    0.000148
modalidad_contratacion_Selección Abreviada de Menor Cuantía                           0.008421
modalidad_contratacion_Selección abreviada subasta inversa                            0.008716
dias_espera_inicio_q_0                                                                0.329886
dias_espera_inicio_q_1                                                                0.391786
dias_espera_inicio_q_2                                                                0.278328
duracion_contrato_q_0                                                                 0.241395
duracion_contrato_q_1                                                                 0.252770
duracion_contrato_q_2                                                                 0.260452
duracion_contrato_q_3                                                                 0.245383
dias_desde_primer_contrato_q_0                                                        0.245827
dias_desde_primer_contrato_q_1                                                        0.245531
dias_desde_primer_contrato_q_2                                                        0.250997
dias_desde_primer_contrato_q_3                                                        0.257645
valor_contratoo_q_0                                                                   0.237849
valor_contratoo_q_1                                                                   0.253509
valor_contratoo_q_2                                                                   0.252622
valor_contratoo_q_3                                                                   0.256020
centralizada_Descentralizada                                                          0.171517
grupo_Si                                                                              0.003841
pime_Si                                                                               0.147585
pago_adelantado_Si                                                                    0.001182
liquidacion_Si                                                                        0.121731
obligacion_ambiente_Si                                                                0.028808
obligacion_postconsumo_Si                                                             0.000591
estado_bpin_Válido                                                                    0.527257
prorrogado_Si                                                                         0.150835
postconflicto_Si                                                                      0.005023
dtype: float64

In [214]:
cumplen=(df_onehot.sum(axis=0)/df_onehot.shape[0]>0.1) & (df_onehot.sum(axis=0)/df_onehot.shape[0]<0.9)
df_onehot=df_onehot.loc[:,cumplen]
df_onehot.head()

,sector_No aplica/No pertenece,sector_Salud y Protección Social,sector_Servicio Público,rama_Corporación Autónoma,rama_Ejecutivo,tipo_contrato_Prestación de servicios,modalidad_contratacion_Contratación directa,modalidad_contratacion_Contratación régimen especial,dias_espera_inicio_q_0,dias_espera_inicio_q_1,dias_espera_inicio_q_2,duracion_contrato_q_0,duracion_contrato_q_1,duracion_contrato_q_2,duracion_contrato_q_3,dias_desde_primer_contrato_q_0,dias_desde_primer_contrato_q_1,dias_desde_primer_contrato_q_2,dias_desde_primer_contrato_q_3,valor_contratoo_q_0,valor_contratoo_q_1,valor_contratoo_q_2,valor_contratoo_q_3,centralizada_Descentralizada,pime_Si,liquidacion_Si,estado_bpin_Válido,prorrogado_Si
1,False,False,False,False,True,True,True,False,True,False,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,True,False
2,False,True,False,False,True,True,False,True,True,False,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,True
16,False,False,True,False,True,True,True,False,True,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,True,False
32,False,False,True,False,True,True,True,False,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False
41,False,False,False,True,False,True,True,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False

### 4.3.1 MINERÍA DE ITEMSETS FRECUENTES

In [215]:
freqitems = apriori(df_onehot, min_support=0.08, use_colnames=True)
freqitems.sort_values('support',ascending=True)

      support                                           itemsets
155  0.080071  frozenset({centralizada_Descentralizada, estad...
39   0.080219  frozenset({sector_Servicio Público, dias_esper...
127  0.080514  frozenset({dias_desde_primer_contrato_q_1, dia...
384  0.080662  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
210  0.080662  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
214  0.081253  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
115  0.081253  frozenset({dias_espera_inicio_q_1, duracion_co...
401  0.081401  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
160  0.081548  frozenset({tipo_contrato_Prestación de servici...
279  0.081548  frozenset({tipo_contrato_Prestación de servici...
275  0.081548  frozenset({tipo_contrato_Prestación de servici...
385  0.081548  frozenset({rama_Ejecutivo, modalidad_contratac...
356  0.081844  frozenset({dias_espera_inicio_q_1, tipo_contra...
422  0.082435  frozenset({tipo_contrato_Prestación de servici...
111  0.082435  frozenset({dias_espera_inicio_q_0, dias_desde_...
370  0.082582  frozenset({tipo_contrato_Prestación de servici...
207  0.082582  frozenset({rama_Ejecutivo, prorrogado_Si, moda...
266  0.082730  frozenset({dias_espera_inicio_q_1, tipo_contra...
364  0.083026  frozenset({tipo_contrato_Prestación de servici...
432  0.083173  frozenset({tipo_contrato_Prestación de servici...
354  0.083173  frozenset({dias_espera_inicio_q_1, tipo_contra...
265  0.083616  frozenset({dias_desde_primer_contrato_q_1, tip...
315  0.083616  frozenset({valor_contratoo_q_3, modalidad_cont...
147  0.083764  frozenset({valor_contratoo_q_1, dias_desde_pri...
436  0.083764  frozenset({dias_espera_inicio_q_1, tipo_contra...
35   0.083912  frozenset({dias_espera_inicio_q_0, sector_Salu...
158  0.083912  frozenset({rama_Ejecutivo, sector_No aplica/No...
405  0.084060  frozenset({dias_espera_inicio_q_1, tipo_contra...
208  0.084060  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
433  0.084355  frozenset({dias_espera_inicio_q_1, tipo_contra...
413  0.084503  frozenset({tipo_contrato_Prestación de servici...
381  0.084503  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
211  0.084651  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
137  0.084651  frozenset({valor_contratoo_q_1, duracion_contr...
439  0.084798  frozenset({tipo_contrato_Prestación de servici...
259  0.084946  frozenset({tipo_contrato_Prestación de servici...
85   0.085094  frozenset({tipo_contrato_Prestación de servici...
386  0.085094  frozenset({duracion_contrato_q_1, rama_Ejecuti...
361  0.085094  frozenset({tipo_contrato_Prestación de servici...
374  0.085980  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
426  0.085980  frozenset({tipo_contrato_Prestación de servici...
109  0.086276  frozenset({dias_espera_inicio_q_0, dias_desde_...
332  0.086423  frozenset({dias_espera_inicio_q_1, sector_Serv...
325  0.086423  frozenset({valor_contratoo_q_0, duracion_contr...
453  0.086571  frozenset({tipo_contrato_Prestación de servici...
403  0.086571  frozenset({dias_espera_inicio_q_1, tipo_contra...
407  0.086867  frozenset({dias_espera_inicio_q_1, tipo_contra...
108  0.087014  frozenset({duracion_contrato_q_1, dias_espera_...
327  0.087014  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
296  0.087162  frozenset({dias_espera_inicio_q_1, duracion_co...
411  0.087310  frozenset({tipo_contrato_Prestación de servici...
441  0.087458  frozenset({tipo_contrato_Prestación de servici...
326  0.087458  frozenset({valor_contratoo_q_3, duracion_contr...
141  0.087753  frozenset({dias_desde_primer_contrato_q_1, dur...
330  0.087753  frozenset({dias_espera_inicio_q_1, sector_Serv...
388  0.087753  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
215  0.087901  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
110  0.087901  frozenset({dias_espera_inicio_q_0, dias_desde_...
300  0.088048  frozenset({dias_espera_inicio_q_1, valor_contr...
306  0.088344  frozenset({modalidad_contratacion_Contratación...
298  0.088344  frozenset({dias_espera_inicio_q_1, modalidad_c...
362  0.088935  frozenset({tipo_contrato_Prestación de servici...
230  0.088935  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
269  0.088935  frozenset({dias_espera_inicio_q_1, tipo_contra...
258  0.089083  frozenset({tipo_contrato_Prestación de servici...
257  0.089083  frozenset({tipo_contrato_Prestación de servici...
121  0.089083  frozenset({dias_espera_inicio_q_1, dias_desde_...
408  0.089230  frozenset({dias_espera_inicio_q_1, tipo_contra...
319  0.089526  frozenset({valor_contratoo_q_0, modalidad_cont...
365  0.089969  frozenset({valor_contratoo_q_2, tipo_contrato_...
334  0.090117  frozenset({dias_espera_inicio_q_1, sector_Serv...
404  0.090264  frozenset({dias_espera_inicio_q_1, tipo_contra...
301  0.090412  frozenset({dias_espera_inicio_q_1, modalidad_c...
222  0.090560  frozenset({duracion_contrato_q_1, rama_Ejecuti...
416  0.090708  frozenset({tipo_contrato_Prestación de servici...
31   0.090855  frozenset({sector_No aplica/No pertenece, esta...
212  0.091003  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
133  0.091151  frozenset({duracion_contrato_q_1, dias_desde_p...
297  0.091299  frozenset({dias_espera_inicio_q_1, modalidad_c...
216  0.091446  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
304  0.091594  frozenset({modalidad_contratacion_Contratación...
120  0.091742  frozenset({dias_desde_primer_contrato_q_1, dia...
431  0.091889  frozenset({tipo_contrato_Prestación de servici...
443  0.092185  frozenset({tipo_contrato_Prestación de servici...
168  0.092333  frozenset({dias_espera_inicio_q_1, sector_Serv...
225  0.092333  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
224  0.092776  frozenset({rama_Ejecutivo, dias_desde_primer_c...
261  0.092776  frozenset({dias_espera_inicio_q_1, tipo_contra...
309  0.092776  frozenset({modalidad_contratacion_Contratación...
274  0.092924  frozenset({tipo_contrato_Prestación de servici...
128  0.093071  frozenset({dias_espera_inicio_q_2, valor_contr...
444  0.093219  frozenset({tipo_contrato_Prestación de servici...
105  0.093219  frozenset({prorrogado_Si, modalidad_contrataci...
285  0.093219  frozenset({tipo_contrato_Prestación de servici...
390  0.093219  frozenset({rama_Ejecutivo, modalidad_contratac...
106  0.093367  frozenset({dias_espera_inicio_q_0, modalidad_c...
267  0.093367  frozenset({dias_espera_inicio_q_1, tipo_contra...
379  0.093367  frozenset({tipo_contrato_Prestación de servici...
359  0.093662  frozenset({tipo_contrato_Prestación de servici...
166  0.093662  frozenset({dias_espera_inicio_q_1, sector_Serv...
412  0.093810  frozenset({tipo_contrato_Prestación de servici...
113  0.093958  frozenset({valor_contratoo_q_1, dias_espera_in...
163  0.094253  frozenset({dias_espera_inicio_q_1, sector_Serv...
355  0.094401  frozenset({dias_espera_inicio_q_1, tipo_contra...
234  0.094401  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
449  0.094549  frozenset({tipo_contrato_Prestación de servici...
46   0.095140  frozenset({rama_Ejecutivo, modalidad_contratac...
305  0.095287  frozenset({valor_contratoo_q_0, duracion_contr...
406  0.095731  frozenset({dias_espera_inicio_q_1, tipo_contra...
400  0.095731  frozenset({rama_Ejecutivo, modalidad_contratac...
123  0.096469  frozenset({dias_espera_inicio_q_1, valor_contr...
299  0.096765  frozenset({dias_espera_inicio_q_1, modalidad_c...
122  0.097208  frozenset({dias_espera_inicio_q_1, dias_desde_...
213  0.097208  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
116  0.097356  frozenset({dias_espera_inicio_q_1, duracion_co...
68   0.097947  frozenset({tipo_contrato_Prestación de servici...
263  0.097947  frozenset({dias_espera_inicio_q_1, tipo_contra...
391  0.098242  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
262  0.098242  frozenset({dias_espera_inicio_q_1, tipo_contra...
268  0.098537  frozenset({dias_espera_inicio_q_1, tipo_contra...
360  0.098685  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
450  0.098833  frozenset({tipo_contrato_Prestación de servici...
397  0.099867  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
375  0.099867  frozenset({tipo_contrato_Prestación de servici...
376  0.100163  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
40   0.100310  frozenset({dias_espera_inicio_q_1, sector_Serv...
64   0.100606        frozenset({rama_Ejecutivo, liquidacion_Si})
294  0.100753  frozenset({tipo_contrato_Prestación de servici...
278  0.100901  frozenset({tipo_contrato_Prestación de servici...
396  0.101049  frozenset({modalidad_contratacion_Contratación...
448  0.101049  frozenset({tipo_contrato_Prestación de servici...
351  0.101492  frozenset({tipo_contrato_Prestación de servici...
144  0.101640  frozenset({valor_contratoo_q_3, dias_desde_pri...
414  0.101640  frozenset({duracion_contrato_q_1, valor_contra...
324  0.101640  frozenset({modalidad_contratacion_Contratación...
307  0.101935  frozenset({duracion_contrato_q_1, modalidad_co...
419  0.102083  frozenset({tipo_contrato_Prestación de servici...
170  0.102083  frozenset({tipo_contrato_Prestación de servici...
435  0.102378  frozenset({tipo_contrato_Prestación de servici...
236  0.102822  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
417  0.102969  frozenset({valor_contratoo_q_2, tipo_contrato_...
107  0.103117  frozenset({dias_espera_inicio_q_0, duracion_co...
312  0.103265  frozenset({modalidad_contratacion_Contratación...
310  0.103560  frozenset({valor_contratoo_q_2, modalidad_cont...
289  0.103560  frozenset({tipo_contrato_Prestación de servici...
427  0.104151  frozenset({tipo_contrato_Prestación de servici...
205  0.104151  frozenset({centralizada_Descentralizada, rama_...
395  0.104299  frozenset({rama_Ejecutivo, modalidad_contratac...
117  0.104447  frozenset({dias_espera_inicio_q_1, duracion_co...
353  0.104447  frozenset({tipo_contrato_Prestación de servici...
328  0.104594  frozenset({tipo_contrato_Prestación de servici...
189  0.104594  frozenset({tipo_contrato_Prestación de servici...
373  0.105333  frozenset({tipo_contrato_Prestación de servici...
367  0.105629  frozenset({tipo_contrato_Prestación de servici...
43   0.105629  frozenset({rama_Corporación Autónoma, modalida...
124  0.105629  frozenset({dias_espera_inicio_q_1, valor_contr...
368  0.105776  frozenset({tipo_contrato_Prestación de servici...
221  0.106072  frozenset({rama_Ejecutivo, duracion_contrato_q...
380  0.106367  frozenset({rama_Ejecutivo, modalidad_contratac...
445  0.107254  frozenset({tipo_contrato_Prestación de servici...
447  0.107401  frozenset({tipo_contrato_Prestación de servici...
32   0.107549  frozenset({rama_Ejecutivo, sector_Salud y Prot...
428  0.107845  frozenset({tipo_contrato_Prestación de servici...
280  0.108140  frozenset({valor_contratoo_q_2, tipo_contrato_...
157  0.108436  frozenset({rama_Ejecutivo, sector_No aplica/No...
118  0.108731  frozenset({dias_espera_inicio_q_1, duracion_co...
402  0.108879  frozenset({tipo_contrato_Prestación de servici...
321  0.108879  frozenset({valor_contratoo_q_0, modalidad_cont...
420  0.109026  frozenset({tipo_contrato_Prestación de servici...
276  0.109174  frozenset({duracion_contrato_q_1, valor_contra...
394  0.109322  frozenset({dias_desde_primer_contrato_q_1, ram...
369  0.109322  frozenset({tipo_contrato_Prestación de servici...
264  0.109617  frozenset({dias_espera_inicio_q_1, tipo_contra...
227  0.109765  frozenset({rama_Ejecutivo, duracion_contrato_q...
339  0.109913  frozenset({tipo_contrato_Prestación de servici...
291  0.109913  frozenset({tipo_contrato_Prestación de servici...
33   0.110356  frozenset({tipo_contrato_Prestación de servici...
290  0.110504  frozenset({tipo_contrato_Prestación de servici...
452  0.110651  frozenset({tipo_contrato_Prestación de servici...
125  0.110799  frozenset({dias_espera_inicio_q_1, valor_contr...
372  0.110799  frozenset({dias_desde_primer_contrato_q_1, tip...
156  0.110799  frozenset({tipo_contrato_Prestación de servici...
425  0.110947  frozenset({tipo_contrato_Prestación de servici...
320  0.111095  frozenset({modalidad_contratacion_Contratación...
392  0.111981  frozenset({rama_Ejecutivo, modalidad_contratac...
34   0.112129  frozenset({modalidad_contratacion_Contratación...
220  0.112129  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
134  0.112129  frozenset({duracion_contrato_q_1, valor_contra...
112  0.112277  frozenset({valor_contratoo_q_0, dias_espera_in...
399  0.112424  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
260  0.112424  frozenset({tipo_contrato_Prestación de servici...
138  0.112572  frozenset({valor_contratoo_q_2, duracion_contr...
151  0.112720  frozenset({valor_contratoo_q_0, estado_bpin_Vá...
295  0.113015  frozenset({modalidad_contratacion_Contratación...
421  0.113015  frozenset({tipo_contrato_Prestación de servici...
136  0.113163  frozenset({dias_desde_primer_contrato_q_2, dur...
272  0.113754  frozenset({tipo_contrato_Prestación de servici...
119  0.113754  frozenset({dias_espera_inicio_q_1, dias_desde_...
318  0.114197  frozenset({modalidad_contratacion_Contratación...
378  0.114788  frozenset({valor_contratoo_q_2, tipo_contrato_...
132  0.115083  frozenset({duracion_contrato_q_0, estado_bpin_...
424  0.115083  frozenset({dias_desde_primer_contrato_q_1, tip...
440  0.115231  frozenset({tipo_contrato_Prestación de servici...
149  0.115527  frozenset({valor_contratoo_q_0, dias_desde_pri...
446  0.115822  frozenset({tipo_contrato_Prestación de servici...
193  0.115822  frozenset({rama_Ejecutivo, duracion_contrato_q...
313  0.116265  frozenset({valor_contratoo_q_3, modalidad_cont...
288  0.116265  frozenset({tipo_contrato_Prestación de servici...
284  0.116413  frozenset({tipo_contrato_Prestación de servici...
393  0.116856  frozenset({rama_Ejecutivo, modalidad_contratac...
317  0.117004  frozenset({dias_desde_primer_contrato_q_1, mod...
371  0.117152  frozenset({tipo_contrato_Prestación de servici...
363  0.117152  frozenset({tipo_contrato_Prestación de servici...
209  0.117152  frozenset({rama_Ejecutivo, dias_espera_inicio_...
387  0.117743  frozenset({modalidad_contratacion_Contratación...
63   0.118186               frozenset({rama_Ejecutivo, pime_Si})
314  0.118186  frozenset({modalidad_contratacion_Contratación...
233  0.118334  frozenset({rama_Ejecutivo, dias_desde_primer_c...
442  0.118629  frozenset({tipo_contrato_Prestación de servici...
255  0.118629  frozenset({tipo_contrato_Prestación de servici...
287  0.119515  frozenset({dias_desde_primer_contrato_q_1, tip...
282  0.119663  frozenset({tipo_contrato_Prestación de servici...
219  0.119663  frozenset({rama_Ejecutivo, duracion_contrato_q...
430  0.119811  frozenset({valor_contratoo_q_2, tipo_contrato_...
389  0.120254  frozenset({modalidad_contratacion_Contratación...
66   0.120993         frozenset({rama_Ejecutivo, prorrogado_Si})
231  0.121288  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
103  0.121436  frozenset({centralizada_Descentralizada, modal...
273  0.121436  frozenset({tipo_contrato_Prestación de servici...
238  0.121584  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
323  0.121584  frozenset({valor_contratoo_q_2, modalidad_cont...
366  0.121584  frozenset({tipo_contrato_Prestación de servici...
25   0.121731                        frozenset({liquidacion_Si})
232  0.122027  frozenset({dias_desde_primer_contrato_q_1, ram...
423  0.122322  frozenset({tipo_contrato_Prestación de servici...
451  0.122766  frozenset({tipo_contrato_Prestación de servici...
350  0.122913  frozenset({tipo_contrato_Prestación de servici...
159  0.123209  frozenset({tipo_contrato_Prestación de servici...
398  0.123504  frozenset({modalidad_contratacion_Contratación...
316  0.123504  frozenset({modalidad_contratacion_Contratación...
229  0.123504  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
235  0.124538  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
286  0.124538  frozenset({tipo_contrato_Prestación de servici...
223  0.124686  frozenset({rama_Ejecutivo, duracion_contrato_q...
377  0.124834  frozenset({tipo_contrato_Prestación de servici...
293  0.124982  frozenset({valor_contratoo_q_2, tipo_contrato_...
228  0.124982  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
140  0.125572  frozenset({duracion_contrato_q_3, dias_desde_p...
438  0.125720  frozenset({tipo_contrato_Prestación de servici...
114  0.125868  frozenset({dias_espera_inicio_q_0, estado_bpin...
283  0.126754  frozenset({tipo_contrato_Prestación de servici...
415  0.127493  frozenset({tipo_contrato_Prestación de servici...
418  0.127493  frozenset({tipo_contrato_Prestación de servici...
28   0.128232  frozenset({rama_Ejecutivo, sector_No aplica/No...
237  0.128379  frozenset({rama_Ejecutivo, valor_contratoo_q_1...
30   0.128527  frozenset({sector_No aplica/No pertenece, moda...
145  0.129118  frozenset({estado_bpin_Válido, dias_desde_prim...
311  0.129266  frozenset({modalidad_contratacion_Contratación...
87   0.129857  frozenset({tipo_contrato_Prestación de servici...
277  0.129857  frozenset({tipo_contrato_Prestación de servici...
148  0.129857  frozenset({dias_desde_primer_contrato_q_2, est...
308  0.130004  frozenset({modalidad_contratacion_Contratación...
187  0.131334  frozenset({tipo_contrato_Prestación de servici...
146  0.131334  frozenset({dias_desde_primer_contrato_q_1, est...
281  0.131629  frozenset({tipo_contrato_Prestación de servici...
383  0.131777  frozenset({modalidad_contratacion_Contratación...
143  0.131777  frozenset({estado_bpin_Válido, duracion_contra...
153  0.131777  frozenset({valor_contratoo_q_2, estado_bpin_Vá...
226  0.131925  frozenset({rama_Ejecutivo, duracion_contrato_q...
358  0.132368  frozenset({tipo_contrato_Prestación de servici...
243  0.132368  frozenset({tipo_contrato_Prestación de servici...
429  0.132959  frozenset({tipo_contrato_Prestación de servici...
239  0.133402  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
434  0.133550  frozenset({tipo_contrato_Prestación de servici...
322  0.133698  frozenset({modalidad_contratacion_Contratación...
410  0.134436  frozenset({tipo_contrato_Prestación de servici...
204  0.134732  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
292  0.135175  frozenset({tipo_contrato_Prestación de servici...
29   0.135175  frozenset({tipo_contrato_Prestación de servici...
150  0.136948  frozenset({estado_bpin_Válido, dias_desde_prim...
346  0.137539  frozenset({tipo_contrato_Prestación de servici...
135  0.137834  frozenset({duracion_contrato_q_1, estado_bpin_...
91   0.138277  frozenset({duracion_contrato_q_0, modalidad_co...
333  0.138573  frozenset({sector_Servicio Público, rama_Ejecu...
152  0.138868  frozenset({valor_contratoo_q_1, estado_bpin_Vá...
331  0.139607  frozenset({sector_Servicio Público, rama_Ejecu...
335  0.140050  frozenset({sector_Servicio Público, modalidad_...
303  0.140493  frozenset({modalidad_contratacion_Contratación...
131  0.140937  frozenset({valor_contratoo_q_0, duracion_contr...
347  0.141232  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
271  0.142266  frozenset({tipo_contrato_Prestación de servici...
139  0.142562  frozenset({duracion_contrato_q_2, estado_bpin_...
175  0.143448  frozenset({tipo_contrato_Prestación de servici...
154  0.143891  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
42   0.144334  frozenset({tipo_contrato_Prestación de servici...
169  0.145073  frozenset({sector_Servicio Público, modalidad_...
254  0.145221  frozenset({tipo_contrato_Prestación de servici...
167  0.146255  frozenset({sector_Servicio Público, tipo_contr...
130  0.146550  frozenset({duracion_contrato_q_0, dias_desde_p...
62   0.146846  frozenset({rama_Ejecutivo, centralizada_Descen...
24   0.147585                               frozenset({pime_Si})
201  0.148176  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
200  0.148176  frozenset({rama_Ejecutivo, modalidad_contratac...
186  0.149062  frozenset({tipo_contrato_Prestación de servici...
342  0.150687  frozenset({tipo_contrato_Prestación de servici...
27   0.150835                         frozenset({prorrogado_Si})

In [216]:
freqitems =fpgrowth(df_onehot, min_support=0.08, use_colnames=True)
freqitems.sort_values('support',ascending=True).head(50)

      support                                           itemsets
392  0.080071  frozenset({centralizada_Descentralizada, estad...
275  0.080219  frozenset({sector_Servicio Público, dias_esper...
169  0.080514  frozenset({dias_desde_primer_contrato_q_1, dia...
344  0.080662  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
214  0.080662  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
247  0.081253  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
301  0.081253  frozenset({dias_espera_inicio_q_1, duracion_co...
130  0.081401  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
270  0.081548  frozenset({tipo_contrato_Prestación de servici...
316  0.081548  frozenset({rama_Ejecutivo, modalidad_contratac...
222  0.081548  frozenset({tipo_contrato_Prestación de servici...
359  0.081548  frozenset({tipo_contrato_Prestación de servici...
434  0.081844  frozenset({dias_espera_inicio_q_1, tipo_contra...
233  0.082435  frozenset({dias_espera_inicio_q_0, dias_desde_...
95   0.082435  frozenset({tipo_contrato_Prestación de servici...
94   0.082582  frozenset({tipo_contrato_Prestación de servici...
228  0.082582  frozenset({rama_Ejecutivo, prorrogado_Si, moda...
246  0.082730  frozenset({dias_espera_inicio_q_1, tipo_contra...
370  0.083026  frozenset({tipo_contrato_Prestación de servici...
139  0.083173  frozenset({tipo_contrato_Prestación de servici...
143  0.083173  frozenset({dias_espera_inicio_q_1, tipo_contra...
182  0.083616  frozenset({dias_desde_primer_contrato_q_1, tip...
93   0.083616  frozenset({valor_contratoo_q_3, modalidad_cont...
102  0.083764  frozenset({dias_espera_inicio_q_1, tipo_contra...
353  0.083764  frozenset({valor_contratoo_q_1, dias_desde_pri...
221  0.083912  frozenset({dias_espera_inicio_q_0, sector_Salu...
446  0.083912  frozenset({rama_Ejecutivo, sector_No aplica/No...
192  0.084060  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
144  0.084060  frozenset({dias_espera_inicio_q_1, tipo_contra...
294  0.084355  frozenset({dias_espera_inicio_q_1, tipo_contra...
315  0.084503  frozenset({tipo_contrato_Prestación de servici...
101  0.084503  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
159  0.084651  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
254  0.084651  frozenset({valor_contratoo_q_1, duracion_contr...
341  0.084798  frozenset({tipo_contrato_Prestación de servici...
266  0.084946  frozenset({tipo_contrato_Prestación de servici...
340  0.085094  frozenset({rama_Ejecutivo, duracion_contrato_q...
452  0.085094  frozenset({tipo_contrato_Prestación de servici...
314  0.085094  frozenset({tipo_contrato_Prestación de servici...
201  0.085980  frozenset({tipo_contrato_Prestación de servici...
200  0.085980  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
78   0.086276  frozenset({dias_espera_inicio_q_0, dias_desde_...
199  0.086423  frozenset({valor_contratoo_q_0, duracion_contr...
293  0.086423  frozenset({dias_espera_inicio_q_1, sector_Serv...
345  0.086571  frozenset({dias_espera_inicio_q_1, tipo_contra...
70   0.086571  frozenset({tipo_contrato_Prestación de servici...
269  0.086867  frozenset({dias_espera_inicio_q_1, tipo_contra...
320  0.087014  frozenset({duracion_contrato_q_1, dias_espera_...
125  0.087014  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
343  0.087162  frozenset({dias_espera_inicio_q_1, duracion_co...

In [217]:
freqitems.shape

(454, 2)

### 4.3.2 MINERÍA DE REGLAS DE ASOCIACIÓN

In [218]:
rules = association_rules(freqitems, metric="lift", min_threshold=1.5)

rules.loc[:, "pearson"] = rules["leverage"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"] *
    (1 - rules["antecedent support"]) * (1 - rules["consequent support"])
)

rules.loc[:, "cosine"] = rules["support"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"]
)

rules.loc[:, "jaccard"] = rules["support"] / (
    rules["antecedent support"] + rules["consequent support"] - rules["support"]
)

rules.loc[:, "kuczynski"] = (rules["support"] / 2) * (
    1 / rules["antecedent support"] + 1 / rules["consequent support"]
)

rules.loc[:, "certainty"] = (
    rules["confidence"] - rules["consequent support"]
) / (1 - rules["consequent support"])

rules.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
0,frozenset({valor_contratoo_q_3}),frozenset({dias_desde_primer_contrato_q_0}),0.256020,0.245827,0.101640,0.396999,1.614957,1.0,0.038703,1.250701,0.511826,0.253968,0.200448,0.405230,0.205959,0.405147,0.405230
1,frozenset({dias_desde_primer_contrato_q_0}),frozenset({valor_contratoo_q_3}),0.245827,0.256020,0.101640,0.413462,1.614957,1.0,0.038703,1.268425,0.504909,0.253968,0.211621,0.405230,0.205959,0.405147,0.405230
2,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_0}),0.181858,0.245827,0.093219,0.512591,2.085175,1.0,0.048513,1.547313,0.636105,0.278710,0.353718,0.445899,0.292100,0.440883,0.445899
3,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.228099,0.256020,0.093219,0.408679,1.596276,1.0,0.034821,1.258165,0.483925,0.238473,0.205192,0.386394,0.190145,0.385750,0.386394
4,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256020,0.228099,0.093219,0.364108,1.596276,1.0,0.034821,1.213888,0.502086,0.238473,0.176201,0.386394,0.190145,0.385750,0.386394
5,frozenset({dias_desde_primer_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.245827,0.181858,0.093219,0.379207,2.085175,1.0,0.048513,1.317897,0.690059,0.278710,0.241215,0.445899,0.292100,0.440883,0.445899
6,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({dias_desde_primer_contrato_q_0}),0.210519,0.245827,0.088935,0.422456,1.718513,1.0,0.037184,1.305829,0.529590,0.242059,0.234203,0.392117,0.211830,0.390942,0.392117
7,"frozenset({rama_Ejecutivo, dias_desde_primer_c...",frozenset({valor_contratoo_q_3}),0.205200,0.256020,0.088935,0.433405,1.692857,1.0,0.036399,1.313073,0.514950,0.238889,0.238427,0.390390,0.206519,0.388013,0.390390
8,frozenset({valor_contratoo_q_3}),"frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.256020,0.205200,0.088935,0.347374,1.692857,1.0,0.036399,1.217850,0.550126,0.238889,0.178881,0.390390,0.206519,0.388013,0.390390
9,frozenset({dias_desde_primer_contrato_q_0}),"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.245827,0.210519,0.088935,0.361779,1.718513,1.0,0.037184,1.237003,0.554384,0.242059,0.191595,0.392117,0.211830,0.390942,0.392117
10,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({dias_desde_primer_contrato_q_0}),0.159699,0.245827,0.083616,0.523589,2.129913,1.0,0.044358,1.583032,0.631318,0.259752,0.368301,0.431867,0.281227,0.422014,0.431867
11,frozenset({modalidad_contratacion_Contratación...,frozenset({valor_contratoo_q_3}),0.196336,0.256020,0.083616,0.425884,1.663479,1.0,0.033350,1.295871,0.496290,0.226763,0.228318,0.376243,0.192374,0.372953,0.376243
12,frozenset({valor_contratoo_q_3}),frozenset({modalidad_contratacion_Contratación...,0.256020,0.196336,0.083616,0.326601,1.663479,1.0,0.033350,1.193444,0.536104,0.226763,0.162089,0.376243,0.192374,0.372953,0.376243
13,frozenset({dias_desde_primer_contrato_q_0}),"frozenset({valor_contratoo_q_3, modalidad_cont...",0.245827,0.159699,0.083616,0.340144,2.129913,1.0,0.044358,1.273462,0.703416,0.259752,0.214739,0.431867,0.281227,0.422014,0.431867
14,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_0}),0.149062,0.245827,0.082582,0.554014,2.253678,1.0,0.045939,1.691024,0.653727,0.264428,0.408642,0.444976,0.299571,0.431409,0.444976
15,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.193677,0.256020,0.082582,0.426392,1.665463,1.0,0.032997,1.297018,0.495541,0.224950,0.229001,0.374477,0.191322,0.370861,0.374477
16,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.181858,0.205200,0.082582,0.454102,2.212973,1.0,0.045265,1.455950,0.669956,0.271228,0.313163,0.428275,0.290579,0.427496,0.428275
17,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.228099,0.210519,0.082582,0.362047,1.719785,1.0,0.034563,1.237522,0.542209,0.231950,0.191934,0.377164,0.202049,0.376861,0.377164
18,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({tipo_contrato_Prestación de servici...,0.210519,0.228099,0.082582,0.392281,1.719785,1.0,0.034563,1.270161,0.530135,0.231950,0.212698,0.377164,0.202049,0.376861,0.377164
19,"frozenset({rama_Ejecutivo, dias_desde_primer_c...",frozenset({tipo_contrato_Prestación de servici...,0.205200,0.181858,0.082582,0.402448,2.212973,1.0,0.045265,1.369155,0.689632,0.271228,0.269622,0.428275,0.290579,0.427496,0.428275
20,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256020,0.193677,0.082582,0.322562,1.665463,1.0,0.032997,1.190254,0.537066,0.224950,0.159843,0.374477,0.191322,0.370861,0.374477
21,frozenset({dias_desde_primer_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.245827,0.149062,0.082582,0.335938,2.253678,1.0,0.045939,1.281413,0.737603,0.264428,0.219611,0.444976,0.299571,0.431409,0.444976
22,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_0}),0.145221,0.245827,0.082435,0.567650,2.309149,1.0,0.046735,1.744359,0.663259,0.267113,0.426723,0.451493,0.308074,0.436296,0.451493
23,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.194416,0.256020,0.082435,0.424012,1.656168,1.0,0.032660,1.291659,0.491812,0.224006,0.225802,0.372999,0.189096,0.369494,0.372999
24,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.181858,0.196336,0.082435,0.453290,2.308743,1.0,0.046729,1.470000,0.692868,0.278721,0.319728,0.436577,0.304979,0.436257,0.436577
25,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.228099,0.159699,0.082435,0.361399,2.263006,1.0,0.046008,1.315847,0.723033,0.269956,0.240033,0.438794,0.299308,0.431914,0.438794
26,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159699,0.228099,0.082435,0.516189,2.263006,1.0,0.046008,1.595460,0.664178,0.269956,0.373221,0.438794,0.299308,0.431914,0.438794
27,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.196336,0.181858,0.082435,0.419865,2.308743,1.0,0.046729,1.410260,0.705350,0.278721,0.290911,0.436577,0.304979,0.436257,0.436577
28,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256020,0.194416,0.082435,0.321985,1.656168,1.0,0.032660,1.188151,0.532536,0.224006,0.158356,0.372999,0.189096,0.369494,0.372999
29,frozenset({dias_desde_primer_contrato_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.245827,0.145221,0.082435,0.335337,2.309149,1.0,0.046735,1.286033,0.751737,0.267113,0.222415,0.451493,0.308074,0.436296,0.451493
30,frozenset({valor_contratoo_q_3}),frozenset({duracion_contrato_q_3}),0.256020,0.245383,0.151278,0.590883,2.407999,1.0,0.088455,1.844500,0.785932,0.432068,0.457848,0.603689,0.470997,0.603554,0.603689
31,frozenset({duracion_contrato_q_3}),frozenset({valor_contratoo_q_3}),0.245383,0.256020,0.151278,0.616496,2.407999,1.0,0.088455,1.939954,0.774854,0.432068,0.484524,0.603689,0.470997,0.603554,0.603689
32,frozenset({duracion_contrato_q_3}),frozenset({dias_desde_primer_contrato_q_0}),0.245383,0.245827,0.125572,0.511740,2.081711,1.0,0.065251,1.544614,0.688596,0.343434,0.352589,0.511279,0.352168,0.511278,0.511279
33,frozenset({dias_desde_primer_contrato_q_0}),frozenset({duracion_contrato_q_3}),0.245827,0.245383,0.125572,0.510817,2.081711,1.0,0.065251,1.542607,0.689001,0.343434,0.351747,0.511279,0.352168,0.511278,0.511279
34,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.181858,0.245383,0.126754,0.696994,2.840430,1.0,0.082129,2.490437,0.791966,0.421829,0.598464,0.606775,0.494802,0.600031,0.606775
35,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.208598,0.256020,0.126754,0.607649,2.373442,1.0,0.073349,1.896209,0.731197,0.375164,0.472632,0.551372,0.413641,0.548492,0.551372
36,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256020,0.208598,0.126754,0.495095,2.373442,1.0,0.073349,1.567428,0.777804,0.375164,0.362012,0.551372,0.413641,0.548492,0.551372
37,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.245383,0.181858,0.126754,0.516556,2.840430,1.0,0.082129,1.692320,0.858636,0.421829,0.409095,0.606775,0.494802,0.600031,0.606775
38,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({duracion_contrato_q_3}),0.210519,0.245383,0.124982,0.593684,2.419415,1.0,0.073324,1.857217,0.743117,0.377679,0.461560,0.551508,0.417968,0.549893,0.551508
39,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_3}),0.203871,0.256020,0.124982,0.613043,2.394513,1.0,0.072787,1.922645,0.731512,0.373180,0.479883,0.550607,0.413966,0.547056,0.550607
40,frozenset({valor_contratoo_q_3}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.256020,0.203871,0.124982,0.488171,2.394513,1.0,0.072787,1.555459,0.782788,0.373180,0.357103,0.550607,0.413966,0.547056,0.550607
41,frozenset({duracion_contrato_q_3}),"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.245383,0.210519,0.124982,0.509332,2.419415,1.0,0.073324,1.608992,0.777450,0.377679,0.378493,0.551508,0.417968,0.549893,0.551508
42,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({duracion_contrato_q_3}),0.159699,0.245383,0.116265,0.728030,2.966907,1.0,0.077078,2.774628,0.788942,0.402558,0.639591,0.600920,0.488963,0.587323,0.600920
43,frozenset({modalidad_contratacion_Contratación...,frozenset({valor_contratoo_q_3}),0.189393,0.256020,0.116265,0.613885,2.397798,1.0,0.067777,1.926833,0.719153,0.353232,0.481014,0.534005,0.396349,0.527997,0.534005
44,frozenset({valor_contratoo_q_3}),frozenset({modalidad_contratacion_Contratación...,0.256020,0.189393,0.116265,0.454126,2.397798,1.0,0.067777,1.484971,0.783557,0.353232,0.326586,0.534005,0.396349,0.527997,0.534005
45,frozenset({duracion_contrato_q_3}),"frozenset({valor_contratoo_q_3, modalidad_cont...",0.245383,0.159699,0.116265,0.473811,2.966907,1.0,0.077078,1.596957,0.878524,0.402558,0.373809,0.600920,0.488963,0.587323,0.600920
46,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.149062,0.245383,0.105776,0.709613,2.891856,1.0,0.069199,2.598663,0.768800,0.366428,0.615187,0.570340,0.451525,0.553073,0.570340
47,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.174767,0.256020,0.105776,0.605241,2.364037,1.0,0.061032,1.884643,0.699190,0.325455,0.469396,0.509199,0.368234,0.500059,0.509199
48,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.181858,0.203871,0.105776,0.581641,2.852991,1.0,0.068701,1.902981,0.793861,0.377836,0.474509,0.550241,0.442091,0.549344,0.550241
49,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.208598,0.210519,0.105776,0.507082,2.408729,1.0,0.061863,1.601649,0.738997,0.337577,0.375644,0.504769,0.373472,0.504764,0.504769

In [219]:
rules_sub=rules[(rules.confidence > 0.5)&(rules.zhangs_metric > 0.5)].sort_values(by='lift',ascending=False)
rules_sub.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
244,frozenset({modalidad_contratacion_Contratación...,frozenset({sector_Salud y Protección Social}),0.152755,0.151573,0.112129,0.734043,4.842821,1.0,0.088975,3.190084,0.936576,0.583397,0.686529,0.736904,0.689681,0.736899,0.736904
245,frozenset({sector_Salud y Protección Social}),frozenset({modalidad_contratacion_Contratación...,0.151573,0.152755,0.112129,0.739766,4.842821,1.0,0.088975,3.255705,0.935271,0.583397,0.692847,0.736904,0.689681,0.736899,0.736904
163,"frozenset({valor_contratoo_q_3, dias_desde_pri...",frozenset({tipo_contrato_Prestación de servici...,0.101640,0.208598,0.083173,0.818314,3.922923,1.0,0.061971,4.355876,0.829387,0.366298,0.770425,0.608520,0.504755,0.571211,0.608520
164,"frozenset({duracion_contrato_q_3, dias_desde_p...",frozenset({tipo_contrato_Prestación de servici...,0.125572,0.181858,0.083173,0.662353,3.642134,1.0,0.060337,2.423067,0.829612,0.370883,0.587300,0.559852,0.472055,0.550389,0.559852
157,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.093219,0.245383,0.083173,0.892235,3.636084,1.0,0.060299,7.002398,0.799508,0.325622,0.857192,0.615593,0.481970,0.549932,0.615593
111,"frozenset({valor_contratoo_q_3, dias_desde_pri...",frozenset({duracion_contrato_q_3}),0.101640,0.245383,0.087458,0.860465,3.506616,1.0,0.062517,5.408086,0.795699,0.336938,0.815092,0.608438,0.480788,0.553787,0.608438
73,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.174767,0.159699,0.093219,0.533390,3.339977,1.0,0.065309,1.800863,0.848969,0.386405,0.444711,0.558554,0.469447,0.557987,0.558554
82,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159699,0.174767,0.093219,0.583719,3.339977,1.0,0.065309,1.982392,0.833745,0.386405,0.495559,0.558554,0.469447,0.557987,0.558554
76,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({tipo_contrato_Prestación de servici...,0.134732,0.208598,0.093219,0.691886,3.316839,1.0,0.065114,2.568536,0.807274,0.372711,0.610673,0.569385,0.469367,0.556051,0.569385
231,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.138277,0.204757,0.093810,0.678419,3.313288,1.0,0.065497,2.472915,0.810220,0.376408,0.595619,0.568286,0.470209,0.557512,0.568286
72,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.149062,0.189393,0.093219,0.625372,3.301982,1.0,0.064988,2.163764,0.819274,0.380120,0.537842,0.558786,0.465707,0.554804,0.558786
57,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.208598,0.159699,0.109026,0.522663,3.272808,1.0,0.075714,1.760394,0.877496,0.420513,0.431945,0.602682,0.508689,0.597346,0.602682
58,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159699,0.208598,0.109026,0.682701,3.272808,1.0,0.075714,2.494185,0.826432,0.420513,0.599067,0.602682,0.508689,0.597346,0.602682
78,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, modalidad_contratac...",0.181858,0.160880,0.093219,0.512591,3.186163,1.0,0.063962,1.721594,0.838660,0.373594,0.419143,0.546011,0.451310,0.544987,0.546011
77,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({tipo_contrato_Prestación de servici...,0.160880,0.181858,0.093219,0.579431,3.186163,1.0,0.063962,1.945319,0.817694,0.373594,0.485946,0.546011,0.451310,0.544987,0.546011
59,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.189393,0.181858,0.109026,0.575663,3.165445,1.0,0.074584,1.928047,0.843921,0.415775,0.481340,0.587588,0.493488,0.587467,0.587588
56,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.181858,0.189393,0.109026,0.599513,3.165445,1.0,0.074584,2.024052,0.836150,0.415775,0.505941,0.587588,0.493488,0.587467,0.587588
74,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.145221,0.203871,0.093219,0.641913,3.148627,1.0,0.063613,2.223282,0.798336,0.364319,0.550214,0.549579,0.448161,0.541768,0.549579
274,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.138277,0.201802,0.087310,0.631410,3.128855,1.0,0.059405,2.165545,0.789575,0.345412,0.538222,0.532030,0.428791,0.522666,0.532030
185,"frozenset({valor_contratoo_q_0, dias_desde_pri...",frozenset({duracion_contrato_q_0}),0.115527,0.241395,0.086423,0.748082,3.099000,1.0,0.058536,3.011317,0.765784,0.319498,0.667919,0.553049,0.427924,0.517519,0.553049
70,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.122913,0.245383,0.093219,0.758413,3.090729,1.0,0.063058,3.123587,0.771248,0.338883,0.679855,0.569153,0.446309,0.536763,0.569153
54,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.145221,0.245383,0.109026,0.750763,3.059551,1.0,0.073392,3.027707,0.787519,0.387198,0.669717,0.597537,0.484083,0.577557,0.597537
239,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.138277,0.190722,0.080662,0.583333,3.058546,1.0,0.054289,1.942266,0.781049,0.324807,0.485138,0.503131,0.400318,0.496697,0.503131
66,"frozenset({valor_contratoo_q_3, modalidad_cont...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.159699,0.203871,0.098242,0.615171,3.017459,1.0,0.065684,2.068788,0.795661,0.370267,0.516625,0.548528,0.445065,0.544464,0.548528
230,"frozenset({valor_contratoo_q_0, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.173881,0.179790,0.093810,0.539507,3.000760,1.0,0.062548,1.781157,0.807088,0.361001,0.438567,0.530641,0.429754,0.530567,0.530641
229,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.179790,0.173881,0.093810,0.521775,3.000760,1.0,0.062548,1.727469,0.812903,0.361001,0.421118,0.530641,0.429754,0.530567,0.530641
227,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.132368,0.237849,0.093810,0.708705,2.979644,1.0,0.062326,2.616426,0.765750,0.339391,0.617799,0.551558,0.431958,0.528697,0.551558
62,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({duracion_contrato_q_3}),0.134732,0.245383,0.098242,0.729167,2.971541,1.0,0.065181,2.786277,0.766785,0.348532,0.641098,0.564764,0.443634,0.540306,0.564764
42,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({duracion_contrato_q_3}),0.159699,0.245383,0.116265,0.728030,2.966907,1.0,0.077078,2.774628,0.788942,0.402558,0.639591,0.600920,0.488963,0.587323,0.600920
95,"frozenset({estado_bpin_Válido, duracion_contra...","frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.131777,0.210519,0.081401,0.617713,2.934245,1.0,0.053659,2.065154,0.759249,0.312005,0.515775,0.502190,0.389126,0.488722,0.502190
235,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_0}),0.115822,0.237849,0.080662,0.696429,2.928028,1.0,0.053114,2.510615,0.744729,0.295455,0.601691,0.517780,0.389825,0.485984,0.517780
215,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({valor_contratoo_q_0}),0.138277,0.237849,0.095287,0.689103,2.897227,1.0,0.062398,2.451455,0.759922,0.339295,0.592079,0.544862,0.424562,0.525423,0.544862
219,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.143448,0.237849,0.098685,0.687951,2.892383,1.0,0.064566,2.442405,0.763835,0.349190,0.590567,0.551429,0.432623,0.534262,0.551429
46,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.149062,0.245383,0.105776,0.709613,2.891856,1.0,0.069199,2.598663,0.768800,0.366428,0.615187,0.570340,0.451525,0.553073,0.570340
222,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.179790,0.190722,0.098685,0.548891,2.877956,1.0,0.064395,1.793972,0.795566,0.363043,0.442578,0.533160,0.426833,0.532927,0.533160
221,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({tipo_contrato_Prestación de servici...,0.190722,0.179790,0.098685,0.517428,2.877956,1.0,0.064395,1.699664,0.806313,0.363043,0.411649,0.533160,0.426833,0.532927,0.533160
51,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.203871,0.181858,0.105776,0.518841,2.852991,1.0,0.068701,1.700354,0.815810,0.377836,0.411887,0.550241,0.442091,0.549344,0.550241
48,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.181858,0.203871,0.105776,0.581641,2.852991,1.0,0.068701,1.902981,0.793861,0.377836,0.474509,0.550241,0.442091,0.549344,0.550241
37,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.245383,0.181858,0.126754,0.516556,2.840430,1.0,0.082129,1.692320,0.858636,0.421829,0.409095,0.606775,0.494802,0.600031,0.606775
34,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.181858,0.245383,0.126754,0.696994,2.840430,1.0,0.082129,2.490437,0.791966,0.421829,0.598464,0.606775,0.494802,0.600031,0.606775
207,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.179790,0.237849,0.121436,0.675431,2.839748,1.0,0.078673,2.348197,0.789866,0.409975,0.574141,0.592995,0.481182,0.587237,0.592995
208,frozenset({valor_contratoo_q_0}),frozenset({tipo_contrato_Prestación de servici...,0.237849,0.179790,0.121436,0.510559,2.839748,1.0,0.078673,1.675809,0.850036,0.409975,0.403273,0.592995,0.481182,0.587237,0.592995
94,"frozenset({valor_contratoo_q_3, estado_bpin_Vá...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.143891,0.203871,0.081401,0.565708,2.774841,1.0,0.052065,1.833168,0.747124,0.305602,0.454496,0.482492,0.368212,0.475261,0.482492
112,"frozenset({duracion_contrato_q_3, dias_desde_p...",frozenset({valor_contratoo_q_3}),0.125572,0.256020,0.087458,0.696471,2.720375,1.0,0.055308,2.451097,0.723220,0.297338,0.592019,0.519037,0.382441,0.487768,0.519037
158,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.119663,0.256020,0.083173,0.695062,2.714872,1.0,0.052537,2.439772,0.717519,0.284343,0.590126,0.509966,0.370889,0.475189,0.509966
142,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.174767,0.196336,0.092185,0.527473,2.686578,1.0,0.057872,1.700777,0.760730,0.330508,0.412033,0.498499,0.383629,0.497657,0.498499
156,frozenset({tipo_contrato_Prestación de servici...,frozenset({dias_desde_primer_contrato_q_0}),0.126754,0.245827,0.083173,0.656177,2.669269,1.0,0.052014,2.193494,0.716139,0.287392,0.544106,0.497259,0.363093,0.471181,0.497259
87,"frozenset({estado_bpin_Válido, duracion_contra...",frozenset({valor_contratoo_q_3}),0.131777,0.256020,0.087014,0.660314,2.579149,1.0,0.053277,2.190198,0.705205,0.289293,0.543420,0.500093,0.360898,0.473733,0.500093
91,"frozenset({rama_Ejecutivo, estado_bpin_Válido,...",frozenset({valor_contratoo_q_3}),0.123504,0.256020,0.081401,0.659091,2.574372,1.0,0.049781,2.182341,0.697728,0.273043,0.541776,0.488518,0.346681,0.457772,0.488518
266,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({dias_desde_primer_contrato_q_3}),0.138277,0.257645,0.091594,0.662393,2.570951,1.0,0.055968,2.198874,0.709090,0.300971,0.545222,0.508949,0.370732,0.485267,0.508949

In [220]:
vals=[len(list(rules_sub.iloc[k,:].consequents)) == 1 for k in range(rules_sub.shape[0])]

In [221]:
np.array(vals).sum()

np.int64(88)

In [222]:
rules_sub.loc[vals,:].consequents.drop_duplicates()

244        frozenset({sector_Salud y Protección Social})
245    frozenset({modalidad_contratacion_Contratación...
157                   frozenset({duracion_contrato_q_3})
185                   frozenset({duracion_contrato_q_0})
227                     frozenset({valor_contratoo_q_0})
112                     frozenset({valor_contratoo_q_3})
156          frozenset({dias_desde_primer_contrato_q_0})
266          frozenset({dias_desde_primer_contrato_q_3})
378                   frozenset({duracion_contrato_q_2})
243                  frozenset({dias_espera_inicio_q_0})
Name: consequents, dtype: object

In [223]:
vals=[list(rules_sub.iloc[k,:].consequents) == ['duracion_contrato_q_0'] for k in range(rules_sub.shape[0])]
print(rules_sub.loc[vals,:].iloc[0,:].antecedents)
rules_sub.loc[vals,:].iloc[0,:]

frozenset({'valor_contratoo_q_0', 'dias_desde_primer_contrato_q_3'})

antecedents           frozenset({valor_contratoo_q_0, dias_desde_pri...
consequents                          frozenset({duracion_contrato_q_0})
antecedent support                                             0.115527
consequent support                                             0.241395
support                                                        0.086423
confidence                                                     0.748082
lift                                                              3.099
representativity                                                    1.0
leverage                                                       0.058536
conviction                                                     3.011317
zhangs_metric                                                  0.765784
jaccard                                                        0.319498
certainty                                                      0.667919
kulczynski                                                     0.553049
pearson                                                        0.427924
cosine                                                         0.517519
kuczynski                                                      0.553049
Name: 185, dtype: object

## 4.4 MINERÍA DE LA CLASE 3

### 4.4.0 SUBCONJUNTO Y PREPRACIÓN

In [227]:
df0=dfs.copy()[dfs.clase==3]
df0.head()

,sector,rama,centralizada,tipo_contrato,modalidad_contratacion,grupo,pime,pago_adelantado,liquidacion,obligacion_ambiente,obligacion_postconsumo,estado_bpin,postconflicto,prorrogado,dias_espera_inicio,duracion_contrato,dias_desde_primer_contrato,valor_contratoo,MCA1,MCA2,MCA3,MCA4,MCA5,MCA6,MCA7,MCA8,MCA9,MCA10,MCA11,MCA12,MCA13,MCA14,MCA15,MCA16,MCA17,MCA18,MCA19,MCA20,MCA21,MCA22,MCA23,MCA24,MCA25,MCA26,MCA27,MCA28,MCA29,MCA30,MCA31,MCA32,MCA33,MCA34,MCA35,SE1,SE2,SE3,clase,indice,dias_espera_inicio_q,duracion_contrato_q,dias_desde_primer_contrato_q,valor_contratoo_q
14,Ambiente y Desarrollo Sostenible,Corporación Autónoma,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,No,2,3,0,3,0.129805,-0.442842,0.015263,0.019625,0.146688,-1.407366,-0.168962,1.599216,-0.108490,0.129548,-0.055144,-0.402230,0.349272,-0.102312,0.164043,0.400653,-0.203536,-0.788251,-0.030020,0.027894,0.135418,-0.532851,0.307781,-0.292646,0.164645,0.167310,0.335567,-0.013272,-0.175789,0.115208,0.013700,0.110319,0.165059,0.248470,0.032868,1.466957,-1.270253,0.604457,3,14,2,3,0,3
19,Transporte,Ejecutivo,Centralizada,Obra,Contratación directa,No,No,No,Si,Si,No,Válido,No,Si,2,3,3,3,-0.111183,0.726818,-0.054001,-0.055899,0.466056,0.196426,-0.135981,0.303224,0.255181,1.401556,-0.130319,-1.397941,-0.716311,0.111667,0.385838,-1.118042,-0.334421,0.311420,-0.344544,0.023287,0.011611,0.157863,0.172594,0.109773,0.270292,-0.240390,-0.152532,-0.078040,0.104727,-0.299779,0.057525,0.007253,-0.260541,-0.031714,0.360554,1.602621,-1.940352,0.630937,3,19,2,3,3,3
29,"Vivienda, Ciudad y Territorio",Ejecutivo,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,Válido,No,No,2,0,1,0,-0.281986,-0.294440,0.011551,0.006757,0.119426,-0.063049,-0.048614,0.011249,-0.059607,0.066095,0.240529,0.273505,-0.096110,-0.195214,-0.139677,-0.174309,0.082977,-0.305554,0.081492,0.179094,-0.083223,0.020008,0.546665,2.563628,-1.323832,-0.128420,0.356478,0.068013,-0.719459,-0.025714,0.052414,0.073487,-0.296640,-0.100556,0.201403,1.806525,-1.962812,0.793963,3,29,2,0,1,0
31,Educación Nacional,Corporación Autónoma,Centralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,No,0,0,2,0,0.079415,-0.432563,0.020150,0.022008,0.013452,-1.047666,-0.110473,0.896411,0.145191,-0.040289,-0.167094,0.798808,-0.381324,-0.628761,-0.426660,-0.397626,-0.028509,1.039252,0.075334,-0.180215,-0.134792,0.249601,-0.407485,-0.121404,0.111527,-0.229936,0.063644,0.324101,-0.012738,0.076958,-0.153960,-0.063286,-0.016394,0.002442,0.108144,1.601453,-1.946982,0.637009,3,31,0,0,2,0
36,Salud y Protección Social,Ejecutivo,Descentralizada,Prestación de servicios,Contratación directa,No,No,No,No,No,No,No Válido,No,Si,0,2,0,1,0.477179,-0.371925,0.008764,0.010483,-0.003859,0.196321,-0.064273,-0.258153,-0.067814,-0.073885,-0.056396,-0.026628,0.310411,-0.001188,0.159446,-0.523528,0.192738,-0.092248,-0.094312,0.076097,0.064411,0.119318,0.043365,-0.207043,0.054160,0.060926,0.001486,0.056117,0.070264,0.015607,-0.037954,0.103874,-0.018967,0.111269,-0.091549,1.664626,-0.993948,0.376302,3,36,0,2,0,1

In [228]:
df_onehot=pd.concat([pd.get_dummies(df0.loc[:,cuals+[cuant+'_q' for cuant in cuants]],drop_first=False),pd.get_dummies(df0.loc[:,binarias],drop_first=True)],axis=1)
df_onehot.head()

,sector_Ambiente y Desarrollo Sostenible,sector_Ciencia Tecnología,sector_Cultura,sector_Educación Nacional,sector_Hacienda y Crédito Público,sector_Inclusión Social y Reconciliación,sector_Industria,sector_Información Estadística,sector_Inteligencia Estratégica y Contrainteligencia,sector_Ley de Justicia,sector_Minas y Energía,sector_No aplica/No pertenece,sector_Planeación,sector_Presidencia de la República,sector_Relaciones Exteriores,sector_Salud y Protección Social,sector_Servicio Público,sector_Tecnologías de la Información y las Comunicaciones,sector_Trabajo,sector_Transporte,"sector_Vivienda, Ciudad y Territorio",sector_agricultura,sector_defensa,sector_deportes,sector_interior,rama_Corporación Autónoma,rama_Ejecutivo,rama_Judicial,rama_Legislativo,tipo_contrato_Acuerdo Marco de Precios,tipo_contrato_Arrendamiento de inmuebles,tipo_contrato_Arrendamiento de muebles,tipo_contrato_Asociación Público Privada,tipo_contrato_Comisión,tipo_contrato_Comodato,tipo_contrato_Compraventa,tipo_contrato_Consultoría,tipo_contrato_Decreto 092 de 2017,tipo_contrato_Interventoría,tipo_contrato_Obra,tipo_contrato_Operaciones de Crédito Público,tipo_contrato_Otro,tipo_contrato_Prestación de servicios,tipo_contrato_Seguros,tipo_contrato_Servicios financieros,tipo_contrato_Suministros,modalidad_contratacion_Concurso de méritos abierto,modalidad_contratacion_Contratación Directa (con ofertas),modalidad_contratacion_Contratación directa,modalidad_contratacion_Contratación régimen especial,modalidad_contratacion_Contratación régimen especial (con ofertas),modalidad_contratacion_Licitación Pública Acuerdo Marco de Precios,modalidad_contratacion_Licitación pública,modalidad_contratacion_Licitación pública Obra Publica,modalidad_contratacion_Mínima cuantía,modalidad_contratacion_Selección Abreviada de Menor Cuantía,modalidad_contratacion_Selección abreviada subasta inversa,dias_espera_inicio_q_0,dias_espera_inicio_q_1,dias_espera_inicio_q_2,duracion_contrato_q_0,duracion_contrato_q_1,duracion_contrato_q_2,duracion_contrato_q_3,dias_desde_primer_contrato_q_0,dias_desde_primer_contrato_q_1,dias_desde_primer_contrato_q_2,dias_desde_primer_contrato_q_3,valor_contratoo_q_0,valor_contratoo_q_1,valor_contratoo_q_2,valor_contratoo_q_3,centralizada_Descentralizada,grupo_Si,pime_Si,pago_adelantado_Si,liquidacion_Si,obligacion_ambiente_Si,estado_bpin_Válido,prorrogado_Si,postconflicto_Si
14,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,True,True,True,True,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False
31,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False

In [229]:
df_onehot.sum(axis=0)/df_onehot.shape[0]

sector_Ambiente y Desarrollo Sostenible                               0.036963
sector_Ciencia Tecnología                                             0.003009
sector_Cultura                                                        0.027650
sector_Educación Nacional                                             0.052579
sector_Hacienda y Crédito Público                                     0.009599
sector_Inclusión Social y Reconciliación                              0.028080
sector_Industria                                                      0.009742
sector_Información Estadística                                        0.027937
sector_Inteligencia Estratégica y Contrainteligencia                  0.000143
sector_Ley de Justicia                                                0.014040
sector_Minas y Energía                                                0.007163
sector_No aplica/No pertenece                                         0.160888
sector_Planeación                                                     0.014613
sector_Presidencia de la República                                    0.005444
sector_Relaciones Exteriores                                          0.000287
sector_Salud y Protección Social                                      0.156447
sector_Servicio Público                                               0.256590
sector_Tecnologías de la Información y las Comunicaciones             0.006160
sector_Trabajo                                                        0.045415
sector_Transporte                                                     0.027794
sector_Vivienda, Ciudad y Territorio                                  0.015616
sector_agricultura                                                    0.027364
sector_defensa                                                        0.027794
sector_deportes                                                       0.034814
sector_interior                                                       0.003868
rama_Corporación Autónoma                                             0.173066
rama_Ejecutivo                                                        0.812178
rama_Judicial                                                         0.006304
rama_Legislativo                                                      0.008453
tipo_contrato_Acuerdo Marco de Precios                                0.000143
tipo_contrato_Arrendamiento de inmuebles                              0.006877
tipo_contrato_Arrendamiento de muebles                                0.000143
tipo_contrato_Asociación Público Privada                              0.000143
tipo_contrato_Comisión                                                0.000143
tipo_contrato_Comodato                                                0.001289
tipo_contrato_Compraventa                                             0.018481
tipo_contrato_Consultoría                                             0.002006
tipo_contrato_Decreto 092 de 2017                                     0.038252
tipo_contrato_Interventoría                                           0.001719
tipo_contrato_Obra                                                    0.007020
tipo_contrato_Operaciones de Crédito Público                          0.000143
tipo_contrato_Otro                                                    0.044986
tipo_contrato_Prestación de servicios                                 0.853438
tipo_contrato_Seguros                                                 0.002436
tipo_contrato_Servicios financieros                                   0.000143
tipo_contrato_Suministros                                             0.022636
modalidad_contratacion_Concurso de méritos abierto                    0.002292
modalidad_contratacion_Contratación Directa (con ofertas)             0.011605
modalidad_contratacion_Contratación directa                           0.749140
modalidad_contratacion_Contratación régimen especial                  0.155444
modalidad_contratacion_Contratación régimen especial (con ofertas)    0.008739
modalidad_contratacion_Licitación Pública Acuerdo Marco de Precios    0.000143
modalidad_contratacion_Licitación pública                             0.002579
modalidad_contratacion_Licitación pública Obra Publica                0.001146
modalidad_contratacion_Mínima cuantía                                 0.051003
modalidad_contratacion_Selección Abreviada de Menor Cuantía           0.009456
modalidad_contratacion_Selección abreviada subasta inversa            0.008453
dias_espera_inicio_q_0                                                0.333381
dias_espera_inicio_q_1                                                0.388109
dias_espera_inicio_q_2                                                0.278510
duracion_contrato_q_0                                                 0.243553
duracion_contrato_q_1                                                 0.245415
duracion_contrato_q_2                                                 0.255014
duracion_contrato_q_3                                                 0.256017
dias_desde_primer_contrato_q_0                                        0.247278
dias_desde_primer_contrato_q_1                                        0.250287
dias_desde_primer_contrato_q_2                                        0.254871
dias_desde_primer_contrato_q_3                                        0.247564
valor_contratoo_q_0                                                   0.258883
valor_contratoo_q_1                                                   0.233095
valor_contratoo_q_2                                                   0.254871
valor_contratoo_q_3                                                   0.253152
centralizada_Descentralizada                                          0.167049
grupo_Si                                                              0.005014
pime_Si                                                               0.143840
pago_adelantado_Si                                                    0.000430
liquidacion_Si                                                        0.131375
obligacion_ambiente_Si                                                0.024499
estado_bpin_Válido                                                    0.536963
prorrogado_Si                                                         0.154011
postconflicto_Si                                                      0.004585
dtype: float64

In [230]:
cumplen=(df_onehot.sum(axis=0)/df_onehot.shape[0]>0.1) & (df_onehot.sum(axis=0)/df_onehot.shape[0]<0.9)
df_onehot=df_onehot.loc[:,cumplen]
df_onehot.head()

,sector_No aplica/No pertenece,sector_Salud y Protección Social,sector_Servicio Público,rama_Corporación Autónoma,rama_Ejecutivo,tipo_contrato_Prestación de servicios,modalidad_contratacion_Contratación directa,modalidad_contratacion_Contratación régimen especial,dias_espera_inicio_q_0,dias_espera_inicio_q_1,dias_espera_inicio_q_2,duracion_contrato_q_0,duracion_contrato_q_1,duracion_contrato_q_2,duracion_contrato_q_3,dias_desde_primer_contrato_q_0,dias_desde_primer_contrato_q_1,dias_desde_primer_contrato_q_2,dias_desde_primer_contrato_q_3,valor_contratoo_q_0,valor_contratoo_q_1,valor_contratoo_q_2,valor_contratoo_q_3,centralizada_Descentralizada,pime_Si,liquidacion_Si,estado_bpin_Válido,prorrogado_Si
14,False,False,False,True,False,True,True,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False
19,False,False,False,False,True,False,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True,True,True
29,False,False,False,False,True,True,True,False,False,False,True,True,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False
31,False,False,False,True,False,True,True,False,True,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False
36,False,True,False,False,True,True,True,False,True,False,False,False,False,True,False,True,False,False,False,False,True,False,False,True,False,False,False,True

### 4.4.1 MINERÍA DE ITEMSETS FRECUENTES

In [231]:
freqitems = apriori(df_onehot, min_support=0.08, use_colnames=True)
freqitems.sort_values('support',ascending=True)

      support                                           itemsets
277  0.080372  frozenset({tipo_contrato_Prestación de servici...
429  0.080659  frozenset({tipo_contrato_Prestación de servici...
128  0.080659  frozenset({dias_espera_inicio_q_2, duracion_co...
111  0.080659  frozenset({dias_espera_inicio_q_0, dias_desde_...
140  0.081089  frozenset({valor_contratoo_q_1, duracion_contr...
353  0.081232  frozenset({tipo_contrato_Prestación de servici...
145  0.081232  frozenset({valor_contratoo_q_2, duracion_contr...
165  0.081232  frozenset({dias_espera_inicio_q_0, modalidad_c...
315  0.081232  frozenset({valor_contratoo_q_3, modalidad_cont...
85   0.081519  frozenset({tipo_contrato_Prestación de servici...
437  0.081519  frozenset({tipo_contrato_Prestación de servici...
233  0.081519  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
384  0.081519  frozenset({rama_Ejecutivo, modalidad_contratac...
136  0.081662  frozenset({valor_contratoo_q_0, duracion_contr...
158  0.081805  frozenset({centralizada_Descentralizada, estad...
115  0.082378  frozenset({dias_espera_inicio_q_1, duracion_co...
164  0.082521  frozenset({modalidad_contratacion_Contratación...
268  0.082521  frozenset({dias_espera_inicio_q_1, tipo_contra...
365  0.083095  frozenset({tipo_contrato_Prestación de servici...
363  0.083095  frozenset({tipo_contrato_Prestación de servici...
269  0.083095  frozenset({dias_espera_inicio_q_1, tipo_contra...
267  0.083238  frozenset({dias_desde_primer_contrato_q_1, tip...
163  0.083238  frozenset({tipo_contrato_Prestación de servici...
374  0.083381  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
355  0.083811  frozenset({dias_espera_inicio_q_1, tipo_contra...
386  0.083954  frozenset({rama_Ejecutivo, modalidad_contratac...
400  0.083954  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
433  0.083954  frozenset({dias_espera_inicio_q_1, tipo_contra...
366  0.084097  frozenset({valor_contratoo_q_2, tipo_contrato_...
326  0.084097  frozenset({valor_contratoo_q_3, duracion_contr...
381  0.084384  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
39   0.084527  frozenset({sector_Servicio Público, dias_esper...
402  0.084670  frozenset({dias_espera_inicio_q_1, tipo_contra...
129  0.084670  frozenset({dias_desde_primer_contrato_q_1, dia...
212  0.084670  frozenset({rama_Ejecutivo, prorrogado_Si, moda...
215  0.084957  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
123  0.084957  frozenset({dias_espera_inicio_q_1, valor_contr...
357  0.085100  frozenset({dias_espera_inicio_q_1, tipo_contra...
271  0.085244  frozenset({dias_espera_inicio_q_1, tipo_contra...
423  0.085387  frozenset({tipo_contrato_Prestación de servici...
297  0.085387  frozenset({dias_espera_inicio_q_1, duracion_co...
225  0.085673  frozenset({duracion_contrato_q_1, rama_Ejecuti...
228  0.085817  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
325  0.086103  frozenset({valor_contratoo_q_0, duracion_contr...
403  0.086819  frozenset({dias_espera_inicio_q_1, tipo_contra...
436  0.086963  frozenset({tipo_contrato_Prestación de servici...
124  0.086963  frozenset({dias_espera_inicio_q_1, valor_contr...
404  0.087249  frozenset({dias_espera_inicio_q_1, tipo_contra...
113  0.087393  frozenset({valor_contratoo_q_1, dias_espera_in...
412  0.087822  frozenset({duracion_contrato_q_1, valor_contra...
385  0.087966  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
298  0.087966  frozenset({dias_espera_inicio_q_1, modalidad_c...
108  0.087966  frozenset({duracion_contrato_q_1, dias_espera_...
362  0.088109  frozenset({tipo_contrato_Prestación de servici...
307  0.088252  frozenset({duracion_contrato_q_1, modalidad_co...
450  0.088252  frozenset({tipo_contrato_Prestación de servici...
411  0.088395  frozenset({tipo_contrato_Prestación de servici...
161  0.088539  frozenset({rama_Ejecutivo, sector_No aplica/No...
218  0.088825  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
109  0.088825  frozenset({dias_espera_inicio_q_0, dias_desde_...
319  0.088825  frozenset({valor_contratoo_q_0, modalidad_cont...
122  0.088968  frozenset({dias_espera_inicio_q_1, dias_desde_...
219  0.089398  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
135  0.089685  frozenset({duracion_contrato_q_1, dias_desde_p...
430  0.089828  frozenset({dias_espera_inicio_q_1, tipo_contra...
260  0.090115  frozenset({tipo_contrato_Prestación de servici...
414  0.090258  frozenset({tipo_contrato_Prestación de servici...
130  0.090258  frozenset({dias_espera_inicio_q_2, valor_contr...
263  0.090258  frozenset({dias_espera_inicio_q_1, tipo_contra...
409  0.090401  frozenset({tipo_contrato_Prestación de servici...
327  0.090544  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
299  0.090544  frozenset({dias_espera_inicio_q_1, modalidad_c...
286  0.090688  frozenset({tipo_contrato_Prestación de servici...
46   0.090688  frozenset({rama_Ejecutivo, modalidad_contratac...
110  0.090831  frozenset({dias_espera_inicio_q_0, dias_desde_...
306  0.090974  frozenset({modalidad_contratacion_Contratación...
332  0.090974  frozenset({dias_espera_inicio_q_1, sector_Serv...
216  0.091261  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
406  0.091404  frozenset({dias_espera_inicio_q_1, tipo_contra...
35   0.091691  frozenset({dias_espera_inicio_q_0, sector_Salu...
237  0.091691  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
301  0.091691  frozenset({dias_espera_inicio_q_1, modalidad_c...
309  0.092407  frozenset({modalidad_contratacion_Contratación...
120  0.092550  frozenset({dias_desde_primer_contrato_q_1, dia...
446  0.092693  frozenset({tipo_contrato_Prestación de servici...
356  0.092693  frozenset({dias_espera_inicio_q_1, tipo_contra...
121  0.092693  frozenset({dias_espera_inicio_q_1, dias_desde_...
144  0.092837  frozenset({dias_desde_primer_contrato_q_1, dur...
330  0.092980  frozenset({dias_espera_inicio_q_1, sector_Serv...
213  0.093123  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
441  0.093266  frozenset({tipo_contrato_Prestación de servici...
227  0.093266  frozenset({rama_Ejecutivo, dias_desde_primer_c...
175  0.093553  frozenset({tipo_contrato_Prestación de servici...
360  0.093696  frozenset({tipo_contrato_Prestación de servici...
304  0.093983  frozenset({modalidad_contratacion_Contratación...
264  0.094126  frozenset({dias_espera_inicio_q_1, tipo_contra...
428  0.094126  frozenset({tipo_contrato_Prestación de servici...
105  0.094556  frozenset({prorrogado_Si, modalidad_contrataci...
440  0.094842  frozenset({tipo_contrato_Prestación de servici...
116  0.094986  frozenset({dias_espera_inicio_q_1, duracion_co...
31   0.095272  frozenset({sector_No aplica/No pertenece, esta...
334  0.095272  frozenset({dias_espera_inicio_q_1, sector_Serv...
217  0.095272  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
276  0.095559  frozenset({tipo_contrato_Prestación de servici...
389  0.096132  frozenset({rama_Ejecutivo, modalidad_contratac...
379  0.096275  frozenset({tipo_contrato_Prestación de servici...
278  0.096418  frozenset({duracion_contrato_q_1, valor_contra...
173  0.096562  frozenset({dias_espera_inicio_q_1, sector_Serv...
405  0.096848  frozenset({dias_espera_inicio_q_1, tipo_contra...
300  0.097421  frozenset({dias_espera_inicio_q_1, modalidad_c...
399  0.097564  frozenset({rama_Ejecutivo, modalidad_contratac...
415  0.097708  frozenset({valor_contratoo_q_2, tipo_contrato_...
310  0.097851  frozenset({valor_contratoo_q_2, modalidad_cont...
148  0.097851  frozenset({valor_contratoo_q_3, dias_desde_pri...
106  0.097851  frozenset({dias_espera_inicio_q_0, modalidad_c...
43   0.098138  frozenset({rama_Corporación Autónoma, modalida...
351  0.098424  frozenset({tipo_contrato_Prestación de servici...
171  0.098567  frozenset({dias_espera_inicio_q_1, sector_Serv...
395  0.098711  frozenset({modalidad_contratacion_Contratación...
375  0.098711  frozenset({tipo_contrato_Prestación de servici...
432  0.099140  frozenset({tipo_contrato_Prestación de servici...
265  0.099140  frozenset({dias_espera_inicio_q_1, tipo_contra...
137  0.100143  frozenset({duracion_contrato_q_1, valor_contra...
390  0.100287  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
210  0.100573  frozenset({centralizada_Descentralizada, rama_...
261  0.100716  frozenset({tipo_contrato_Prestación de servici...
107  0.101003  frozenset({dias_espera_inicio_q_0, duracion_co...
424  0.101146  frozenset({tipo_contrato_Prestación de servici...
168  0.101289  frozenset({dias_espera_inicio_q_1, sector_Serv...
117  0.101433  frozenset({dias_espera_inicio_q_1, duracion_co...
290  0.101576  frozenset({tipo_contrato_Prestación de servici...
68   0.101576  frozenset({tipo_contrato_Prestación de servici...
445  0.102149  frozenset({tipo_contrato_Prestación de servici...
270  0.102149  frozenset({dias_espera_inicio_q_1, tipo_contra...
380  0.102292  frozenset({rama_Ejecutivo, modalidad_contratac...
354  0.102292  frozenset({tipo_contrato_Prestación de servici...
410  0.102292  frozenset({tipo_contrato_Prestación de servici...
280  0.102579  frozenset({tipo_contrato_Prestación de servici...
369  0.103295  frozenset({tipo_contrato_Prestación de servici...
32   0.103438  frozenset({rama_Ejecutivo, sector_Salud y Prot...
447  0.103438  frozenset({tipo_contrato_Prestación de servici...
305  0.103438  frozenset({valor_contratoo_q_0, duracion_contr...
281  0.104011  frozenset({valor_contratoo_q_2, tipo_contrato_...
396  0.104011  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
295  0.104011  frozenset({tipo_contrato_Prestación de servici...
324  0.104155  frozenset({modalidad_contratacion_Contratación...
394  0.104298  frozenset({rama_Ejecutivo, modalidad_contratac...
376  0.104728  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
417  0.105301  frozenset({tipo_contrato_Prestación de servici...
361  0.105731  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
368  0.105874  frozenset({tipo_contrato_Prestación de servici...
141  0.106304  frozenset({valor_contratoo_q_2, duracion_contr...
224  0.106590  frozenset({rama_Ejecutivo, duracion_contrato_q...
194  0.106590  frozenset({tipo_contrato_Prestación de servici...
373  0.107020  frozenset({tipo_contrato_Prestación de servici...
40   0.107163  frozenset({dias_espera_inicio_q_1, sector_Serv...
125  0.107163  frozenset({dias_espera_inicio_q_1, valor_contr...
401  0.107163  frozenset({tipo_contrato_Prestación de servici...
312  0.107307  frozenset({modalidad_contratacion_Contratación...
239  0.107450  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
291  0.107593  frozenset({tipo_contrato_Prestación de servici...
418  0.107736  frozenset({tipo_contrato_Prestación de servici...
320  0.108166  frozenset({modalidad_contratacion_Contratación...
64   0.108166        frozenset({rama_Ejecutivo, liquidacion_Si})
126  0.109026  frozenset({dias_espera_inicio_q_1, valor_contr...
328  0.109312  frozenset({tipo_contrato_Prestación de servici...
118  0.109312  frozenset({dias_espera_inicio_q_1, duracion_co...
230  0.109742  frozenset({rama_Ejecutivo, duracion_contrato_q...
266  0.110602  frozenset({dias_espera_inicio_q_1, tipo_contra...
438  0.110745  frozenset({tipo_contrato_Prestación de servici...
296  0.110888  frozenset({modalidad_contratacion_Contratación...
262  0.111175  frozenset({tipo_contrato_Prestación de servici...
33   0.112464  frozenset({tipo_contrato_Prestación de servici...
387  0.112607  frozenset({modalidad_contratacion_Contratación...
364  0.113324  frozenset({tipo_contrato_Prestación de servici...
152  0.113467  frozenset({valor_contratoo_q_0, dias_desde_pri...
119  0.113897  frozenset({dias_espera_inicio_q_1, dias_desde_...
443  0.113897  frozenset({tipo_contrato_Prestación de servici...
160  0.114040  frozenset({rama_Ejecutivo, sector_No aplica/No...
274  0.114183  frozenset({tipo_contrato_Prestación de servici...
258  0.114183  frozenset({tipo_contrato_Prestación de servici...
439  0.114470  frozenset({tipo_contrato_Prestación de servici...
448  0.114613  frozenset({tipo_contrato_Prestación de servici...
214  0.114900  frozenset({rama_Ejecutivo, dias_espera_inicio_...
425  0.114900  frozenset({tipo_contrato_Prestación de servici...
371  0.114900  frozenset({tipo_contrato_Prestación de servici...
392  0.114900  frozenset({rama_Ejecutivo, modalidad_contratac...
444  0.115330  frozenset({tipo_contrato_Prestación de servici...
321  0.115473  frozenset({valor_contratoo_q_0, modalidad_cont...
139  0.115473  frozenset({dias_desde_primer_contrato_q_2, dur...
422  0.115473  frozenset({tipo_contrato_Prestación de servici...
63   0.115616               frozenset({rama_Ejecutivo, pime_Si})
397  0.116046  frozenset({modalidad_contratacion_Contratación...
388  0.116046  frozenset({modalidad_contratacion_Contratación...
34   0.116189  frozenset({modalidad_contratacion_Contratación...
292  0.116476  frozenset({tipo_contrato_Prestación de servici...
377  0.116619  frozenset({tipo_contrato_Prestación de servici...
134  0.116619  frozenset({duracion_contrato_q_0, estado_bpin_...
313  0.116619  frozenset({valor_contratoo_q_3, modalidad_cont...
103  0.117192  frozenset({centralizada_Descentralizada, modal...
442  0.117335  frozenset({tipo_contrato_Prestación de servici...
222  0.117335  frozenset({rama_Ejecutivo, duracion_contrato_q...
159  0.117479  frozenset({tipo_contrato_Prestación de servici...
318  0.117622  frozenset({modalidad_contratacion_Contratación...
449  0.117765  frozenset({tipo_contrato_Prestación de servici...
367  0.117908  frozenset({tipo_contrato_Prestación de servici...
393  0.118052  frozenset({dias_desde_primer_contrato_q_1, ram...
398  0.118338  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
234  0.118338  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
223  0.118768  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
339  0.118911  frozenset({tipo_contrato_Prestación de servici...
372  0.119054  frozenset({dias_desde_primer_contrato_q_1, tip...
236  0.119628  frozenset({rama_Ejecutivo, dias_desde_primer_c...
420  0.119628  frozenset({tipo_contrato_Prestación de servici...
154  0.119628  frozenset({valor_contratoo_q_0, estado_bpin_Vá...
370  0.120344  frozenset({tipo_contrato_Prestación de servici...
289  0.120487  frozenset({tipo_contrato_Prestación de servici...
240  0.120487  frozenset({rama_Ejecutivo, valor_contratoo_q_1...
316  0.120630  frozenset({modalidad_contratacion_Contratación...
226  0.121490  frozenset({rama_Ejecutivo, duracion_contrato_q...
238  0.121490  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
419  0.121490  frozenset({tipo_contrato_Prestación de servici...
413  0.121920  frozenset({tipo_contrato_Prestación de servici...
231  0.121920  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
287  0.122063  frozenset({tipo_contrato_Prestación de servici...
378  0.122063  frozenset({valor_contratoo_q_2, tipo_contrato_...
198  0.122636  frozenset({rama_Ejecutivo, duracion_contrato_q...
426  0.122779  frozenset({tipo_contrato_Prestación de servici...
283  0.122923  frozenset({tipo_contrato_Prestación de servici...
421  0.123352  frozenset({dias_desde_primer_contrato_q_1, tip...
391  0.123352  frozenset({rama_Ejecutivo, modalidad_contratac...
66   0.123496         frozenset({rama_Ejecutivo, prorrogado_Si})
350  0.123496  frozenset({tipo_contrato_Prestación de servici...
112  0.123639  frozenset({valor_contratoo_q_0, dias_espera_in...
308  0.124212  frozenset({modalidad_contratacion_Contratación...
322  0.124355  frozenset({modalidad_contratacion_Contratación...
284  0.124355  frozenset({tipo_contrato_Prestación de servici...
279  0.124642  frozenset({tipo_contrato_Prestación de servici...
192  0.124785  frozenset({tipo_contrato_Prestación de servici...
114  0.125072  frozenset({dias_espera_inicio_q_0, estado_bpin...
293  0.125501  frozenset({tipo_contrato_Prestación de servici...
149  0.125931  frozenset({estado_bpin_Válido, dias_desde_prim...
317  0.126074  frozenset({dias_desde_primer_contrato_q_1, mod...
285  0.126504  frozenset({tipo_contrato_Prestación de servici...
314  0.127794  frozenset({modalidad_contratacion_Contratación...
416  0.127794  frozenset({tipo_contrato_Prestación de servici...
427  0.127794  frozenset({valor_contratoo_q_2, tipo_contrato_...
241  0.127794  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
288  0.128080  frozenset({dias_desde_primer_contrato_q_1, tip...
323  0.128510  frozenset({valor_contratoo_q_2, modalidad_cont...
143  0.128510  frozenset({duracion_contrato_q_3, dias_desde_p...
162  0.128797  frozenset({tipo_contrato_Prestación de servici...
229  0.129226  frozenset({rama_Ejecutivo, duracion_contrato_q...
311  0.129513  frozenset({modalidad_contratacion_Contratación...
155  0.129943  frozenset({valor_contratoo_q_1, estado_bpin_Vá...
275  0.130659  frozenset({tipo_contrato_Prestación de servici...
435  0.131089  frozenset({tipo_contrato_Prestación de servici...
25   0.131375                        frozenset({liquidacion_Si})
282  0.131519  frozenset({tipo_contrato_Prestación de servici...
87   0.132092  frozenset({tipo_contrato_Prestación de servici...
294  0.132235  frozenset({valor_contratoo_q_2, tipo_contrato_...
28   0.133095  frozenset({rama_Ejecutivo, sector_No aplica/No...
235  0.133238  frozenset({dias_desde_primer_contrato_q_1, ram...
153  0.133668  frozenset({estado_bpin_Válido, dias_desde_prim...
138  0.133811  frozenset({duracion_contrato_q_1, estado_bpin_...
346  0.133811  frozenset({tipo_contrato_Prestación de servici...
151  0.134384  frozenset({dias_desde_primer_contrato_q_2, est...
232  0.135387  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
30   0.135673  frozenset({sector_No aplica/No pertenece, moda...
209  0.136246  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
242  0.136963  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
359  0.138252  frozenset({tipo_contrato_Prestación de servici...
156  0.138252  frozenset({valor_contratoo_q_2, estado_bpin_Vá...
383  0.138395  frozenset({modalidad_contratacion_Contratación...
431  0.139685  frozenset({tipo_contrato_Prestación de servici...
408  0.140258  frozenset({tipo_contrato_Prestación de servici...
246  0.140401  frozenset({tipo_contrato_Prestación de servici...
42   0.140831  frozenset({tipo_contrato_Prestación de servici...
29   0.140831  frozenset({tipo_contrato_Prestación de servici...
62   0.141691  frozenset({rama_Ejecutivo, centralizada_Descen...
150  0.142980  frozenset({dias_desde_primer_contrato_q_1, est...
142  0.143266  frozenset({duracion_contrato_q_2, estado_bpin_...
147  0.143266  frozenset({estado_bpin_Válido, duracion_contra...
205  0.143553  frozenset({rama_Ejecutivo, modalidad_contratac...
24   0.143840                               frozenset({pime_Si})
257  0.143983  frozenset({tipo_contrato_Prestación de servici...
333  0.144413  frozenset({sector_Servicio Público, rama_Ejecu...
91   0.144699  frozenset({duracion_contrato_q_0, modalidad_co...
191  0.144699  frozenset({tipo_contrato_Prestación de servici...
84   0.144986  frozenset({tipo_contrato_Prestación de servici...
335  0.145845  frozenset({sector_Servicio Público, modalidad_...
132  0.145989  frozenset({duracion_contrato_q_0, dias_desde_p...
331  0.146418  frozenset({sector_Servicio Público, rama_Ejecu...
303  0.147708  frozenset({modalidad_contratacion_Contratación...
273  0.148281  frozenset({tipo_contrato_Prestación de servici...
157  0.149140  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
146  0.149284  frozenset({valor_contratoo_q_3, duracion_contr...
180  0.149427  frozenset({tipo_contrato_Prestación de servici...
345  0.149570  frozenset({tipo_contrato_Prestación de servici...
133  0.149857  frozenset({valor_contratoo_q_0, duracion_contr...
174  0.150716  frozenset({sector_Servicio Público, modalidad_...
347  0.151289  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
172  0.152579  frozenset({sector_Servicio Público, tipo_contr...
253  0.153725  frozenset({tipo_contrato_Prestación de servici...
27   0.154011                         frozenset({prorrogado_Si})
7    0.155444  frozenset({modalidad_contratacion_Contratación...

In [232]:
freqitems =fpgrowth(df_onehot, min_support=0.08, use_colnames=True)
freqitems.sort_values('support',ascending=True).head(300)

      support                                           itemsets
438  0.080372  frozenset({tipo_contrato_Prestación de servici...
48   0.080659  frozenset({dias_espera_inicio_q_2, duracion_co...
152  0.080659  frozenset({dias_espera_inicio_q_0, dias_desde_...
119  0.080659  frozenset({tipo_contrato_Prestación de servici...
311  0.081089  frozenset({valor_contratoo_q_1, duracion_contr...
117  0.081232  frozenset({valor_contratoo_q_3, modalidad_cont...
361  0.081232  frozenset({valor_contratoo_q_2, duracion_contr...
390  0.081232  frozenset({dias_espera_inicio_q_0, modalidad_c...
175  0.081232  frozenset({tipo_contrato_Prestación de servici...
243  0.081519  frozenset({tipo_contrato_Prestación de servici...
449  0.081519  frozenset({tipo_contrato_Prestación de servici...
236  0.081519  frozenset({rama_Ejecutivo, modalidad_contratac...
118  0.081519  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
432  0.081662  frozenset({valor_contratoo_q_0, duracion_contr...
335  0.081805  frozenset({centralizada_Descentralizada, estad...
222  0.082378  frozenset({dias_espera_inicio_q_1, duracion_co...
279  0.082521  frozenset({dias_espera_inicio_q_1, tipo_contra...
425  0.082521  frozenset({modalidad_contratacion_Contratación...
331  0.083095  frozenset({tipo_contrato_Prestación de servici...
319  0.083095  frozenset({dias_espera_inicio_q_1, tipo_contra...
277  0.083095  frozenset({tipo_contrato_Prestación de servici...
214  0.083238  frozenset({dias_desde_primer_contrato_q_1, tip...
424  0.083238  frozenset({tipo_contrato_Prestación de servici...
167  0.083381  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
66   0.083811  frozenset({dias_espera_inicio_q_1, tipo_contra...
91   0.083954  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
126  0.083954  frozenset({dias_espera_inicio_q_1, tipo_contra...
242  0.083954  frozenset({rama_Ejecutivo, modalidad_contratac...
116  0.084097  frozenset({valor_contratoo_q_3, duracion_contr...
385  0.084097  frozenset({valor_contratoo_q_2, tipo_contrato_...
125  0.084384  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
395  0.084527  frozenset({sector_Servicio Público, dias_esper...
173  0.084670  frozenset({rama_Ejecutivo, prorrogado_Si, moda...
200  0.084670  frozenset({dias_desde_primer_contrato_q_1, dia...
448  0.084670  frozenset({dias_espera_inicio_q_1, tipo_contra...
298  0.084957  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
182  0.084957  frozenset({dias_espera_inicio_q_1, valor_contr...
369  0.085100  frozenset({dias_espera_inicio_q_1, tipo_contra...
96   0.085244  frozenset({dias_espera_inicio_q_1, tipo_contra...
168  0.085387  frozenset({tipo_contrato_Prestación de servici...
447  0.085387  frozenset({dias_espera_inicio_q_1, duracion_co...
329  0.085673  frozenset({duracion_contrato_q_1, rama_Ejecuti...
383  0.085817  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
246  0.086103  frozenset({valor_contratoo_q_0, duracion_contr...
299  0.086819  frozenset({dias_espera_inicio_q_1, tipo_contra...
234  0.086963  frozenset({tipo_contrato_Prestación de servici...
312  0.086963  frozenset({dias_espera_inicio_q_1, valor_contr...
67   0.087249  frozenset({dias_espera_inicio_q_1, tipo_contra...
310  0.087393  frozenset({valor_contratoo_q_1, dias_espera_in...
330  0.087822  frozenset({tipo_contrato_Prestación de servici...
233  0.087966  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
430  0.087966  frozenset({duracion_contrato_q_1, dias_espera_...
297  0.087966  frozenset({dias_espera_inicio_q_1, modalidad_c...
240  0.088109  frozenset({tipo_contrato_Prestación de servici...
328  0.088252  frozenset({duracion_contrato_q_1, valor_contra...
94   0.088252  frozenset({tipo_contrato_Prestación de servici...
241  0.088395  frozenset({tipo_contrato_Prestación de servici...
423  0.088539  frozenset({rama_Ejecutivo, sector_No aplica/No...
102  0.088825  frozenset({dias_espera_inicio_q_0, dias_desde_...
367  0.088825  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
166  0.088825  frozenset({valor_contratoo_q_0, modalidad_cont...
151  0.088968  frozenset({dias_espera_inicio_q_1, dias_desde_...
95   0.089398  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
429  0.089685  frozenset({duracion_contrato_q_1, dias_desde_p...
414  0.089828  frozenset({dias_espera_inicio_q_1, tipo_contra...
174  0.090115  frozenset({tipo_contrato_Prestación de servici...
446  0.090258  frozenset({dias_espera_inicio_q_1, tipo_contra...
278  0.090258  frozenset({tipo_contrato_Prestación de servici...
71   0.090258  frozenset({dias_espera_inicio_q_2, valor_contr...
235  0.090401  frozenset({tipo_contrato_Prestación de servici...
65   0.090544  frozenset({dias_espera_inicio_q_1, modalidad_c...
88   0.090544  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
115  0.090688  frozenset({tipo_contrato_Prestación de servici...
388  0.090688  frozenset({rama_Ejecutivo, modalidad_contratac...
265  0.090831  frozenset({dias_espera_inicio_q_0, dias_desde_...
413  0.090974  frozenset({dias_espera_inicio_q_1, sector_Serv...
239  0.090974  frozenset({modalidad_contratacion_Contratación...
64   0.091261  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
370  0.091404  frozenset({dias_espera_inicio_q_1, tipo_contra...
368  0.091691  frozenset({dias_espera_inicio_q_1, modalidad_c...
165  0.091691  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
342  0.091691  frozenset({dias_espera_inicio_q_0, sector_Salu...
276  0.092407  frozenset({modalidad_contratacion_Contratación...
201  0.092550  frozenset({dias_desde_primer_contrato_q_1, dia...
162  0.092693  frozenset({tipo_contrato_Prestación de servici...
268  0.092693  frozenset({dias_espera_inicio_q_1, dias_desde_...
124  0.092693  frozenset({dias_espera_inicio_q_1, tipo_contra...
202  0.092837  frozenset({dias_desde_primer_contrato_q_1, dur...
411  0.092980  frozenset({dias_espera_inicio_q_1, sector_Serv...
195  0.093123  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
84   0.093266  frozenset({tipo_contrato_Prestación de servici...
275  0.093266  frozenset({rama_Ejecutivo, dias_desde_primer_c...
137  0.093553  frozenset({tipo_contrato_Prestación de servici...
247  0.093696  frozenset({tipo_contrato_Prestación de servici...
230  0.093983  frozenset({modalidad_contratacion_Contratación...
296  0.094126  frozenset({dias_espera_inicio_q_1, tipo_contra...
93   0.094126  frozenset({tipo_contrato_Prestación de servici...
170  0.094556  frozenset({prorrogado_Si, modalidad_contrataci...
113  0.094842  frozenset({tipo_contrato_Prestación de servici...
433  0.094986  frozenset({dias_espera_inicio_q_1, duracion_co...
418  0.095272  frozenset({sector_No aplica/No pertenece, esta...
122  0.095272  frozenset({dias_espera_inicio_q_1, rama_Ejecut...
412  0.095272  frozenset({dias_espera_inicio_q_1, sector_Serv...
238  0.095559  frozenset({tipo_contrato_Prestación de servici...
112  0.096132  frozenset({rama_Ejecutivo, modalidad_contratac...
92   0.096275  frozenset({tipo_contrato_Prestación de servici...
327  0.096418  frozenset({tipo_contrato_Prestación de servici...
410  0.096562  frozenset({dias_espera_inicio_q_1, sector_Serv...
127  0.096848  frozenset({dias_espera_inicio_q_1, tipo_contra...
123  0.097421  frozenset({dias_espera_inicio_q_1, modalidad_c...
90   0.097564  frozenset({rama_Ejecutivo, modalidad_contratac...
384  0.097708  frozenset({valor_contratoo_q_2, tipo_contrato_...
389  0.097851  frozenset({dias_espera_inicio_q_0, modalidad_c...
100  0.097851  frozenset({valor_contratoo_q_3, dias_desde_pri...
382  0.097851  frozenset({valor_contratoo_q_2, modalidad_cont...
136  0.098138  frozenset({rama_Corporación Autónoma, modalida...
339  0.098424  frozenset({tipo_contrato_Prestación de servici...
409  0.098567  frozenset({dias_espera_inicio_q_1, sector_Serv...
161  0.098711  frozenset({tipo_contrato_Prestación de servici...
159  0.098711  frozenset({modalidad_contratacion_Contratación...
262  0.099140  frozenset({tipo_contrato_Prestación de servici...
63   0.099140  frozenset({dias_espera_inicio_q_1, tipo_contra...
314  0.100143  frozenset({duracion_contrato_q_1, valor_contra...
83   0.100287  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
338  0.100573  frozenset({centralizada_Descentralizada, rama_...
194  0.100716  frozenset({tipo_contrato_Prestación de servici...
220  0.101003  frozenset({dias_espera_inicio_q_0, duracion_co...
160  0.101146  frozenset({tipo_contrato_Prestación de servici...
408  0.101289  frozenset({dias_espera_inicio_q_1, sector_Serv...
290  0.101433  frozenset({dias_espera_inicio_q_1, duracion_co...
164  0.101576  frozenset({tipo_contrato_Prestación de servici...
387  0.101576  frozenset({tipo_contrato_Prestación de servici...
366  0.102149  frozenset({dias_espera_inicio_q_1, tipo_contra...
286  0.102149  frozenset({tipo_contrato_Prestación de servici...
232  0.102292  frozenset({tipo_contrato_Prestación de servici...
259  0.102292  frozenset({tipo_contrato_Prestación de servici...
261  0.102292  frozenset({rama_Ejecutivo, modalidad_contratac...
274  0.102579  frozenset({tipo_contrato_Prestación de servici...
85   0.103295  frozenset({tipo_contrato_Prestación de servici...
341  0.103438  frozenset({rama_Ejecutivo, sector_Salud y Prot...
193  0.103438  frozenset({tipo_contrato_Prestación de servici...
229  0.103438  frozenset({valor_contratoo_q_0, duracion_contr...
192  0.104011  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
89   0.104011  frozenset({tipo_contrato_Prestación de servici...
381  0.104011  frozenset({valor_contratoo_q_2, tipo_contrato_...
87   0.104155  frozenset({modalidad_contratacion_Contratación...
285  0.104298  frozenset({rama_Ejecutivo, modalidad_contratac...
191  0.104728  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
111  0.105301  frozenset({tipo_contrato_Prestación de servici...
226  0.105731  frozenset({rama_Ejecutivo, tipo_contrato_Prest...
114  0.105874  frozenset({tipo_contrato_Prestación de servici...
364  0.106304  frozenset({valor_contratoo_q_2, duracion_contr...
237  0.106590  frozenset({rama_Ejecutivo, duracion_contrato_q...
172  0.106590  frozenset({tipo_contrato_Prestación de servici...
283  0.107020  frozenset({tipo_contrato_Prestación de servici...
360  0.107163  frozenset({dias_espera_inicio_q_1, valor_contr...
396  0.107163  frozenset({dias_espera_inicio_q_1, sector_Serv...
260  0.107163  frozenset({tipo_contrato_Prestación de servici...
109  0.107307  frozenset({modalidad_contratacion_Contratación...
189  0.107450  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
158  0.107593  frozenset({tipo_contrato_Prestación de servici...
82   0.107736  frozenset({tipo_contrato_Prestación de servici...
157  0.108166  frozenset({modalidad_contratacion_Contratación...
176  0.108166        frozenset({rama_Ejecutivo, liquidacion_Si})
74   0.109026  frozenset({dias_espera_inicio_q_1, valor_contr...
51   0.109312  frozenset({dias_espera_inicio_q_1, duracion_co...
422  0.109312  frozenset({tipo_contrato_Prestación de servici...
110  0.109742  frozenset({rama_Ejecutivo, duracion_contrato_q...
121  0.110602  frozenset({dias_espera_inicio_q_1, tipo_contra...
445  0.110745  frozenset({tipo_contrato_Prestación de servici...
258  0.110888  frozenset({modalidad_contratacion_Contratación...
257  0.111175  frozenset({tipo_contrato_Prestación de servici...
340  0.112464  frozenset({tipo_contrato_Prestación de servici...
444  0.112607  frozenset({modalidad_contratacion_Contratación...
443  0.113324  frozenset({tipo_contrato_Prestación de servici...
150  0.113467  frozenset({valor_contratoo_q_0, dias_desde_pri...
134  0.113897  frozenset({tipo_contrato_Prestación de servici...
103  0.113897  frozenset({dias_espera_inicio_q_1, dias_desde_...
421  0.114040  frozenset({rama_Ejecutivo, sector_No aplica/No...
245  0.114183  frozenset({tipo_contrato_Prestación de servici...
337  0.114183  frozenset({tipo_contrato_Prestación de servici...
306  0.114470  frozenset({tipo_contrato_Prestación de servici...
326  0.114613  frozenset({tipo_contrato_Prestación de servici...
190  0.114900  frozenset({tipo_contrato_Prestación de servici...
256  0.114900  frozenset({rama_Ejecutivo, dias_espera_inicio_...
133  0.114900  frozenset({tipo_contrato_Prestación de servici...
132  0.114900  frozenset({rama_Ejecutivo, modalidad_contratac...
213  0.115330  frozenset({tipo_contrato_Prestación de servici...
188  0.115473  frozenset({valor_contratoo_q_0, modalidad_cont...
267  0.115473  frozenset({dias_desde_primer_contrato_q_2, dur...
284  0.115473  frozenset({tipo_contrato_Prestación de servici...
450  0.115616               frozenset({rama_Ejecutivo, pime_Si})
325  0.116046  frozenset({modalidad_contratacion_Contratación...
305  0.116046  frozenset({modalidad_contratacion_Contratación...
386  0.116189  frozenset({modalidad_contratacion_Contratación...
187  0.116476  frozenset({tipo_contrato_Prestación de servici...
80   0.116619  frozenset({valor_contratoo_q_3, modalidad_cont...
324  0.116619  frozenset({tipo_contrato_Prestación de servici...
219  0.116619  frozenset({duracion_contrato_q_0, estado_bpin_...
334  0.117192  frozenset({centralizada_Descentralizada, modal...
62   0.117335  frozenset({tipo_contrato_Prestación de servici...
244  0.117335  frozenset({rama_Ejecutivo, duracion_contrato_q...
420  0.117479  frozenset({tipo_contrato_Prestación de servici...
282  0.117622  frozenset({modalidad_contratacion_Contratación...
380  0.117765  frozenset({tipo_contrato_Prestación de servici...
304  0.117908  frozenset({tipo_contrato_Prestación de servici...
212  0.118052  frozenset({dias_desde_primer_contrato_q_1, ram...
130  0.118338  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
379  0.118338  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
225  0.118768  frozenset({rama_Ejecutivo, valor_contratoo_q_0...
231  0.118911  frozenset({tipo_contrato_Prestación de servici...
210  0.119054  frozenset({dias_desde_primer_contrato_q_1, tip...
180  0.119628  frozenset({valor_contratoo_q_0, estado_bpin_Vá...
131  0.119628  frozenset({tipo_contrato_Prestación de servici...
281  0.119628  frozenset({rama_Ejecutivo, dias_desde_primer_c...
61   0.120344  frozenset({tipo_contrato_Prestación de servici...
280  0.120487  frozenset({tipo_contrato_Prestación de servici...
322  0.120487  frozenset({rama_Ejecutivo, valor_contratoo_q_1...
129  0.120630  frozenset({modalidad_contratacion_Contratación...
60   0.121490  frozenset({tipo_contrato_Prestación de servici...
156  0.121490  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
441  0.121490  frozenset({rama_Ejecutivo, duracion_contrato_q...
81   0.121920  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
442  0.121920  frozenset({tipo_contrato_Prestación de servici...
128  0.122063  frozenset({tipo_contrato_Prestación de servici...
378  0.122063  frozenset({valor_contratoo_q_2, tipo_contrato_...
228  0.122636  frozenset({rama_Ejecutivo, duracion_contrato_q...
323  0.122779  frozenset({tipo_contrato_Prestación de servici...
108  0.122923  frozenset({tipo_contrato_Prestación de servici...
211  0.123352  frozenset({dias_desde_primer_contrato_q_1, tip...
59   0.123352  frozenset({rama_Ejecutivo, modalidad_contratac...
78   0.123496  frozenset({tipo_contrato_Prestación de servici...
169  0.123496         frozenset({rama_Ejecutivo, prorrogado_Si})
181  0.123639  frozenset({valor_contratoo_q_0, dias_espera_in...
440  0.124212  frozenset({modalidad_contratacion_Contratación...
321  0.124355  frozenset({modalidad_contratacion_Contratación...
79   0.124355  frozenset({tipo_contrato_Prestación de servici...
439  0.124642  frozenset({tipo_contrato_Prestación de servici...
336  0.124785  frozenset({tipo_contrato_Prestación de servici...
251  0.125072  frozenset({dias_espera_inicio_q_0, estado_bpin...
320  0.125501  frozenset({tipo_contrato_Prestación de servici...
104  0.125931  frozenset({estado_bpin_Válido, dias_desde_prim...
209  0.126074  frozenset({dias_desde_primer_contrato_q_1, mod...
58   0.126504  frozenset({tipo_contrato_Prestación de servici...
57   0.127794  frozenset({modalidad_contratacion_Contratación...
303  0.127794  frozenset({tipo_contrato_Prestación de servici...
377  0.127794  frozenset({valor_contratoo_q_2, tipo_contrato_...
376  0.127794  frozenset({valor_contratoo_q_2, rama_Ejecutivo...
208  0.128080  frozenset({dias_desde_primer_contrato_q_1, tip...
375  0.128510  frozenset({valor_contratoo_q_2, modalidad_cont...
99   0.128510  frozenset({duracion_contrato_q_3, dias_desde_p...
419  0.128797  frozenset({tipo_contrato_Prestación de servici...
302  0.129226  frozenset({rama_Ejecutivo, duracion_contrato_q...
301  0.129513  frozenset({modalidad_contratacion_Contratación...
313  0.129943  frozenset({valor_contratoo_q_1, estado_bpin_Vá...
224  0.130659  frozenset({tipo_contrato_Prestación de servici...
44   0.131089  frozenset({tipo_contrato_Prestación de servici...
11   0.131375                        frozenset({liquidacion_Si})
300  0.131519  frozenset({tipo_contrato_Prestación de servici...
171  0.132092  frozenset({tipo_contrato_Prestación de servici...
374  0.132235  frozenset({valor_contratoo_q_2, tipo_contrato_...
417  0.133095  frozenset({rama_Ejecutivo, sector_No aplica/No...
207  0.133238  frozenset({dias_desde_primer_contrato_q_1, ram...
148  0.133668  frozenset({estado_bpin_Válido, dias_desde_prim...
431  0.133811  frozenset({duracion_contrato_q_1, estado_bpin_...
155  0.133811  frozenset({tipo_contrato_Prestación de servici...
269  0.134384  frozenset({dias_desde_primer_contrato_q_2, est...
56   0.135387  frozenset({rama_Ejecutivo, estado_bpin_Válido,...
416  0.135673  frozenset({sector_No aplica/No pertenece, moda...
77   0.136246  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
86   0.136963  frozenset({rama_Ejecutivo, valor_contratoo_q_3...
45   0.138252  frozenset({tipo_contrato_Prestación de servici...
363  0.138252  frozenset({valor_contratoo_q_2, estado_bpin_Vá...
42   0.138395  frozenset({modalidad_contratacion_Contratación...
407  0.139685  frozenset({tipo_contrato_Prestación de servici...
43   0.140258  frozenset({tipo_contrato_Prestación de servici...
227  0.140401  frozenset({tipo_contrato_Prestación de servici...
135  0.140831  frozenset({tipo_contrato_Prestación de servici...
415  0.140831  frozenset({tipo_contrato_Prestación de servici...
333  0.141691  frozenset({rama_Ejecutivo, centralizada_Descen...
199  0.142980  frozenset({dias_desde_primer_contrato_q_1, est...
291  0.143266  frozenset({duracion_contrato_q_2, estado_bpin_...
50   0.143266  frozenset({estado_bpin_Válido, duracion_contra...
153  0.143553  frozenset({rama_Ejecutivo, modalidad_contratac...
27   0.143840                               frozenset({pime_Si})
76   0.143983  frozenset({tipo_contrato_Prestación de servici...
406  0.144413  frozenset({sector_Servicio Público, rama_Ejecu...
218  0.144699  frozenset({duracion_contrato_q_0, modalidad_co...
75   0.144699  frozenset({tipo_contrato_Prestación de servici...
332  0.144986  frozenset({tipo_contrato_Prestación de servici...
405  0.145845  frozenset({sector_Servicio Público, modalidad_...
221  0.145989  frozenset({duracion_contrato_q_0, dias_desde_p...
404  0.146418  frozenset({sector_Servicio Público, rama_Ejecu...
40   0.147708  frozenset({modalidad_contratacion_Contratación...
41   0.148281  frozenset({tipo_contrato_Prestación de servici...
73   0.149140  frozenset({valor_contratoo_q_3, estado_bpin_Vá...
70   0.149284  frozenset({valor_contratoo_q_3, duracion_contr...
223  0.149427  frozenset({tipo_contrato_Prestación de servici...
272  0.149570  frozenset({tipo_contrato_Prestación de servici...
217  0.149857  frozenset({valor_contratoo_q_0, duracion_contr...

In [233]:
freqitems.shape

(451, 2)

### 4.1.2 MINERÍA DE REGLAS DE ASOCIACIÓN

In [240]:
rules = association_rules(freqitems, metric="lift", min_threshold=1.5)

rules.loc[:, "pearson"] = rules["leverage"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"] *
    (1 - rules["antecedent support"]) * (1 - rules["consequent support"])
)

rules.loc[:, "cosine"] = rules["support"] / np.sqrt(
    rules["antecedent support"] * rules["consequent support"]
)

rules.loc[:, "jaccard"] = rules["support"] / (
    rules["antecedent support"] + rules["consequent support"] - rules["support"]
)

rules.loc[:, "kuczynski"] = (rules["support"] / 2) * (
    1 / rules["antecedent support"] + 1 / rules["consequent support"]
)

rules.loc[:, "certainty"] = (
    rules["confidence"] - rules["consequent support"]
) / (1 - rules["consequent support"])

rules.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
0,frozenset({valor_contratoo_q_3}),frozenset({duracion_contrato_q_3}),0.253152,0.256017,0.149284,0.589700,2.303361,1.0,0.084472,1.813266,0.757653,0.414809,0.448509,0.586400,0.445136,0.586391,0.586400
1,frozenset({duracion_contrato_q_3}),frozenset({valor_contratoo_q_3}),0.256017,0.253152,0.149284,0.583100,2.303361,1.0,0.084472,1.791433,0.760571,0.414809,0.441788,0.586400,0.445136,0.586391,0.586400
2,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.175931,0.256017,0.124355,0.706840,2.760910,1.0,0.079314,2.537808,0.773965,0.404285,0.605959,0.596285,0.477287,0.585947,0.596285
3,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.216619,0.253152,0.124355,0.574074,2.267706,1.0,0.069518,1.753470,0.713606,0.360017,0.429702,0.532651,0.388110,0.531038,0.532651
4,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.253152,0.216619,0.124355,0.491228,2.267706,1.0,0.069518,1.539749,0.748513,0.360017,0.350544,0.532651,0.388110,0.531038,0.532651
5,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256017,0.175931,0.124355,0.485730,2.760910,1.0,0.079314,1.602406,0.857279,0.404285,0.375938,0.596285,0.477287,0.585947,0.596285
6,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({duracion_contrato_q_3}),0.159599,0.256017,0.116619,0.730700,2.854106,1.0,0.075759,2.762656,0.772997,0.390034,0.638030,0.593106,0.473979,0.576925,0.593106
7,frozenset({modalidad_contratacion_Contratación...,frozenset({valor_contratoo_q_3}),0.200000,0.253152,0.116619,0.583095,2.303339,1.0,0.065989,1.791409,0.707310,0.346530,0.441780,0.521881,0.379404,0.518279,0.521881
8,frozenset({valor_contratoo_q_3}),frozenset({modalidad_contratacion_Contratación...,0.253152,0.200000,0.116619,0.460668,2.303339,1.0,0.065989,1.483316,0.757648,0.346530,0.325835,0.521881,0.379404,0.518279,0.521881
9,frozenset({duracion_contrato_q_3}),"frozenset({valor_contratoo_q_3, modalidad_cont...",0.256017,0.159599,0.116619,0.455512,2.854106,1.0,0.075759,1.543471,0.873176,0.390034,0.352109,0.593106,0.473979,0.576925,0.593106
10,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({duracion_contrato_q_3}),0.206590,0.256017,0.121920,0.590153,2.305129,1.0,0.069029,1.815268,0.713610,0.357864,0.449117,0.533185,0.390672,0.530133,0.533185
11,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_3}),0.213897,0.253152,0.121920,0.569993,2.251586,1.0,0.067771,1.736829,0.707119,0.353259,0.424238,0.525800,0.380100,0.523940,0.525800
12,frozenset({valor_contratoo_q_3}),"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.253152,0.213897,0.121920,0.481607,2.251586,1.0,0.067771,1.516424,0.744286,0.353259,0.340554,0.525800,0.380100,0.523940,0.525800
13,frozenset({duracion_contrato_q_3}),"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.256017,0.206590,0.121920,0.476217,2.305129,1.0,0.069029,1.514768,0.761019,0.357864,0.339833,0.533185,0.390672,0.530133,0.533185
14,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.143983,0.256017,0.107736,0.748259,2.922689,1.0,0.070874,2.955347,0.768500,0.368627,0.661630,0.584538,0.462569,0.561142,0.584538
15,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.184241,0.253152,0.107736,0.584759,2.309914,1.0,0.061096,1.798589,0.695160,0.326814,0.444009,0.505170,0.362434,0.498860,0.505170
16,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.175931,0.200000,0.107736,0.612378,3.061889,1.0,0.072550,2.063866,0.817170,0.401709,0.515472,0.575530,0.476349,0.574349,0.575530
17,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.216619,0.159599,0.107736,0.497354,3.116279,1.0,0.073164,1.671956,0.866889,0.401281,0.401898,0.586200,0.484960,0.579428,0.586200
18,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159599,0.216619,0.107736,0.675045,3.116279,1.0,0.073164,2.410736,0.808072,0.401281,0.585189,0.586200,0.484960,0.579428,0.586200
19,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.200000,0.175931,0.107736,0.538682,3.061889,1.0,0.072550,1.786335,0.841755,0.401709,0.440195,0.575530,0.476349,0.574349,0.575530
20,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.253152,0.184241,0.107736,0.425580,2.309914,1.0,0.061096,1.420145,0.759302,0.326814,0.295846,0.505170,0.362434,0.498860,0.505170
21,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256017,0.143983,0.107736,0.420817,2.922689,1.0,0.070874,1.477974,0.884227,0.368627,0.323398,0.584538,0.462569,0.561142,0.584538
22,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({duracion_contrato_q_3}),0.136246,0.256017,0.100287,0.736067,2.875070,1.0,0.065405,2.818835,0.755056,0.343474,0.645244,0.563893,0.436856,0.536964,0.563893
23,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({valor_contratoo_q_3}),0.174212,0.253152,0.100287,0.575658,2.273963,1.0,0.056184,1.760014,0.678430,0.306614,0.431823,0.485905,0.340672,0.477544,0.485905
24,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({modalidad_contratacion_Contratación...,0.206590,0.200000,0.100287,0.485437,2.427184,1.0,0.058968,1.554717,0.741105,0.327409,0.356796,0.493435,0.364130,0.493370,0.493435
25,"frozenset({rama_Ejecutivo, duracion_contrato_q...","frozenset({valor_contratoo_q_3, modalidad_cont...",0.213897,0.159599,0.100287,0.468855,2.937707,1.0,0.066149,1.582243,0.839074,0.367069,0.367986,0.548610,0.440476,0.542782,0.548610
26,"frozenset({valor_contratoo_q_3, modalidad_cont...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.159599,0.213897,0.100287,0.628366,2.937707,1.0,0.066149,2.115263,0.784861,0.367069,0.527246,0.548610,0.440476,0.542782,0.548610
27,frozenset({modalidad_contratacion_Contratación...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.200000,0.206590,0.100287,0.501433,2.427184,1.0,0.058968,1.591379,0.735000,0.327409,0.371614,0.493435,0.364130,0.493370,0.493435
28,frozenset({valor_contratoo_q_3}),"frozenset({rama_Ejecutivo, modalidad_contratac...",0.253152,0.174212,0.100287,0.396152,2.273963,1.0,0.056184,1.367542,0.750138,0.306614,0.268761,0.485905,0.340672,0.477544,0.485905
29,frozenset({duracion_contrato_q_3}),"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",0.256017,0.136246,0.100287,0.391718,2.875070,1.0,0.065405,1.419989,0.876609,0.343474,0.295769,0.563893,0.436856,0.536964,0.563893
30,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.123496,0.256017,0.093266,0.755220,2.949882,1.0,0.061649,3.039399,0.754136,0.325826,0.670988,0.559759,0.429349,0.524524,0.559759
31,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.162034,0.253152,0.093266,0.575597,2.273721,1.0,0.052247,1.759761,0.668515,0.289720,0.431741,0.472009,0.326091,0.460502,0.472009
32,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.144699,0.200000,0.093266,0.644554,3.222772,1.0,0.064327,2.250696,0.806392,0.370940,0.555693,0.555443,0.457129,0.548249,0.555443
33,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.183811,0.159599,0.093266,0.507405,3.179249,1.0,0.063930,1.706068,0.839830,0.372852,0.413857,0.545893,0.450680,0.544534,0.545893
34,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.143983,0.213897,0.093266,0.647761,3.028381,1.0,0.062469,2.231734,0.782450,0.352463,0.551918,0.541898,0.433936,0.531457,0.541898
35,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.184241,0.206590,0.093266,0.506221,2.450362,1.0,0.055204,1.606811,0.725578,0.313433,0.377649,0.478839,0.351718,0.478055,0.478839
36,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({tipo_contrato_Prestación de servici...,0.136246,0.216619,0.093266,0.684543,3.160124,1.0,0.063753,2.483318,0.791379,0.359272,0.597313,0.557549,0.451136,0.542894,0.557549
37,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({tipo_contrato_Prestación de servici...,0.174212,0.175931,0.093266,0.535362,3.043018,1.0,0.062617,1.773571,0.813016,0.363079,0.436166,0.532746,0.433577,0.532740,0.532746
38,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, modalidad_contratac...",0.175931,0.174212,0.093266,0.530130,3.043018,1.0,0.062617,1.757483,0.814712,0.363079,0.431004,0.532746,0.433577,0.532740,0.532746
39,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",0.216619,0.136246,0.093266,0.430556,3.160124,1.0,0.063753,1.516836,0.872572,0.359272,0.340733,0.557549,0.451136,0.542894,0.557549
40,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",frozenset({tipo_contrato_Prestación de servici...,0.206590,0.184241,0.093266,0.451456,2.450362,1.0,0.055204,1.487136,0.746017,0.313433,0.327567,0.478839,0.351718,0.478055,0.478839
41,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.213897,0.143983,0.093266,0.436035,3.028381,1.0,0.062469,1.517855,0.852039,0.352463,0.341175,0.541898,0.433936,0.531457,0.541898
42,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159599,0.183811,0.093266,0.584381,3.179249,1.0,0.063930,1.963790,0.815635,0.372852,0.490781,0.545893,0.450680,0.544534,0.545893
43,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.200000,0.144699,0.093266,0.466332,3.222772,1.0,0.064327,1.602685,0.862135,0.370940,0.376047,0.555443,0.457129,0.548249,0.555443
44,frozenset({valor_contratoo_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.253152,0.162034,0.093266,0.368421,2.273721,1.0,0.052247,1.326779,0.750075,0.289720,0.246295,0.472009,0.326091,0.460502,0.472009
45,frozenset({duracion_contrato_q_3}),frozenset({tipo_contrato_Prestación de servici...,0.256017,0.123496,0.093266,0.364298,2.949882,1.0,0.061649,1.378797,0.888466,0.325826,0.274730,0.559759,0.429349,0.524524,0.559759
46,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.144699,0.256017,0.103295,0.713861,2.788334,1.0,0.066250,2.600078,0.749868,0.347303,0.615396,0.558665,0.431494,0.536676,0.558665
47,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_3}),0.183811,0.253152,0.103295,0.561964,2.219870,1.0,0.056763,1.704993,0.673279,0.309575,0.413487,0.485000,0.337037,0.478855,0.485000
48,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.175931,0.213897,0.103295,0.587134,2.744938,1.0,0.065664,1.904013,0.771408,0.360500,0.474794,0.535027,0.420564,0.532484,0.535027
49,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.216619,0.206590,0.103295,0.476852,2.308201,1.0,0.058544,1.516606,0.723482,0.322884,0.340633,0.488426,0.351028,0.488289,0.488426

In [241]:
rules_sub=rules[(rules.confidence > 0.5)&(rules.zhangs_metric > 0.5)].sort_values(by='lift',ascending=False)
rules_sub.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,pearson,cosine,kuczynski
380,frozenset({modalidad_contratacion_Contratación...,"frozenset({dias_espera_inicio_q_0, sector_Salu...",0.155444,0.091691,0.081232,0.522581,5.699395,1.0,0.066979,1.902540,0.976303,0.489637,0.474387,0.704259,0.640561,0.680422,0.704259
377,"frozenset({dias_espera_inicio_q_0, sector_Salu...",frozenset({modalidad_contratacion_Contratación...,0.091691,0.155444,0.081232,0.885937,5.699395,1.0,0.066979,7.404325,0.907777,0.489637,0.864944,0.704259,0.640561,0.680422,0.704259
376,"frozenset({dias_espera_inicio_q_0, modalidad_c...",frozenset({sector_Salud y Protección Social}),0.097851,0.156447,0.081232,0.830161,5.306341,1.0,0.065924,4.966782,0.899570,0.469371,0.798662,0.674696,0.610772,0.656540,0.674696
381,frozenset({sector_Salud y Protección Social}),"frozenset({dias_espera_inicio_q_0, modalidad_c...",0.156447,0.097851,0.081232,0.519231,5.306341,1.0,0.065924,1.876470,0.962057,0.469371,0.467084,0.674696,0.610772,0.656540,0.674696
372,frozenset({modalidad_contratacion_Contratación...,frozenset({sector_Salud y Protección Social}),0.155444,0.156447,0.116189,0.747465,4.777755,1.0,0.091870,3.340347,0.936228,0.593704,0.700630,0.745070,0.697966,0.745066,0.745070
373,frozenset({sector_Salud y Protección Social}),frozenset({modalidad_contratacion_Contratación...,0.156447,0.155444,0.116189,0.742674,4.777755,1.0,0.091870,3.282046,0.937341,0.593704,0.695312,0.745070,0.697966,0.745066,0.745070
147,"frozenset({valor_contratoo_q_3, dias_desde_pri...",frozenset({tipo_contrato_Prestación de servici...,0.097851,0.216619,0.080659,0.824305,3.805321,1.0,0.059463,4.458744,0.817171,0.344975,0.775722,0.598330,0.485834,0.554016,0.598330
148,"frozenset({duracion_contrato_q_3, dias_desde_p...",frozenset({tipo_contrato_Prestación de servici...,0.128510,0.175931,0.080659,0.627648,3.567574,1.0,0.058050,2.213143,0.825824,0.360435,0.548154,0.543058,0.455565,0.536430,0.543058
141,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.090688,0.256017,0.080659,0.889415,3.474046,1.0,0.057441,6.727730,0.783176,0.303177,0.851361,0.602234,0.458330,0.529352,0.602234
239,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, tipo_contrato_Prest...",0.144699,0.178223,0.086963,0.600990,3.372115,1.0,0.061174,2.059539,0.822459,0.368549,0.514454,0.544466,0.454375,0.541524,0.544466
127,"frozenset({valor_contratoo_q_3, dias_desde_pri...",frozenset({duracion_contrato_q_3}),0.097851,0.256017,0.084097,0.859444,3.356976,1.0,0.059046,5.293128,0.778267,0.311737,0.811076,0.593964,0.455357,0.531331,0.593964
246,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.144699,0.192120,0.090401,0.624752,3.251881,1.0,0.062601,2.152925,0.809640,0.366860,0.535516,0.547648,0.451681,0.542193,0.547648
32,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.144699,0.200000,0.093266,0.644554,3.222772,1.0,0.064327,2.250696,0.806392,0.370940,0.555693,0.555443,0.457129,0.548249,0.555443
42,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159599,0.183811,0.093266,0.584381,3.179249,1.0,0.063930,1.963790,0.815635,0.372852,0.490781,0.545893,0.450680,0.544534,0.545893
33,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_3, modalidad_cont...",0.183811,0.159599,0.093266,0.507405,3.179249,1.0,0.063930,1.706068,0.839830,0.372852,0.413857,0.545893,0.450680,0.544534,0.545893
233,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({tipo_contrato_Prestación de servici...,0.122636,0.223496,0.086963,0.709112,3.172822,1.0,0.059554,2.669428,0.780546,0.335544,0.625388,0.549107,0.435819,0.525278,0.549107
215,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({tipo_contrato_Prestación de servici...,0.144699,0.223496,0.102292,0.706931,3.163062,1.0,0.069953,2.649559,0.799544,0.384698,0.622579,0.582312,0.477315,0.568820,0.582312
36,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({tipo_contrato_Prestación de servici...,0.136246,0.216619,0.093266,0.684543,3.160124,1.0,0.063753,2.483318,0.791379,0.359272,0.597313,0.557549,0.451136,0.542894,0.557549
18,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.159599,0.216619,0.107736,0.675045,3.116279,1.0,0.073164,2.410736,0.808072,0.401281,0.585189,0.586200,0.484960,0.579428,0.586200
267,"frozenset({valor_contratoo_q_0, dias_desde_pri...",frozenset({duracion_contrato_q_0}),0.113467,0.243553,0.086103,0.758838,3.115701,1.0,0.058468,3.136681,0.765956,0.317821,0.681192,0.556184,0.429486,0.517950,0.556184
230,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.149427,0.187106,0.086963,0.581975,3.110403,1.0,0.059004,1.944606,0.797695,0.348450,0.485757,0.523377,0.424376,0.520086,0.523377
16,frozenset({tipo_contrato_Prestación de servici...,frozenset({modalidad_contratacion_Contratación...,0.175931,0.200000,0.107736,0.612378,3.061889,1.0,0.072550,2.063866,0.817170,0.401709,0.515472,0.575530,0.476349,0.574349,0.575530
19,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.200000,0.175931,0.107736,0.538682,3.061889,1.0,0.072550,1.786335,0.841755,0.401709,0.440195,0.575530,0.476349,0.574349,0.575530
38,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, modalidad_contratac...",0.175931,0.174212,0.093266,0.530130,3.043018,1.0,0.062617,1.757483,0.814712,0.363079,0.431004,0.532746,0.433577,0.532740,0.532746
37,"frozenset({rama_Ejecutivo, modalidad_contratac...",frozenset({tipo_contrato_Prestación de servici...,0.174212,0.175931,0.093266,0.535362,3.043018,1.0,0.062617,1.773571,0.813016,0.363079,0.436166,0.532746,0.433577,0.532740,0.532746
231,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.140401,0.203725,0.086963,0.619388,3.040314,1.0,0.058360,2.092090,0.780697,0.338162,0.522009,0.523126,0.417085,0.514193,0.523126
34,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.143983,0.213897,0.093266,0.647761,3.028381,1.0,0.062469,2.231734,0.782450,0.352463,0.551918,0.541898,0.433936,0.531457,0.541898
223,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.144699,0.203725,0.087966,0.607921,2.984028,1.0,0.058487,2.030904,0.777367,0.337734,0.507608,0.519854,0.412773,0.512340,0.519854
232,"frozenset({rama_Ejecutivo, valor_contratoo_q_0...",frozenset({tipo_contrato_Prestación de servici...,0.157736,0.186533,0.086963,0.551317,2.955601,1.0,0.057540,1.813011,0.785573,0.337973,0.448431,0.508761,0.405256,0.506978,0.508761
30,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.123496,0.256017,0.093266,0.755220,2.949882,1.0,0.061649,3.039399,0.754136,0.325826,0.670988,0.559759,0.429349,0.524524,0.559759
26,"frozenset({valor_contratoo_q_3, modalidad_cont...","frozenset({rama_Ejecutivo, duracion_contrato_q...",0.159599,0.213897,0.100287,0.628366,2.937707,1.0,0.066149,2.115263,0.784861,0.367069,0.527246,0.548610,0.440476,0.542782,0.548610
213,frozenset({tipo_contrato_Prestación de servici...,"frozenset({valor_contratoo_q_0, modalidad_cont...",0.186533,0.187106,0.102292,0.548387,2.930890,1.0,0.067391,1.799980,0.809875,0.376980,0.444438,0.547547,0.443601,0.547547,0.547547
214,"frozenset({valor_contratoo_q_0, modalidad_cont...",frozenset({tipo_contrato_Prestación de servici...,0.187106,0.186533,0.102292,0.546708,2.930890,1.0,0.067391,1.794574,0.810446,0.376980,0.442765,0.547547,0.443601,0.547547,0.547547
14,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.143983,0.256017,0.107736,0.748259,2.922689,1.0,0.070874,2.955347,0.768500,0.368627,0.661630,0.584538,0.462569,0.561142,0.584538
247,frozenset({modalidad_contratacion_Contratación...,frozenset({tipo_contrato_Prestación de servici...,0.166332,0.186533,0.090401,0.543497,2.913678,1.0,0.059375,1.781953,0.787833,0.344432,0.438818,0.514068,0.409325,0.513225,0.514068
22,"frozenset({rama_Ejecutivo, valor_contratoo_q_3...",frozenset({duracion_contrato_q_3}),0.136246,0.256017,0.100287,0.736067,2.875070,1.0,0.065405,2.818835,0.755056,0.343474,0.645244,0.563893,0.436856,0.536964,0.563893
6,"frozenset({valor_contratoo_q_3, modalidad_cont...",frozenset({duracion_contrato_q_3}),0.159599,0.256017,0.116619,0.730700,2.854106,1.0,0.075759,2.762656,0.772997,0.390034,0.638030,0.593106,0.473979,0.576925,0.593106
63,"frozenset({estado_bpin_Válido, duracion_contra...","frozenset({rama_Ejecutivo, valor_contratoo_q_3})",0.143266,0.206590,0.083954,0.586000,2.836533,1.0,0.054357,1.916449,0.755727,0.315733,0.478202,0.496190,0.383225,0.487995,0.496190
227,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.118911,0.258883,0.086963,0.731325,2.824931,1.0,0.056179,2.758419,0.733194,0.299015,0.637474,0.533621,0.396238,0.495645,0.533621
254,"frozenset({duracion_contrato_q_0, modalidad_co...","frozenset({rama_Ejecutivo, dias_desde_primer_c...",0.144699,0.199857,0.081519,0.563366,2.818851,1.0,0.052600,1.832528,0.754408,0.309913,0.454306,0.485626,0.373892,0.479363,0.485626
211,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.140401,0.258883,0.102292,0.728571,2.814294,1.0,0.065945,2.730433,0.749967,0.344428,0.633758,0.561851,0.433364,0.536545,0.561851
46,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.144699,0.256017,0.103295,0.713861,2.788334,1.0,0.066250,2.600078,0.749868,0.347303,0.615396,0.558665,0.431494,0.536676,0.558665
198,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",0.186533,0.203725,0.105731,0.566820,2.782282,1.0,0.067729,1.838209,0.787472,0.371601,0.455992,0.542904,0.431693,0.542377,0.542904
197,"frozenset({rama_Ejecutivo, valor_contratoo_q_0})",frozenset({tipo_contrato_Prestación de servici...,0.203725,0.186533,0.105731,0.518987,2.782282,1.0,0.067729,1.691155,0.804474,0.371601,0.408688,0.542904,0.431693,0.542377,0.542904
219,"frozenset({rama_Ejecutivo, duracion_contrato_q...",frozenset({valor_contratoo_q_0}),0.122636,0.258883,0.087966,0.717290,2.770715,1.0,0.056217,2.621473,0.728412,0.299658,0.618535,0.528540,0.391269,0.493688,0.528540
203,"frozenset({duracion_contrato_q_0, modalidad_co...",frozenset({valor_contratoo_q_0}),0.144699,0.258883,0.103438,0.714851,2.761297,1.0,0.065978,2.599058,0.745763,0.344630,0.615245,0.557204,0.428168,0.534438,0.557204
2,frozenset({tipo_contrato_Prestación de servici...,frozenset({duracion_contrato_q_3}),0.175931,0.256017,0.124355,0.706840,2.760910,1.0,0.079314,2.537808,0.773965,0.404285,0.605959,0.596285,0.477287,0.585947,0.596285
48,frozenset({tipo_contrato_Prestación de servici...,"frozenset({rama_Ejecutivo, duracion_contrato_q...",0.175931,0.213897,0.103295,0.587134,2.744938,1.0,0.065664,1.904013,0.771408,0.360500,0.474794,0.535027,0.420564,0.532484,0.535027
195,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.149427,0.258883,0.105731,0.707574,2.733187,1.0,0.067047,2.534379,0.745529,0.349432,0.605426,0.557993,0.429350,0.537570,0.557993
187,frozenset({tipo_contrato_Prestación de servici...,frozenset({valor_contratoo_q_0}),0.186533,0.258883,0.130659,0.700461,2.705709,1.0,0.082369,2.474192,0.774968,0.415112,0.595828,0.602582,0.482748,0.594580,0.602582

In [236]:
vals=[len(list(rules_sub.iloc[k,:].consequents)) == 1 for k in range(rules_sub.shape[0])]

In [237]:
np.array(vals).sum()

np.int64(88)

In [238]:
rules_sub.loc[vals,:].consequents.drop_duplicates()

377    frozenset({modalidad_contratacion_Contratación...
376        frozenset({sector_Salud y Protección Social})
141                   frozenset({duracion_contrato_q_3})
267                   frozenset({duracion_contrato_q_0})
227                     frozenset({valor_contratoo_q_0})
250          frozenset({dias_desde_primer_contrato_q_3})
140          frozenset({dias_desde_primer_contrato_q_0})
142                     frozenset({valor_contratoo_q_3})
378                  frozenset({dias_espera_inicio_q_0})
Name: consequents, dtype: object

In [239]:
vals=[list(rules_sub.iloc[k,:].consequents) == ['duracion_contrato_q_0'] for k in range(rules_sub.shape[0])]
print(rules_sub.loc[vals,:].iloc[0,:].antecedents)
rules_sub.loc[vals,:].iloc[0,:]

frozenset({'valor_contratoo_q_0', 'dias_desde_primer_contrato_q_3'})

antecedents           frozenset({valor_contratoo_q_0, dias_desde_pri...
consequents                          frozenset({duracion_contrato_q_0})
antecedent support                                             0.113467
consequent support                                             0.243553
support                                                        0.086103
confidence                                                     0.758838
lift                                                           3.115701
representativity                                                    1.0
leverage                                                       0.058468
conviction                                                     3.136681
zhangs_metric                                                  0.765956
jaccard                                                        0.317821
certainty                                                      0.681192
kulczynski                                                     0.556184
pearson                                                        0.429486
cosine                                                          0.51795
kuczynski                                                      0.556184
Name: 267, dtype: object